language: go
services:
  - docker
go:
  1.8.3
install:
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - export TAG=${TRAVIS_TAG:-latest}
  - docker build -t $DOCKER_ID_USER/wompatti .
  - docker tag $DOCKER_ID_USER/wompatti $DOCKER_ID_USER/wompatti:$TAG
after_success:
  - docker push $DOCKER_ID_USER/wompatti