// Code generated by protoc-gen-go.
// source: add_computer_request.proto
// DO NOT EDIT!

/*
Package WompattiService is a generated protocol buffer package.

It is generated from these files:
	add_computer_request.proto
	add_computer_response.proto
	computer.proto
	edit_computer_request.proto
	edit_computer_response.proto
	fetch_computer_by_id_request.proto
	fetch_computer_by_id_response.proto
	fetch_computers_request.proto
	keijo.proto
	passive_computer_request.proto
	passive_computer_response.proto
	wakeup_request.proto
	wakeup_response.proto
	wompatti_service.proto

It has these top-level messages:
	AddComputerRequest
	AddComputerResponse
	Computer
	RemoveComputerRequest
	RemoveComputerResponse
	EditComputerRequest
	EditComputerResponse
	FetchComputerByIdRequest
	FetchComputerByIdResponse
	FetchComputersRequest
	Keijo
	AddKeijoRequest
	AddKeijoResponse
	EditKeijoRequest
	EditKeijoResponse
	FetchKeijosRequest
	FetchKeijoByIdRequest
	FetchKeijoByIdResponse
	RemoveKeijoRequest
	RemoveKeijoResponse
	TurnOnCecDeviceRequest
	TurnOnCecDeviceResponse
	ChangeKeijoSourceRequest
	ChangeKeijoSourceResponse
	ShutDownCecDeviceRequest
	ShutDownCecDeviceResponse
	FetchCecDevicePowerStatusByKeijoIdRequest
	FetchCecDevicePowerStatusByKeijoIdResponse
	FetchCecTvDeviceSourceByKeijoIdRequest
	FetchCecTvDeviceSourceByKeijoIdResponse
	PassiveComputerRequest
	PassiveComputerResponse
	WakeupRequest
	WakeupResponse
*/
package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddComputerRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mac  string `protobuf:"bytes,2,opt,name=mac" json:"mac,omitempty"`
}

func (m *AddComputerRequest) Reset()                    { *m = AddComputerRequest{} }
func (m *AddComputerRequest) String() string            { return proto.CompactTextString(m) }
func (*AddComputerRequest) ProtoMessage()               {}
func (*AddComputerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddComputerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddComputerRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func init() {
	proto.RegisterType((*AddComputerRequest)(nil), "WompattiService.AddComputerRequest")
}

func init() { proto.RegisterFile("add_computer_request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0x4c, 0x49, 0x89,
	0x4f, 0xce, 0xcf, 0x2d, 0x28, 0x2d, 0x49, 0x2d, 0x8a, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0f, 0xcf, 0xcf, 0x2d, 0x48, 0x2c, 0x29, 0xc9,
	0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0xb2, 0xe2, 0x12, 0x72, 0x4c, 0x49, 0x71, 0x86,
	0xaa, 0x0e, 0x82, 0x28, 0x16, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x13, 0x93, 0x25, 0x98, 0xc0, 0x42,
	0x20, 0x66, 0x12, 0x1b, 0xd8, 0x4c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xab, 0xde,
	0xc3, 0x71, 0x00, 0x00, 0x00,
}
