// Code generated by protoc-gen-go.
// source: computer.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FetchManyComputerByIdResponse_State int32

const (
	FetchManyComputerByIdResponse_SUCCESS   FetchManyComputerByIdResponse_State = 0
	FetchManyComputerByIdResponse_NOT_FOUND FetchManyComputerByIdResponse_State = 1
)

var FetchManyComputerByIdResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var FetchManyComputerByIdResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x FetchManyComputerByIdResponse_State) String() string {
	return proto.EnumName(FetchManyComputerByIdResponse_State_name, int32(x))
}
func (FetchManyComputerByIdResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6, 0}
}

type EditComputerResponse_State int32

const (
	EditComputerResponse_SUCCESS   EditComputerResponse_State = 0
	EditComputerResponse_NOT_FOUND EditComputerResponse_State = 1
)

var EditComputerResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditComputerResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditComputerResponse_State) String() string {
	return proto.EnumName(EditComputerResponse_State_name, int32(x))
}
func (EditComputerResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{11, 0}
}

type RemoveComputerResponse_State int32

const (
	RemoveComputerResponse_SUCCESS   RemoveComputerResponse_State = 0
	RemoveComputerResponse_NOT_FOUND RemoveComputerResponse_State = 1
)

var RemoveComputerResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveComputerResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveComputerResponse_State) String() string {
	return proto.EnumName(RemoveComputerResponse_State_name, int32(x))
}
func (RemoveComputerResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{13, 0}
}

type Computer struct {
	Id             uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ArttuId        uint32 `protobuf:"varint,3,opt,name=arttuId" json:"arttuId,omitempty"`
	DeviceInfoId   uint32 `protobuf:"varint,4,opt,name=deviceInfoId" json:"deviceInfoId,omitempty"`
	WolInterfaceId uint32 `protobuf:"varint,5,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
}

func (m *Computer) Reset()                    { *m = Computer{} }
func (m *Computer) String() string            { return proto.CompactTextString(m) }
func (*Computer) ProtoMessage()               {}
func (*Computer) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Computer) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Computer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Computer) GetArttuId() uint32 {
	if m != nil {
		return m.ArttuId
	}
	return 0
}

func (m *Computer) GetDeviceInfoId() uint32 {
	if m != nil {
		return m.DeviceInfoId
	}
	return 0
}

func (m *Computer) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

type ComputersEdge struct {
	Node   *Computer `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *ComputersEdge) Reset()                    { *m = ComputersEdge{} }
func (m *ComputersEdge) String() string            { return proto.CompactTextString(m) }
func (*ComputersEdge) ProtoMessage()               {}
func (*ComputersEdge) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ComputersEdge) GetNode() *Computer {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ComputersEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type ComputersConnection struct {
	PageInfo   *PageInfo        `protobuf:"bytes,1,opt,name=pageInfo" json:"pageInfo,omitempty"`
	Edges      []*ComputersEdge `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32           `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *ComputersConnection) Reset()                    { *m = ComputersConnection{} }
func (m *ComputersConnection) String() string            { return proto.CompactTextString(m) }
func (*ComputersConnection) ProtoMessage()               {}
func (*ComputersConnection) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *ComputersConnection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *ComputersConnection) GetEdges() []*ComputersEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *ComputersConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type FetchComputerByIdRequest struct {
	ComputerIdt []uint32 `protobuf:"varint,1,rep,packed,name=computerIdt" json:"computerIdt,omitempty"`
}

func (m *FetchComputerByIdRequest) Reset()                    { *m = FetchComputerByIdRequest{} }
func (m *FetchComputerByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchComputerByIdRequest) ProtoMessage()               {}
func (*FetchComputerByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *FetchComputerByIdRequest) GetComputerIdt() []uint32 {
	if m != nil {
		return m.ComputerIdt
	}
	return nil
}

type FetchComputerByIdResponse struct {
	Computers []*Computer `protobuf:"bytes,1,rep,name=computers" json:"computers,omitempty"`
}

func (m *FetchComputerByIdResponse) Reset()                    { *m = FetchComputerByIdResponse{} }
func (m *FetchComputerByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchComputerByIdResponse) ProtoMessage()               {}
func (*FetchComputerByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *FetchComputerByIdResponse) GetComputers() []*Computer {
	if m != nil {
		return m.Computers
	}
	return nil
}

type FetchManyComputerByIdRequest struct {
	Id []uint32 `protobuf:"varint,1,rep,packed,name=id" json:"id,omitempty"`
}

func (m *FetchManyComputerByIdRequest) Reset()                    { *m = FetchManyComputerByIdRequest{} }
func (m *FetchManyComputerByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchManyComputerByIdRequest) ProtoMessage()               {}
func (*FetchManyComputerByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *FetchManyComputerByIdRequest) GetId() []uint32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type FetchManyComputerByIdResponse struct {
	Computer   *Computer                           `protobuf:"bytes,1,opt,name=computer" json:"computer,omitempty"`
	State      FetchManyComputerByIdResponse_State `protobuf:"varint,2,opt,name=state,enum=WompattiService.FetchManyComputerByIdResponse_State" json:"state,omitempty"`
	ComputerId uint32                              `protobuf:"varint,3,opt,name=computerId" json:"computerId,omitempty"`
}

func (m *FetchManyComputerByIdResponse) Reset()                    { *m = FetchManyComputerByIdResponse{} }
func (m *FetchManyComputerByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchManyComputerByIdResponse) ProtoMessage()               {}
func (*FetchManyComputerByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *FetchManyComputerByIdResponse) GetComputer() *Computer {
	if m != nil {
		return m.Computer
	}
	return nil
}

func (m *FetchManyComputerByIdResponse) GetState() FetchManyComputerByIdResponse_State {
	if m != nil {
		return m.State
	}
	return FetchManyComputerByIdResponse_SUCCESS
}

func (m *FetchManyComputerByIdResponse) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

type FetchComputersRequest struct {
	After  uint32 `protobuf:"varint,1,opt,name=after" json:"after,omitempty"`
	Before uint32 `protobuf:"varint,2,opt,name=before" json:"before,omitempty"`
	First  uint32 `protobuf:"varint,3,opt,name=first" json:"first,omitempty"`
	Last   uint32 `protobuf:"varint,4,opt,name=last" json:"last,omitempty"`
}

func (m *FetchComputersRequest) Reset()                    { *m = FetchComputersRequest{} }
func (m *FetchComputersRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchComputersRequest) ProtoMessage()               {}
func (*FetchComputersRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *FetchComputersRequest) GetAfter() uint32 {
	if m != nil {
		return m.After
	}
	return 0
}

func (m *FetchComputersRequest) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

func (m *FetchComputersRequest) GetFirst() uint32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *FetchComputersRequest) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type CreateComputerRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateComputerRequest) Reset()                    { *m = CreateComputerRequest{} }
func (m *CreateComputerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateComputerRequest) ProtoMessage()               {}
func (*CreateComputerRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *CreateComputerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateComputerResponse struct {
	Computer   *Computer   `protobuf:"bytes,1,opt,name=computer" json:"computer,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
}

func (m *CreateComputerResponse) Reset()                    { *m = CreateComputerResponse{} }
func (m *CreateComputerResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateComputerResponse) ProtoMessage()               {}
func (*CreateComputerResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *CreateComputerResponse) GetComputer() *Computer {
	if m != nil {
		return m.Computer
	}
	return nil
}

func (m *CreateComputerResponse) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

type EditComputerRequest struct {
	ComputerId     uint32 `protobuf:"varint,1,opt,name=computerId" json:"computerId,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ArttuId        uint32 `protobuf:"varint,3,opt,name=arttuId" json:"arttuId,omitempty"`
	DeviceInfoId   uint32 `protobuf:"varint,4,opt,name=deviceInfoId" json:"deviceInfoId,omitempty"`
	WolInterfaceId uint32 `protobuf:"varint,5,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
}

func (m *EditComputerRequest) Reset()                    { *m = EditComputerRequest{} }
func (m *EditComputerRequest) String() string            { return proto.CompactTextString(m) }
func (*EditComputerRequest) ProtoMessage()               {}
func (*EditComputerRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *EditComputerRequest) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

func (m *EditComputerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditComputerRequest) GetArttuId() uint32 {
	if m != nil {
		return m.ArttuId
	}
	return 0
}

func (m *EditComputerRequest) GetDeviceInfoId() uint32 {
	if m != nil {
		return m.DeviceInfoId
	}
	return 0
}

func (m *EditComputerRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

type EditComputerResponse struct {
	Computer   *Computer                  `protobuf:"bytes,1,opt,name=computer" json:"computer,omitempty"`
	State      EditComputerResponse_State `protobuf:"varint,2,opt,name=state,enum=WompattiService.EditComputerResponse_State" json:"state,omitempty"`
	ComputerId uint32                     `protobuf:"varint,3,opt,name=computerId" json:"computerId,omitempty"`
}

func (m *EditComputerResponse) Reset()                    { *m = EditComputerResponse{} }
func (m *EditComputerResponse) String() string            { return proto.CompactTextString(m) }
func (*EditComputerResponse) ProtoMessage()               {}
func (*EditComputerResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *EditComputerResponse) GetComputer() *Computer {
	if m != nil {
		return m.Computer
	}
	return nil
}

func (m *EditComputerResponse) GetState() EditComputerResponse_State {
	if m != nil {
		return m.State
	}
	return EditComputerResponse_SUCCESS
}

func (m *EditComputerResponse) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

type RemoveComputerRequest struct {
	ComputerId uint32 `protobuf:"varint,1,opt,name=computerId" json:"computerId,omitempty"`
}

func (m *RemoveComputerRequest) Reset()                    { *m = RemoveComputerRequest{} }
func (m *RemoveComputerRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveComputerRequest) ProtoMessage()               {}
func (*RemoveComputerRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *RemoveComputerRequest) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

type RemoveComputerResponse struct {
	State RemoveComputerResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveComputerResponse_State" json:"state,omitempty"`
}

func (m *RemoveComputerResponse) Reset()                    { *m = RemoveComputerResponse{} }
func (m *RemoveComputerResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveComputerResponse) ProtoMessage()               {}
func (*RemoveComputerResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *RemoveComputerResponse) GetState() RemoveComputerResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveComputerResponse_SUCCESS
}

func init() {
	proto.RegisterType((*Computer)(nil), "WompattiService.Computer")
	proto.RegisterType((*ComputersEdge)(nil), "WompattiService.ComputersEdge")
	proto.RegisterType((*ComputersConnection)(nil), "WompattiService.ComputersConnection")
	proto.RegisterType((*FetchComputerByIdRequest)(nil), "WompattiService.FetchComputerByIdRequest")
	proto.RegisterType((*FetchComputerByIdResponse)(nil), "WompattiService.FetchComputerByIdResponse")
	proto.RegisterType((*FetchManyComputerByIdRequest)(nil), "WompattiService.FetchManyComputerByIdRequest")
	proto.RegisterType((*FetchManyComputerByIdResponse)(nil), "WompattiService.FetchManyComputerByIdResponse")
	proto.RegisterType((*FetchComputersRequest)(nil), "WompattiService.FetchComputersRequest")
	proto.RegisterType((*CreateComputerRequest)(nil), "WompattiService.CreateComputerRequest")
	proto.RegisterType((*CreateComputerResponse)(nil), "WompattiService.CreateComputerResponse")
	proto.RegisterType((*EditComputerRequest)(nil), "WompattiService.EditComputerRequest")
	proto.RegisterType((*EditComputerResponse)(nil), "WompattiService.EditComputerResponse")
	proto.RegisterType((*RemoveComputerRequest)(nil), "WompattiService.RemoveComputerRequest")
	proto.RegisterType((*RemoveComputerResponse)(nil), "WompattiService.RemoveComputerResponse")
	proto.RegisterEnum("WompattiService.FetchManyComputerByIdResponse_State", FetchManyComputerByIdResponse_State_name, FetchManyComputerByIdResponse_State_value)
	proto.RegisterEnum("WompattiService.EditComputerResponse_State", EditComputerResponse_State_name, EditComputerResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveComputerResponse_State", RemoveComputerResponse_State_name, RemoveComputerResponse_State_value)
}

func init() { proto.RegisterFile("computer.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdd, 0x6e, 0x12, 0x41,
	0x14, 0x76, 0xa0, 0xb4, 0x70, 0x70, 0x69, 0x9d, 0x16, 0xb2, 0xad, 0xda, 0x90, 0x31, 0x31, 0x24,
	0x4d, 0xb9, 0xc0, 0x36, 0xbd, 0xd0, 0x1b, 0xdd, 0xd2, 0x64, 0x4d, 0x6c, 0xcd, 0xd0, 0xea, 0x65,
	0xb3, 0xdd, 0x99, 0xc5, 0x4d, 0x60, 0x07, 0x77, 0x87, 0x9a, 0xde, 0x7a, 0xed, 0xa5, 0x4f, 0xe0,
	0x0b, 0xf8, 0x34, 0x3e, 0x83, 0xaf, 0x61, 0x76, 0x76, 0x07, 0xd8, 0x05, 0xaa, 0xa6, 0x31, 0x5e,
	0x31, 0xe7, 0xf0, 0x7d, 0xe7, 0x7c, 0xe7, 0x0f, 0xa0, 0xe6, 0x8a, 0xe1, 0x68, 0x2c, 0x79, 0xd8,
	0x1e, 0x85, 0x42, 0x0a, 0xbc, 0xfe, 0x5e, 0x0c, 0x47, 0x8e, 0x94, 0x7e, 0x8f, 0x87, 0xd7, 0xbe,
	0xcb, 0x77, 0x1e, 0x30, 0x1e, 0x7f, 0x5e, 0xfa, 0x81, 0x27, 0x12, 0xcc, 0xce, 0xfa, 0xc8, 0xe9,
	0xcf, 0x3a, 0xc8, 0x57, 0x04, 0x65, 0x2b, 0x8d, 0x83, 0x6b, 0x50, 0xf0, 0x99, 0x89, 0x9a, 0xa8,
	0x65, 0xd0, 0x82, 0xcf, 0x30, 0x86, 0x95, 0xc0, 0x19, 0x72, 0xb3, 0xd0, 0x44, 0xad, 0x0a, 0x55,
	0x6f, 0x6c, 0xc2, 0x9a, 0x13, 0x4a, 0x39, 0xb6, 0x99, 0x59, 0x54, 0x40, 0x6d, 0x62, 0x02, 0xf7,
	0x93, 0x84, 0x76, 0xe0, 0x09, 0x9b, 0x99, 0x2b, 0xea, 0xeb, 0x8c, 0x0f, 0x3f, 0x85, 0xda, 0x27,
	0x31, 0xb0, 0x03, 0xc9, 0x43, 0xcf, 0x71, 0xb9, 0xcd, 0xcc, 0x92, 0x42, 0xe5, 0xbc, 0xe4, 0x1d,
	0x18, 0x5a, 0x55, 0xd4, 0x65, 0x7d, 0x8e, 0xf7, 0x61, 0x25, 0x10, 0x8c, 0x2b, 0x71, 0xd5, 0xce,
	0x76, 0x3b, 0x57, 0x6b, 0x5b, 0xa3, 0xa9, 0x82, 0xe1, 0x06, 0xac, 0xba, 0xe3, 0x30, 0x12, 0xa1,
	0xd2, 0x6e, 0xd0, 0xd4, 0x22, 0xdf, 0x10, 0x6c, 0x4e, 0x02, 0x5b, 0x22, 0x08, 0xb8, 0x2b, 0x7d,
	0x11, 0xe0, 0x43, 0x28, 0xc7, 0x9d, 0x89, 0x55, 0x2e, 0x4d, 0xf1, 0x36, 0x05, 0xd0, 0x09, 0x14,
	0x1f, 0x40, 0x89, 0xb3, 0x3e, 0x8f, 0xcc, 0x42, 0xb3, 0xd8, 0xaa, 0x76, 0x76, 0x97, 0xca, 0x52,
	0x45, 0xd0, 0x04, 0x8c, 0x77, 0x01, 0xa4, 0x90, 0xce, 0xc0, 0x12, 0xe3, 0x40, 0xa6, 0x5d, 0x9c,
	0xf1, 0x90, 0x17, 0x60, 0x9e, 0x70, 0xe9, 0x7e, 0xd0, 0xe4, 0x57, 0x37, 0x36, 0xa3, 0xfc, 0xe3,
	0x98, 0x47, 0x12, 0x37, 0xa1, 0xaa, 0xc7, 0x6e, 0x33, 0x69, 0xa2, 0x66, 0xb1, 0x65, 0xd0, 0x59,
	0x17, 0x39, 0x87, 0xed, 0x05, 0xec, 0x68, 0x24, 0x82, 0x88, 0xe3, 0x23, 0xa8, 0x68, 0x6c, 0xa4,
	0xc8, 0xb7, 0xf6, 0x72, 0x8a, 0x25, 0x6d, 0x78, 0xa4, 0xa2, 0xbe, 0x71, 0x82, 0x9b, 0x45, 0xba,
	0xf4, 0xea, 0x14, 0x93, 0xd5, 0x21, 0x3f, 0x11, 0x3c, 0x5e, 0x42, 0x48, 0xa5, 0x1c, 0x42, 0x59,
	0x87, 0xff, 0xfd, 0x54, 0x27, 0x50, 0xfc, 0x1a, 0x4a, 0x91, 0x74, 0x64, 0xb2, 0x94, 0xb5, 0xce,
	0xc1, 0x1c, 0xe7, 0xd6, 0xac, 0xed, 0x5e, 0xcc, 0xa5, 0x49, 0x88, 0x78, 0x10, 0xd3, 0xce, 0xe9,
	0x41, 0x4c, 0x3d, 0xe4, 0x09, 0x94, 0x14, 0x1e, 0x57, 0x61, 0xad, 0x77, 0x61, 0x59, 0xdd, 0x5e,
	0x6f, 0xe3, 0x1e, 0x36, 0xa0, 0x72, 0x7a, 0x76, 0x7e, 0x79, 0x72, 0x76, 0x71, 0x7a, 0xbc, 0x81,
	0x88, 0x80, 0x7a, 0xa6, 0xdf, 0x91, 0x6e, 0xc9, 0x16, 0x94, 0x1c, 0x4f, 0x57, 0x67, 0xd0, 0xc4,
	0x88, 0x37, 0xf3, 0x8a, 0x7b, 0x22, 0xe4, 0x7a, 0x33, 0x13, 0x2b, 0x46, 0x7b, 0x7e, 0x18, 0xe9,
	0x7d, 0x48, 0x8c, 0xf8, 0x02, 0x07, 0x4e, 0x24, 0xd3, 0x5b, 0x52, 0x6f, 0xb2, 0x07, 0x75, 0x2b,
	0xe4, 0x8e, 0xe4, 0x93, 0xee, 0xa4, 0x09, 0xf5, 0xb9, 0xa2, 0xe9, 0xb9, 0x92, 0x2f, 0x08, 0x1a,
	0x79, 0xf4, 0xdd, 0x06, 0xf0, 0x1c, 0x60, 0x7a, 0xd2, 0xaa, 0x88, 0x6a, 0xe7, 0xe1, 0x1c, 0xf1,
	0x78, 0x02, 0xa1, 0x33, 0x70, 0xf2, 0x1d, 0xc1, 0x66, 0x97, 0xf9, 0x32, 0x2f, 0x3d, 0x3b, 0x09,
	0x94, 0x9f, 0xc4, 0x7f, 0xfc, 0x25, 0xfa, 0x81, 0x60, 0x2b, 0xab, 0xf8, 0x6e, 0xed, 0x7b, 0x99,
	0xdd, 0xdf, 0xbd, 0x39, 0xce, 0xa2, 0x64, 0xff, 0x60, 0x6d, 0x8f, 0xa0, 0x4e, 0xf9, 0x50, 0x5c,
	0xf3, 0xbf, 0x1c, 0x05, 0xf9, 0x8c, 0xa0, 0x91, 0x67, 0xa6, 0x2d, 0xb1, 0x74, 0x6d, 0x48, 0xd5,
	0xb6, 0x3f, 0x57, 0xdb, 0x62, 0x5e, 0xa6, 0xba, 0x3f, 0x52, 0x7f, 0xb5, 0xaa, 0xfe, 0xbd, 0x9e,
	0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x16, 0x1d, 0xaf, 0x22, 0x04, 0x07, 0x00, 0x00,
}
