// Code generated by protoc-gen-go.
// source: device_type.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateDeviceTypeResponse_State int32

const (
	CreateDeviceTypeResponse_SUCCESS   CreateDeviceTypeResponse_State = 0
	CreateDeviceTypeResponse_NOT_FOUND CreateDeviceTypeResponse_State = 1
)

var CreateDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateDeviceTypeResponse_State) String() string {
	return proto.EnumName(CreateDeviceTypeResponse_State_name, int32(x))
}
func (CreateDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{5, 0}
}

type EditDeviceTypeResponse_State int32

const (
	EditDeviceTypeResponse_SUCCESS   EditDeviceTypeResponse_State = 0
	EditDeviceTypeResponse_NOT_FOUND EditDeviceTypeResponse_State = 1
)

var EditDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditDeviceTypeResponse_State) String() string {
	return proto.EnumName(EditDeviceTypeResponse_State_name, int32(x))
}
func (EditDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{7, 0}
}

type RemoveDeviceTypeResponse_State int32

const (
	RemoveDeviceTypeResponse_SUCCESS   RemoveDeviceTypeResponse_State = 0
	RemoveDeviceTypeResponse_NOT_FOUND RemoveDeviceTypeResponse_State = 1
)

var RemoveDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveDeviceTypeResponse_State) String() string {
	return proto.EnumName(RemoveDeviceTypeResponse_State_name, int32(x))
}
func (RemoveDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{9, 0}
}

type CreateCommandResponse_State int32

const (
	CreateCommandResponse_SUCCESS   CreateCommandResponse_State = 0
	CreateCommandResponse_NOT_FOUND CreateCommandResponse_State = 1
)

var CreateCommandResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateCommandResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateCommandResponse_State) String() string {
	return proto.EnumName(CreateCommandResponse_State_name, int32(x))
}
func (CreateCommandResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{14, 0}
}

type EditCommandReponse_State int32

const (
	EditCommandReponse_SUCCESS   EditCommandReponse_State = 0
	EditCommandReponse_NOT_FOUND EditCommandReponse_State = 1
)

var EditCommandReponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditCommandReponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditCommandReponse_State) String() string {
	return proto.EnumName(EditCommandReponse_State_name, int32(x))
}
func (EditCommandReponse_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{16, 0} }

type RemoveCommandResponse_State int32

const (
	RemoveCommandResponse_SUCCESS   RemoveCommandResponse_State = 0
	RemoveCommandResponse_NOT_FOUND RemoveCommandResponse_State = 1
)

var RemoveCommandResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveCommandResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveCommandResponse_State) String() string {
	return proto.EnumName(RemoveCommandResponse_State_name, int32(x))
}
func (RemoveCommandResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{18, 0}
}

type DeviceType struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DeviceType) Reset()                    { *m = DeviceType{} }
func (m *DeviceType) String() string            { return proto.CompactTextString(m) }
func (*DeviceType) ProtoMessage()               {}
func (*DeviceType) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *DeviceType) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeviceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Command struct {
	Id           uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DeviceTypeId uint32 `protobuf:"varint,2,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value        string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Command) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Command) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DeviceTypesConnection struct {
	PageInfo   *PageInfo          `protobuf:"bytes,1,opt,name=pageInfo" json:"pageInfo,omitempty"`
	Edges      []*DeviceTypesEdge `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32             `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *DeviceTypesConnection) Reset()                    { *m = DeviceTypesConnection{} }
func (m *DeviceTypesConnection) String() string            { return proto.CompactTextString(m) }
func (*DeviceTypesConnection) ProtoMessage()               {}
func (*DeviceTypesConnection) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *DeviceTypesConnection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *DeviceTypesConnection) GetEdges() []*DeviceTypesEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *DeviceTypesConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type DeviceTypesEdge struct {
	Node   *DeviceType `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32      `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *DeviceTypesEdge) Reset()                    { *m = DeviceTypesEdge{} }
func (m *DeviceTypesEdge) String() string            { return proto.CompactTextString(m) }
func (*DeviceTypesEdge) ProtoMessage()               {}
func (*DeviceTypesEdge) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *DeviceTypesEdge) GetNode() *DeviceType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *DeviceTypesEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type CreateDeviceTypeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateDeviceTypeRequest) Reset()                    { *m = CreateDeviceTypeRequest{} }
func (m *CreateDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceTypeRequest) ProtoMessage()               {}
func (*CreateDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *CreateDeviceTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDeviceTypeResponse struct {
	State      CreateDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateDeviceTypeResponse_State" json:"state,omitempty"`
	DeviceType *DeviceType                    `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *CreateDeviceTypeResponse) Reset()                    { *m = CreateDeviceTypeResponse{} }
func (m *CreateDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceTypeResponse) ProtoMessage()               {}
func (*CreateDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *CreateDeviceTypeResponse) GetState() CreateDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return CreateDeviceTypeResponse_SUCCESS
}

func (m *CreateDeviceTypeResponse) GetDeviceType() *DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type EditDeviceTypeRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EditDeviceTypeRequest) Reset()                    { *m = EditDeviceTypeRequest{} }
func (m *EditDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*EditDeviceTypeRequest) ProtoMessage()               {}
func (*EditDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *EditDeviceTypeRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *EditDeviceTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EditDeviceTypeResponse struct {
	State      EditDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditDeviceTypeResponse_State" json:"state,omitempty"`
	DeviceType *DeviceType                  `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *EditDeviceTypeResponse) Reset()                    { *m = EditDeviceTypeResponse{} }
func (m *EditDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*EditDeviceTypeResponse) ProtoMessage()               {}
func (*EditDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *EditDeviceTypeResponse) GetState() EditDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return EditDeviceTypeResponse_SUCCESS
}

func (m *EditDeviceTypeResponse) GetDeviceType() *DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type RemoveDeviceTypeRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
}

func (m *RemoveDeviceTypeRequest) Reset()                    { *m = RemoveDeviceTypeRequest{} }
func (m *RemoveDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeRequest) ProtoMessage()               {}
func (*RemoveDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *RemoveDeviceTypeRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

type RemoveDeviceTypeResponse struct {
	State RemoveDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveDeviceTypeResponse_State" json:"state,omitempty"`
}

func (m *RemoveDeviceTypeResponse) Reset()                    { *m = RemoveDeviceTypeResponse{} }
func (m *RemoveDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeResponse) ProtoMessage()               {}
func (*RemoveDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *RemoveDeviceTypeResponse) GetState() RemoveDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveDeviceTypeResponse_SUCCESS
}

type FetchDeviceTypesRequest struct {
	After  uint32 `protobuf:"varint,1,opt,name=after" json:"after,omitempty"`
	Before uint32 `protobuf:"varint,2,opt,name=before" json:"before,omitempty"`
	First  uint32 `protobuf:"varint,3,opt,name=first" json:"first,omitempty"`
	Last   uint32 `protobuf:"varint,4,opt,name=last" json:"last,omitempty"`
}

func (m *FetchDeviceTypesRequest) Reset()                    { *m = FetchDeviceTypesRequest{} }
func (m *FetchDeviceTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypesRequest) ProtoMessage()               {}
func (*FetchDeviceTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *FetchDeviceTypesRequest) GetAfter() uint32 {
	if m != nil {
		return m.After
	}
	return 0
}

func (m *FetchDeviceTypesRequest) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

func (m *FetchDeviceTypesRequest) GetFirst() uint32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *FetchDeviceTypesRequest) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type FetchDeviceTypeByIdRequest struct {
	DeviceTypesIdt []uint32 `protobuf:"varint,1,rep,packed,name=deviceTypesIdt" json:"deviceTypesIdt,omitempty"`
}

func (m *FetchDeviceTypeByIdRequest) Reset()                    { *m = FetchDeviceTypeByIdRequest{} }
func (m *FetchDeviceTypeByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypeByIdRequest) ProtoMessage()               {}
func (*FetchDeviceTypeByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *FetchDeviceTypeByIdRequest) GetDeviceTypesIdt() []uint32 {
	if m != nil {
		return m.DeviceTypesIdt
	}
	return nil
}

type FetchDeviceTypeByIdResponse struct {
	DeviceTypes []*DeviceType `protobuf:"bytes,1,rep,name=deviceTypes" json:"deviceTypes,omitempty"`
}

func (m *FetchDeviceTypeByIdResponse) Reset()                    { *m = FetchDeviceTypeByIdResponse{} }
func (m *FetchDeviceTypeByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypeByIdResponse) ProtoMessage()               {}
func (*FetchDeviceTypeByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *FetchDeviceTypeByIdResponse) GetDeviceTypes() []*DeviceType {
	if m != nil {
		return m.DeviceTypes
	}
	return nil
}

type CreateCommandRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value        string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *CreateCommandRequest) Reset()                    { *m = CreateCommandRequest{} }
func (m *CreateCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCommandRequest) ProtoMessage()               {}
func (*CreateCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *CreateCommandRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *CreateCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCommandRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateCommandResponse struct {
	State   CreateCommandResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateCommandResponse_State" json:"state,omitempty"`
	Command *Command                    `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *CreateCommandResponse) Reset()                    { *m = CreateCommandResponse{} }
func (m *CreateCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCommandResponse) ProtoMessage()               {}
func (*CreateCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *CreateCommandResponse) GetState() CreateCommandResponse_State {
	if m != nil {
		return m.State
	}
	return CreateCommandResponse_SUCCESS
}

func (m *CreateCommandResponse) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type EditCommandRequest struct {
	CommandId uint32 `protobuf:"varint,1,opt,name=commandId" json:"commandId,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value     string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *EditCommandRequest) Reset()                    { *m = EditCommandRequest{} }
func (m *EditCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*EditCommandRequest) ProtoMessage()               {}
func (*EditCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *EditCommandRequest) GetCommandId() uint32 {
	if m != nil {
		return m.CommandId
	}
	return 0
}

func (m *EditCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditCommandRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EditCommandReponse struct {
	State   EditCommandReponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditCommandReponse_State" json:"state,omitempty"`
	Command *Command                 `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *EditCommandReponse) Reset()                    { *m = EditCommandReponse{} }
func (m *EditCommandReponse) String() string            { return proto.CompactTextString(m) }
func (*EditCommandReponse) ProtoMessage()               {}
func (*EditCommandReponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *EditCommandReponse) GetState() EditCommandReponse_State {
	if m != nil {
		return m.State
	}
	return EditCommandReponse_SUCCESS
}

func (m *EditCommandReponse) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type RemoveCommandRequest struct {
	CommandId uint32 `protobuf:"varint,1,opt,name=commandId" json:"commandId,omitempty"`
}

func (m *RemoveCommandRequest) Reset()                    { *m = RemoveCommandRequest{} }
func (m *RemoveCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveCommandRequest) ProtoMessage()               {}
func (*RemoveCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *RemoveCommandRequest) GetCommandId() uint32 {
	if m != nil {
		return m.CommandId
	}
	return 0
}

type RemoveCommandResponse struct {
	State RemoveCommandResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveCommandResponse_State" json:"state,omitempty"`
}

func (m *RemoveCommandResponse) Reset()                    { *m = RemoveCommandResponse{} }
func (m *RemoveCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveCommandResponse) ProtoMessage()               {}
func (*RemoveCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{18} }

func (m *RemoveCommandResponse) GetState() RemoveCommandResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveCommandResponse_SUCCESS
}

type FetchCommandsByDeviceTypeIdRequest struct {
	DeviceTypeIdt []uint32 `protobuf:"varint,1,rep,packed,name=deviceTypeIdt" json:"deviceTypeIdt,omitempty"`
}

func (m *FetchCommandsByDeviceTypeIdRequest) Reset()         { *m = FetchCommandsByDeviceTypeIdRequest{} }
func (m *FetchCommandsByDeviceTypeIdRequest) String() string { return proto.CompactTextString(m) }
func (*FetchCommandsByDeviceTypeIdRequest) ProtoMessage()    {}
func (*FetchCommandsByDeviceTypeIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{19}
}

func (m *FetchCommandsByDeviceTypeIdRequest) GetDeviceTypeIdt() []uint32 {
	if m != nil {
		return m.DeviceTypeIdt
	}
	return nil
}

type DeviceTypeCommands struct {
	Commands     []*Command `protobuf:"bytes,1,rep,name=commands" json:"commands,omitempty"`
	DeviceTypeId uint32     `protobuf:"varint,2,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
}

func (m *DeviceTypeCommands) Reset()                    { *m = DeviceTypeCommands{} }
func (m *DeviceTypeCommands) String() string            { return proto.CompactTextString(m) }
func (*DeviceTypeCommands) ProtoMessage()               {}
func (*DeviceTypeCommands) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{20} }

func (m *DeviceTypeCommands) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *DeviceTypeCommands) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

type FetchCommandsByDeviceTypeIdResponse struct {
	DeviceTypeCommands []*DeviceTypeCommands `protobuf:"bytes,1,rep,name=deviceTypeCommands" json:"deviceTypeCommands,omitempty"`
}

func (m *FetchCommandsByDeviceTypeIdResponse) Reset()         { *m = FetchCommandsByDeviceTypeIdResponse{} }
func (m *FetchCommandsByDeviceTypeIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchCommandsByDeviceTypeIdResponse) ProtoMessage()    {}
func (*FetchCommandsByDeviceTypeIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{21}
}

func (m *FetchCommandsByDeviceTypeIdResponse) GetDeviceTypeCommands() []*DeviceTypeCommands {
	if m != nil {
		return m.DeviceTypeCommands
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceType)(nil), "WompattiService.DeviceType")
	proto.RegisterType((*Command)(nil), "WompattiService.Command")
	proto.RegisterType((*DeviceTypesConnection)(nil), "WompattiService.DeviceTypesConnection")
	proto.RegisterType((*DeviceTypesEdge)(nil), "WompattiService.DeviceTypesEdge")
	proto.RegisterType((*CreateDeviceTypeRequest)(nil), "WompattiService.CreateDeviceTypeRequest")
	proto.RegisterType((*CreateDeviceTypeResponse)(nil), "WompattiService.CreateDeviceTypeResponse")
	proto.RegisterType((*EditDeviceTypeRequest)(nil), "WompattiService.EditDeviceTypeRequest")
	proto.RegisterType((*EditDeviceTypeResponse)(nil), "WompattiService.EditDeviceTypeResponse")
	proto.RegisterType((*RemoveDeviceTypeRequest)(nil), "WompattiService.RemoveDeviceTypeRequest")
	proto.RegisterType((*RemoveDeviceTypeResponse)(nil), "WompattiService.RemoveDeviceTypeResponse")
	proto.RegisterType((*FetchDeviceTypesRequest)(nil), "WompattiService.FetchDeviceTypesRequest")
	proto.RegisterType((*FetchDeviceTypeByIdRequest)(nil), "WompattiService.FetchDeviceTypeByIdRequest")
	proto.RegisterType((*FetchDeviceTypeByIdResponse)(nil), "WompattiService.FetchDeviceTypeByIdResponse")
	proto.RegisterType((*CreateCommandRequest)(nil), "WompattiService.CreateCommandRequest")
	proto.RegisterType((*CreateCommandResponse)(nil), "WompattiService.CreateCommandResponse")
	proto.RegisterType((*EditCommandRequest)(nil), "WompattiService.EditCommandRequest")
	proto.RegisterType((*EditCommandReponse)(nil), "WompattiService.EditCommandReponse")
	proto.RegisterType((*RemoveCommandRequest)(nil), "WompattiService.RemoveCommandRequest")
	proto.RegisterType((*RemoveCommandResponse)(nil), "WompattiService.RemoveCommandResponse")
	proto.RegisterType((*FetchCommandsByDeviceTypeIdRequest)(nil), "WompattiService.FetchCommandsByDeviceTypeIdRequest")
	proto.RegisterType((*DeviceTypeCommands)(nil), "WompattiService.DeviceTypeCommands")
	proto.RegisterType((*FetchCommandsByDeviceTypeIdResponse)(nil), "WompattiService.FetchCommandsByDeviceTypeIdResponse")
	proto.RegisterEnum("WompattiService.CreateDeviceTypeResponse_State", CreateDeviceTypeResponse_State_name, CreateDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.EditDeviceTypeResponse_State", EditDeviceTypeResponse_State_name, EditDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveDeviceTypeResponse_State", RemoveDeviceTypeResponse_State_name, RemoveDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.CreateCommandResponse_State", CreateCommandResponse_State_name, CreateCommandResponse_State_value)
	proto.RegisterEnum("WompattiService.EditCommandReponse_State", EditCommandReponse_State_name, EditCommandReponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveCommandResponse_State", RemoveCommandResponse_State_name, RemoveCommandResponse_State_value)
}

func init() { proto.RegisterFile("device_type.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcf, 0x4f, 0x13, 0x41,
	0x18, 0x75, 0x0a, 0xe5, 0xc7, 0x57, 0x17, 0x70, 0xd2, 0xc2, 0x0a, 0xc6, 0x34, 0x83, 0x31, 0x35,
	0x91, 0x62, 0x2a, 0x7a, 0x31, 0xc4, 0x84, 0x6d, 0x49, 0xea, 0x01, 0xcc, 0x16, 0x62, 0x62, 0x48,
	0xc8, 0xd2, 0x99, 0xd6, 0x4d, 0xe8, 0x4e, 0xd9, 0x9d, 0x92, 0xd4, 0x93, 0x27, 0xff, 0x14, 0x8f,
	0x9e, 0xbc, 0x7b, 0xf0, 0x1f, 0x33, 0x3b, 0x3b, 0xdb, 0xfd, 0xd5, 0x96, 0xd2, 0x03, 0xb7, 0xce,
	0xf4, 0xbd, 0x37, 0xdf, 0xf7, 0xe6, 0x7b, 0x93, 0x85, 0x27, 0x94, 0xdd, 0xda, 0x6d, 0x76, 0x29,
	0x86, 0x7d, 0x56, 0xed, 0xbb, 0x5c, 0x70, 0xbc, 0xfe, 0x85, 0xf7, 0xfa, 0x96, 0x10, 0x76, 0x8b,
	0xb9, 0xfe, 0x7f, 0xdb, 0xeb, 0x7d, 0xab, 0xcb, 0x2e, 0x6d, 0xa7, 0xc3, 0x03, 0x04, 0x79, 0x03,
	0x50, 0x97, 0xb4, 0xb3, 0x61, 0x9f, 0xe1, 0x35, 0xc8, 0xd9, 0x54, 0x47, 0x65, 0x54, 0xd1, 0xcc,
	0x9c, 0x4d, 0x31, 0x86, 0x45, 0xc7, 0xea, 0x31, 0x3d, 0x57, 0x46, 0x95, 0x55, 0x53, 0xfe, 0x26,
	0x5d, 0x58, 0x36, 0x78, 0xaf, 0x67, 0x39, 0x34, 0x03, 0x27, 0xf0, 0x98, 0x8e, 0xc4, 0x9a, 0x54,
	0xd2, 0x34, 0x33, 0xb1, 0x37, 0x92, 0x5c, 0x88, 0x24, 0x71, 0x11, 0xf2, 0xb7, 0xd6, 0xf5, 0x80,
	0xe9, 0x8b, 0x72, 0x33, 0x58, 0x90, 0x5f, 0x08, 0x4a, 0x51, 0x6d, 0x9e, 0xc1, 0x1d, 0x87, 0xb5,
	0x85, 0xcd, 0x1d, 0xfc, 0x0e, 0x56, 0xfc, 0x3e, 0x9a, 0x4e, 0x87, 0xcb, 0xd3, 0x0b, 0xb5, 0xa7,
	0xd5, 0x54, 0xa7, 0xd5, 0xcf, 0x0a, 0x60, 0x8e, 0xa0, 0xf8, 0x3d, 0xe4, 0x19, 0xed, 0x32, 0x4f,
	0xcf, 0x95, 0x17, 0x2a, 0x85, 0x5a, 0x39, 0xc3, 0x89, 0x9d, 0xd6, 0xa0, 0x5d, 0x66, 0x06, 0x70,
	0xfc, 0x1c, 0x40, 0x70, 0x61, 0x5d, 0x1b, 0x7c, 0xe0, 0x08, 0x59, 0xb8, 0x66, 0xc6, 0x76, 0xc8,
	0x57, 0x58, 0x4f, 0x31, 0xf1, 0x3e, 0x2c, 0x3a, 0x9c, 0x32, 0x55, 0xdd, 0xce, 0x94, 0x93, 0x4c,
	0x09, 0xc4, 0x9b, 0xb0, 0xd4, 0x1e, 0xb8, 0x1e, 0x77, 0x95, 0x69, 0x6a, 0x45, 0xf6, 0x60, 0xcb,
	0x70, 0x99, 0x25, 0x58, 0x8c, 0xc1, 0x6e, 0x06, 0xcc, 0x13, 0x23, 0x27, 0x51, 0xec, 0x72, 0xfe,
	0x21, 0xd0, 0xb3, 0x78, 0xaf, 0xcf, 0x1d, 0x8f, 0xe1, 0x06, 0xe4, 0x3d, 0x61, 0x89, 0x80, 0xb1,
	0x56, 0xdb, 0xcf, 0x54, 0x35, 0x89, 0x59, 0x6d, 0xf9, 0x34, 0x33, 0x60, 0xe3, 0x0f, 0x00, 0xd1,
	0x8d, 0xca, 0x72, 0xef, 0xe8, 0x30, 0x06, 0x27, 0xbb, 0x90, 0x97, 0x62, 0xb8, 0x00, 0xcb, 0xad,
	0x73, 0xc3, 0x68, 0xb4, 0x5a, 0x1b, 0x8f, 0xb0, 0x06, 0xab, 0x27, 0xa7, 0x67, 0x97, 0xc7, 0xa7,
	0xe7, 0x27, 0xf5, 0x0d, 0x44, 0x4e, 0xa1, 0xd4, 0xa0, 0xb6, 0xc8, 0xb6, 0x9c, 0x1e, 0x30, 0x34,
	0x65, 0xc0, 0xe2, 0x33, 0xfb, 0x17, 0xc1, 0x66, 0x5a, 0x51, 0x99, 0x62, 0x24, 0x4d, 0xd9, 0xcb,
	0x34, 0x32, 0x9e, 0xf7, 0xd0, 0x96, 0x1c, 0xc2, 0x96, 0xc9, 0x7a, 0xfc, 0x96, 0xcd, 0x65, 0x0a,
	0xf9, 0x89, 0x40, 0xcf, 0xf2, 0x67, 0x9d, 0x8b, 0x49, 0xcc, 0x84, 0x09, 0xb3, 0xf5, 0x71, 0x03,
	0x5b, 0xc7, 0x4c, 0xb4, 0xbf, 0xc5, 0x02, 0x13, 0xf6, 0x51, 0x84, 0xbc, 0xd5, 0x11, 0xcc, 0x55,
	0x0d, 0x04, 0x0b, 0x3f, 0x18, 0x57, 0xac, 0xc3, 0x5d, 0x16, 0x06, 0x23, 0x58, 0xf9, 0xe8, 0x8e,
	0xed, 0x7a, 0x61, 0x1e, 0x83, 0x85, 0x7f, 0xf9, 0xd7, 0x96, 0x27, 0xe4, 0x43, 0xa2, 0x99, 0xf2,
	0x37, 0xa9, 0xc3, 0x76, 0xea, 0xc8, 0xa3, 0x61, 0x93, 0x86, 0xa7, 0xbe, 0x84, 0xb5, 0xc8, 0x29,
	0xaf, 0x49, 0x85, 0x8e, 0xca, 0x0b, 0x15, 0xcd, 0x4c, 0xed, 0x92, 0x0b, 0xd8, 0x19, 0xab, 0xa2,
	0x3c, 0x3c, 0x84, 0x42, 0x8c, 0x20, 0x35, 0xee, 0x18, 0x81, 0x38, 0x9e, 0x50, 0x28, 0x06, 0xe1,
	0x53, 0x4f, 0xeb, 0x3c, 0x03, 0x7f, 0xf7, 0x8b, 0xfa, 0x07, 0x41, 0x29, 0x75, 0x8c, 0x2a, 0xff,
	0x28, 0x39, 0x02, 0xaf, 0x27, 0x3c, 0x0d, 0x29, 0x5a, 0x32, 0x04, 0x35, 0x58, 0x6e, 0x07, 0xff,
	0xab, 0x04, 0xe8, 0x59, 0x15, 0xc5, 0x0f, 0x81, 0xb3, 0xcd, 0xcc, 0x05, 0x60, 0x3f, 0x84, 0x29,
	0x6b, 0x9e, 0xc1, 0xaa, 0x52, 0x19, 0xf9, 0x12, 0x6d, 0xdc, 0xc3, 0x94, 0xdf, 0x28, 0x25, 0x1f,
	0x38, 0xf2, 0x31, 0xe9, 0xc8, 0xab, 0xb1, 0xef, 0x42, 0x92, 0xf3, 0x40, 0x76, 0x1c, 0x40, 0x31,
	0x08, 0xe4, 0x7d, 0x0c, 0x21, 0x3f, 0x10, 0x94, 0x52, 0xb4, 0x59, 0xef, 0x7e, 0x2c, 0x6d, 0x8e,
	0xec, 0x7f, 0x02, 0x22, 0x23, 0xa4, 0x94, 0xbc, 0xa3, 0x61, 0x3d, 0x36, 0xc7, 0x61, 0x1b, 0x2f,
	0x40, 0x8b, 0x8f, 0x77, 0x98, 0xc7, 0xe4, 0x26, 0x71, 0x00, 0x47, 0xe4, 0x50, 0x10, 0x1f, 0xc0,
	0x8a, 0xea, 0x38, 0x8c, 0xe0, 0x64, 0xd3, 0x47, 0xc8, 0x59, 0x3e, 0x5b, 0xc8, 0x77, 0xd8, 0x9d,
	0x5a, 0xbb, 0xf2, 0xb2, 0x05, 0x98, 0x66, 0xca, 0x52, 0xa5, 0xec, 0x4e, 0x79, 0x0d, 0x42, 0xa8,
	0x39, 0x86, 0x7e, 0xb5, 0x24, 0x3f, 0xd5, 0xde, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xce, 0xa4,
	0x5f, 0xfc, 0xe1, 0x09, 0x00, 0x00,
}
