// Code generated by protoc-gen-go.
// source: device_type.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateDeviceTypeResponse_State int32

const (
	CreateDeviceTypeResponse_SUCCESS   CreateDeviceTypeResponse_State = 0
	CreateDeviceTypeResponse_NOT_FOUND CreateDeviceTypeResponse_State = 1
)

var CreateDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateDeviceTypeResponse_State) String() string {
	return proto.EnumName(CreateDeviceTypeResponse_State_name, int32(x))
}
func (CreateDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{6, 0}
}

type EditDeviceTypeResponse_State int32

const (
	EditDeviceTypeResponse_SUCCESS   EditDeviceTypeResponse_State = 0
	EditDeviceTypeResponse_NOT_FOUND EditDeviceTypeResponse_State = 1
)

var EditDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditDeviceTypeResponse_State) String() string {
	return proto.EnumName(EditDeviceTypeResponse_State_name, int32(x))
}
func (EditDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{8, 0}
}

type RemoveDeviceTypeResponse_State int32

const (
	RemoveDeviceTypeResponse_SUCCESS   RemoveDeviceTypeResponse_State = 0
	RemoveDeviceTypeResponse_NOT_FOUND RemoveDeviceTypeResponse_State = 1
)

var RemoveDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveDeviceTypeResponse_State) String() string {
	return proto.EnumName(RemoveDeviceTypeResponse_State_name, int32(x))
}
func (RemoveDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{10, 0}
}

type DeviceType struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DeviceType) Reset()                    { *m = DeviceType{} }
func (m *DeviceType) String() string            { return proto.CompactTextString(m) }
func (*DeviceType) ProtoMessage()               {}
func (*DeviceType) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *DeviceType) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeviceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FetchDeviceTypesRequest struct {
}

func (m *FetchDeviceTypesRequest) Reset()                    { *m = FetchDeviceTypesRequest{} }
func (m *FetchDeviceTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypesRequest) ProtoMessage()               {}
func (*FetchDeviceTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type FetchDeviceTypesResponse struct {
}

func (m *FetchDeviceTypesResponse) Reset()                    { *m = FetchDeviceTypesResponse{} }
func (m *FetchDeviceTypesResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypesResponse) ProtoMessage()               {}
func (*FetchDeviceTypesResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

type FetchDeviceTypeByIdRequest struct {
	DeviceTypesIdt []uint32 `protobuf:"varint,1,rep,packed,name=deviceTypesIdt" json:"deviceTypesIdt,omitempty"`
}

func (m *FetchDeviceTypeByIdRequest) Reset()                    { *m = FetchDeviceTypeByIdRequest{} }
func (m *FetchDeviceTypeByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypeByIdRequest) ProtoMessage()               {}
func (*FetchDeviceTypeByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *FetchDeviceTypeByIdRequest) GetDeviceTypesIdt() []uint32 {
	if m != nil {
		return m.DeviceTypesIdt
	}
	return nil
}

type FetchDeviceTypeByIdResponse struct {
	DeviceTypes []*DeviceType `protobuf:"bytes,1,rep,name=deviceTypes" json:"deviceTypes,omitempty"`
}

func (m *FetchDeviceTypeByIdResponse) Reset()                    { *m = FetchDeviceTypeByIdResponse{} }
func (m *FetchDeviceTypeByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypeByIdResponse) ProtoMessage()               {}
func (*FetchDeviceTypeByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *FetchDeviceTypeByIdResponse) GetDeviceTypes() []*DeviceType {
	if m != nil {
		return m.DeviceTypes
	}
	return nil
}

type CreateDeviceTypeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateDeviceTypeRequest) Reset()                    { *m = CreateDeviceTypeRequest{} }
func (m *CreateDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceTypeRequest) ProtoMessage()               {}
func (*CreateDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *CreateDeviceTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDeviceTypeResponse struct {
	State      CreateDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateDeviceTypeResponse_State" json:"state,omitempty"`
	DeviceType *DeviceType                    `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *CreateDeviceTypeResponse) Reset()                    { *m = CreateDeviceTypeResponse{} }
func (m *CreateDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceTypeResponse) ProtoMessage()               {}
func (*CreateDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *CreateDeviceTypeResponse) GetState() CreateDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return CreateDeviceTypeResponse_SUCCESS
}

func (m *CreateDeviceTypeResponse) GetDeviceType() *DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type EditDeviceTypeRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EditDeviceTypeRequest) Reset()                    { *m = EditDeviceTypeRequest{} }
func (m *EditDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*EditDeviceTypeRequest) ProtoMessage()               {}
func (*EditDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *EditDeviceTypeRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *EditDeviceTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EditDeviceTypeResponse struct {
	State      EditDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditDeviceTypeResponse_State" json:"state,omitempty"`
	DeviceType *DeviceType                  `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *EditDeviceTypeResponse) Reset()                    { *m = EditDeviceTypeResponse{} }
func (m *EditDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*EditDeviceTypeResponse) ProtoMessage()               {}
func (*EditDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *EditDeviceTypeResponse) GetState() EditDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return EditDeviceTypeResponse_SUCCESS
}

func (m *EditDeviceTypeResponse) GetDeviceType() *DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type RemoveDeviceTypeRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
}

func (m *RemoveDeviceTypeRequest) Reset()                    { *m = RemoveDeviceTypeRequest{} }
func (m *RemoveDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeRequest) ProtoMessage()               {}
func (*RemoveDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *RemoveDeviceTypeRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

type RemoveDeviceTypeResponse struct {
	State RemoveDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveDeviceTypeResponse_State" json:"state,omitempty"`
}

func (m *RemoveDeviceTypeResponse) Reset()                    { *m = RemoveDeviceTypeResponse{} }
func (m *RemoveDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeResponse) ProtoMessage()               {}
func (*RemoveDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *RemoveDeviceTypeResponse) GetState() RemoveDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveDeviceTypeResponse_SUCCESS
}

func init() {
	proto.RegisterType((*DeviceType)(nil), "WompattiService.DeviceType")
	proto.RegisterType((*FetchDeviceTypesRequest)(nil), "WompattiService.FetchDeviceTypesRequest")
	proto.RegisterType((*FetchDeviceTypesResponse)(nil), "WompattiService.FetchDeviceTypesResponse")
	proto.RegisterType((*FetchDeviceTypeByIdRequest)(nil), "WompattiService.FetchDeviceTypeByIdRequest")
	proto.RegisterType((*FetchDeviceTypeByIdResponse)(nil), "WompattiService.FetchDeviceTypeByIdResponse")
	proto.RegisterType((*CreateDeviceTypeRequest)(nil), "WompattiService.CreateDeviceTypeRequest")
	proto.RegisterType((*CreateDeviceTypeResponse)(nil), "WompattiService.CreateDeviceTypeResponse")
	proto.RegisterType((*EditDeviceTypeRequest)(nil), "WompattiService.EditDeviceTypeRequest")
	proto.RegisterType((*EditDeviceTypeResponse)(nil), "WompattiService.EditDeviceTypeResponse")
	proto.RegisterType((*RemoveDeviceTypeRequest)(nil), "WompattiService.RemoveDeviceTypeRequest")
	proto.RegisterType((*RemoveDeviceTypeResponse)(nil), "WompattiService.RemoveDeviceTypeResponse")
	proto.RegisterEnum("WompattiService.CreateDeviceTypeResponse_State", CreateDeviceTypeResponse_State_name, CreateDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.EditDeviceTypeResponse_State", EditDeviceTypeResponse_State_name, EditDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveDeviceTypeResponse_State", RemoveDeviceTypeResponse_State_name, RemoveDeviceTypeResponse_State_value)
}

func init() { proto.RegisterFile("device_type.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x5d, 0x14, 0x0d, 0x83, 0xfc, 0x71, 0x13, 0xa5, 0xc2, 0x85, 0xac, 0x89, 0xe1, 0x42,
	0x35, 0x78, 0x34, 0x5c, 0x2c, 0x90, 0x70, 0x81, 0x64, 0x0b, 0xf1, 0x62, 0x42, 0x2a, 0x3b, 0x6a,
	0x0f, 0xd0, 0x4a, 0x57, 0x12, 0x5e, 0xc0, 0xd7, 0xf2, 0xe0, 0x8b, 0x19, 0xda, 0x92, 0x96, 0x6e,
	0x89, 0xc4, 0x83, 0xb7, 0x66, 0xe6, 0xfb, 0x7d, 0x9d, 0xf9, 0x3a, 0x85, 0x33, 0x81, 0x4b, 0x7b,
	0x8a, 0x13, 0xb9, 0x72, 0x51, 0x77, 0x17, 0x8e, 0x74, 0x68, 0xe9, 0xd1, 0x99, 0xb9, 0x96, 0x94,
	0xb6, 0x89, 0x8b, 0x75, 0xaf, 0x5a, 0x72, 0xad, 0x57, 0x9c, 0xd8, 0xf3, 0x17, 0x27, 0x50, 0xb0,
	0x5b, 0x80, 0x8e, 0x8f, 0x8d, 0x56, 0x2e, 0xd2, 0x22, 0x64, 0x6c, 0xa1, 0x91, 0x3a, 0x69, 0x14,
	0x78, 0xc6, 0x16, 0x94, 0xc2, 0xd1, 0xdc, 0x9a, 0xa1, 0x96, 0xa9, 0x93, 0x46, 0x8e, 0xfb, 0xcf,
	0xec, 0x12, 0x2a, 0x3d, 0x94, 0xd3, 0xb7, 0x08, 0xf3, 0x38, 0xbe, 0x7f, 0xa0, 0x27, 0x59, 0x15,
	0x34, 0xb5, 0xe5, 0xb9, 0xce, 0xdc, 0x43, 0xd6, 0x81, 0x6a, 0xa2, 0xf7, 0xb0, 0xea, 0x8b, 0x90,
	0xa4, 0xd7, 0x50, 0x14, 0x11, 0xd4, 0x17, 0x52, 0x23, 0xf5, 0xc3, 0x46, 0x81, 0x27, 0xaa, 0xec,
	0x09, 0x6a, 0xa9, 0x2e, 0xc1, 0x4b, 0x68, 0x1b, 0xf2, 0x31, 0xc0, 0xf7, 0xc8, 0xb7, 0x6a, 0x7a,
	0x22, 0x05, 0x3d, 0xa2, 0x79, 0x5c, 0xcf, 0x9a, 0x50, 0x31, 0x16, 0x68, 0x49, 0x8c, 0x09, 0xc2,
	0x01, 0x37, 0x49, 0x90, 0x58, 0x12, 0xdf, 0x04, 0x34, 0x55, 0x1f, 0x8e, 0xd2, 0x85, 0xac, 0x27,
	0x2d, 0x19, 0x10, 0xc5, 0xd6, 0x8d, 0x32, 0xc4, 0x2e, 0x52, 0x37, 0xd7, 0x18, 0x0f, 0x68, 0x7a,
	0x0f, 0x10, 0x4d, 0xe8, 0x7f, 0x87, 0x5f, 0x16, 0x8a, 0xc9, 0xd9, 0x15, 0x64, 0x7d, 0x33, 0x9a,
	0x87, 0x13, 0x73, 0x6c, 0x18, 0x5d, 0xd3, 0x2c, 0x1f, 0xd0, 0x02, 0xe4, 0x06, 0xc3, 0xd1, 0xa4,
	0x37, 0x1c, 0x0f, 0x3a, 0x65, 0xc2, 0x86, 0x70, 0xde, 0x15, 0xb6, 0x54, 0x57, 0x66, 0x70, 0x1a,
	0x79, 0xf5, 0x37, 0x67, 0xb1, 0x55, 0x4b, 0x3d, 0x90, 0x2f, 0x02, 0x17, 0x49, 0xc7, 0x30, 0x14,
	0x63, 0x3b, 0x94, 0xa6, 0xb2, 0x48, 0x3a, 0xf7, 0xdf, 0x91, 0xb4, 0xa1, 0xc2, 0x71, 0xe6, 0x2c,
	0xf1, 0x4f, 0xa1, 0xb0, 0x4f, 0x02, 0x9a, 0xca, 0xef, 0x7b, 0x17, 0xbb, 0xc8, 0xad, 0x10, 0xf6,
	0xda, 0xe3, 0xf9, 0xd8, 0xff, 0xc7, 0xef, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x05, 0x3f,
	0x30, 0x1a, 0x04, 0x00, 0x00,
}
