// Code generated by protoc-gen-go.
// source: device_type.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateDeviceTypeResponse_State int32

const (
	CreateDeviceTypeResponse_SUCCESS   CreateDeviceTypeResponse_State = 0
	CreateDeviceTypeResponse_NOT_FOUND CreateDeviceTypeResponse_State = 1
)

var CreateDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateDeviceTypeResponse_State) String() string {
	return proto.EnumName(CreateDeviceTypeResponse_State_name, int32(x))
}
func (CreateDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{3, 0}
}

type EditDeviceTypeResponse_State int32

const (
	EditDeviceTypeResponse_SUCCESS   EditDeviceTypeResponse_State = 0
	EditDeviceTypeResponse_NOT_FOUND EditDeviceTypeResponse_State = 1
)

var EditDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditDeviceTypeResponse_State) String() string {
	return proto.EnumName(EditDeviceTypeResponse_State_name, int32(x))
}
func (EditDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{5, 0}
}

type RemoveDeviceTypeResponse_State int32

const (
	RemoveDeviceTypeResponse_SUCCESS   RemoveDeviceTypeResponse_State = 0
	RemoveDeviceTypeResponse_NOT_FOUND RemoveDeviceTypeResponse_State = 1
)

var RemoveDeviceTypeResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveDeviceTypeResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveDeviceTypeResponse_State) String() string {
	return proto.EnumName(RemoveDeviceTypeResponse_State_name, int32(x))
}
func (RemoveDeviceTypeResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{7, 0}
}

type CreateCommandResponse_State int32

const (
	CreateCommandResponse_SUCCESS   CreateCommandResponse_State = 0
	CreateCommandResponse_NOT_FOUND CreateCommandResponse_State = 1
)

var CreateCommandResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateCommandResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateCommandResponse_State) String() string {
	return proto.EnumName(CreateCommandResponse_State_name, int32(x))
}
func (CreateCommandResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{12, 0}
}

type EditCommandReponse_State int32

const (
	EditCommandReponse_SUCCESS   EditCommandReponse_State = 0
	EditCommandReponse_NOT_FOUND EditCommandReponse_State = 1
)

var EditCommandReponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditCommandReponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditCommandReponse_State) String() string {
	return proto.EnumName(EditCommandReponse_State_name, int32(x))
}
func (EditCommandReponse_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{14, 0} }

type RemoveCommandResponse_State int32

const (
	RemoveCommandResponse_SUCCESS   RemoveCommandResponse_State = 0
	RemoveCommandResponse_NOT_FOUND RemoveCommandResponse_State = 1
)

var RemoveCommandResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveCommandResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveCommandResponse_State) String() string {
	return proto.EnumName(RemoveCommandResponse_State_name, int32(x))
}
func (RemoveCommandResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{16, 0}
}

type DeviceType struct {
	Id                uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	SerialInterfaceId uint32 `protobuf:"varint,3,opt,name=serialInterfaceId" json:"serialInterfaceId,omitempty"`
	TelnetInterfaceId uint32 `protobuf:"varint,4,opt,name=telnetInterfaceId" json:"telnetInterfaceId,omitempty"`
	CecInterfaceId    uint32 `protobuf:"varint,5,opt,name=cecInterfaceId" json:"cecInterfaceId,omitempty"`
}

func (m *DeviceType) Reset()                    { *m = DeviceType{} }
func (m *DeviceType) String() string            { return proto.CompactTextString(m) }
func (*DeviceType) ProtoMessage()               {}
func (*DeviceType) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *DeviceType) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeviceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceType) GetSerialInterfaceId() uint32 {
	if m != nil {
		return m.SerialInterfaceId
	}
	return 0
}

func (m *DeviceType) GetTelnetInterfaceId() uint32 {
	if m != nil {
		return m.TelnetInterfaceId
	}
	return 0
}

func (m *DeviceType) GetCecInterfaceId() uint32 {
	if m != nil {
		return m.CecInterfaceId
	}
	return 0
}

type Command struct {
	Id           uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DeviceTypeId uint32 `protobuf:"varint,2,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value        string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Command) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Command) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateDeviceTypeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateDeviceTypeRequest) Reset()                    { *m = CreateDeviceTypeRequest{} }
func (m *CreateDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceTypeRequest) ProtoMessage()               {}
func (*CreateDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *CreateDeviceTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDeviceTypeResponse struct {
	State      CreateDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateDeviceTypeResponse_State" json:"state,omitempty"`
	DeviceType *DeviceType                    `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *CreateDeviceTypeResponse) Reset()                    { *m = CreateDeviceTypeResponse{} }
func (m *CreateDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceTypeResponse) ProtoMessage()               {}
func (*CreateDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *CreateDeviceTypeResponse) GetState() CreateDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return CreateDeviceTypeResponse_SUCCESS
}

func (m *CreateDeviceTypeResponse) GetDeviceType() *DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type EditDeviceTypeRequest struct {
	DeviceTypeId      uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	SerialInterfaceId uint32 `protobuf:"varint,3,opt,name=serialInterfaceId" json:"serialInterfaceId,omitempty"`
	TelnetInterfaceId uint32 `protobuf:"varint,4,opt,name=telnetInterfaceId" json:"telnetInterfaceId,omitempty"`
	CecInterfaceId    uint32 `protobuf:"varint,5,opt,name=cecInterfaceId" json:"cecInterfaceId,omitempty"`
}

func (m *EditDeviceTypeRequest) Reset()                    { *m = EditDeviceTypeRequest{} }
func (m *EditDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*EditDeviceTypeRequest) ProtoMessage()               {}
func (*EditDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *EditDeviceTypeRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *EditDeviceTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditDeviceTypeRequest) GetSerialInterfaceId() uint32 {
	if m != nil {
		return m.SerialInterfaceId
	}
	return 0
}

func (m *EditDeviceTypeRequest) GetTelnetInterfaceId() uint32 {
	if m != nil {
		return m.TelnetInterfaceId
	}
	return 0
}

func (m *EditDeviceTypeRequest) GetCecInterfaceId() uint32 {
	if m != nil {
		return m.CecInterfaceId
	}
	return 0
}

type EditDeviceTypeResponse struct {
	State      EditDeviceTypeResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditDeviceTypeResponse_State" json:"state,omitempty"`
	DeviceType *DeviceType                  `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *EditDeviceTypeResponse) Reset()                    { *m = EditDeviceTypeResponse{} }
func (m *EditDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*EditDeviceTypeResponse) ProtoMessage()               {}
func (*EditDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *EditDeviceTypeResponse) GetState() EditDeviceTypeResponse_State {
	if m != nil {
		return m.State
	}
	return EditDeviceTypeResponse_SUCCESS
}

func (m *EditDeviceTypeResponse) GetDeviceType() *DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type RemoveDeviceTypeRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
}

func (m *RemoveDeviceTypeRequest) Reset()                    { *m = RemoveDeviceTypeRequest{} }
func (m *RemoveDeviceTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeRequest) ProtoMessage()               {}
func (*RemoveDeviceTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *RemoveDeviceTypeRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

type RemoveDeviceTypeResponse struct {
}

func (m *RemoveDeviceTypeResponse) Reset()                    { *m = RemoveDeviceTypeResponse{} }
func (m *RemoveDeviceTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeResponse) ProtoMessage()               {}
func (*RemoveDeviceTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

type FetchDeviceTypesRequest struct {
	Offset uint32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *FetchDeviceTypesRequest) Reset()                    { *m = FetchDeviceTypesRequest{} }
func (m *FetchDeviceTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypesRequest) ProtoMessage()               {}
func (*FetchDeviceTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *FetchDeviceTypesRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FetchDeviceTypesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type FetchDeviceTypeByIdRequest struct {
	DeviceTypesIdt []uint32 `protobuf:"varint,1,rep,packed,name=deviceTypesIdt" json:"deviceTypesIdt,omitempty"`
}

func (m *FetchDeviceTypeByIdRequest) Reset()                    { *m = FetchDeviceTypeByIdRequest{} }
func (m *FetchDeviceTypeByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypeByIdRequest) ProtoMessage()               {}
func (*FetchDeviceTypeByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *FetchDeviceTypeByIdRequest) GetDeviceTypesIdt() []uint32 {
	if m != nil {
		return m.DeviceTypesIdt
	}
	return nil
}

type FetchDeviceTypeByIdResponse struct {
}

func (m *FetchDeviceTypeByIdResponse) Reset()                    { *m = FetchDeviceTypeByIdResponse{} }
func (m *FetchDeviceTypeByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchDeviceTypeByIdResponse) ProtoMessage()               {}
func (*FetchDeviceTypeByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

type CreateCommandRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value        string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *CreateCommandRequest) Reset()                    { *m = CreateCommandRequest{} }
func (m *CreateCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCommandRequest) ProtoMessage()               {}
func (*CreateCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *CreateCommandRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *CreateCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCommandRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateCommandResponse struct {
	State   CreateCommandResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateCommandResponse_State" json:"state,omitempty"`
	Command *Command                    `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *CreateCommandResponse) Reset()                    { *m = CreateCommandResponse{} }
func (m *CreateCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCommandResponse) ProtoMessage()               {}
func (*CreateCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *CreateCommandResponse) GetState() CreateCommandResponse_State {
	if m != nil {
		return m.State
	}
	return CreateCommandResponse_SUCCESS
}

func (m *CreateCommandResponse) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type EditCommandRequest struct {
	CommandId uint32 `protobuf:"varint,1,opt,name=commandId" json:"commandId,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value     string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *EditCommandRequest) Reset()                    { *m = EditCommandRequest{} }
func (m *EditCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*EditCommandRequest) ProtoMessage()               {}
func (*EditCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *EditCommandRequest) GetCommandId() uint32 {
	if m != nil {
		return m.CommandId
	}
	return 0
}

func (m *EditCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditCommandRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EditCommandReponse struct {
	State   EditCommandReponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditCommandReponse_State" json:"state,omitempty"`
	Command *Command                 `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *EditCommandReponse) Reset()                    { *m = EditCommandReponse{} }
func (m *EditCommandReponse) String() string            { return proto.CompactTextString(m) }
func (*EditCommandReponse) ProtoMessage()               {}
func (*EditCommandReponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *EditCommandReponse) GetState() EditCommandReponse_State {
	if m != nil {
		return m.State
	}
	return EditCommandReponse_SUCCESS
}

func (m *EditCommandReponse) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type RemoveCommandRequest struct {
	CommandId uint32 `protobuf:"varint,1,opt,name=commandId" json:"commandId,omitempty"`
}

func (m *RemoveCommandRequest) Reset()                    { *m = RemoveCommandRequest{} }
func (m *RemoveCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveCommandRequest) ProtoMessage()               {}
func (*RemoveCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *RemoveCommandRequest) GetCommandId() uint32 {
	if m != nil {
		return m.CommandId
	}
	return 0
}

type RemoveCommandResponse struct {
	State RemoveCommandResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveCommandResponse_State" json:"state,omitempty"`
}

func (m *RemoveCommandResponse) Reset()                    { *m = RemoveCommandResponse{} }
func (m *RemoveCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveCommandResponse) ProtoMessage()               {}
func (*RemoveCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *RemoveCommandResponse) GetState() RemoveCommandResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveCommandResponse_SUCCESS
}

type FetchCommandsByDeviceTypeIdRequest struct {
	DeviceTypeId uint32 `protobuf:"varint,1,opt,name=deviceTypeId" json:"deviceTypeId,omitempty"`
}

func (m *FetchCommandsByDeviceTypeIdRequest) Reset()         { *m = FetchCommandsByDeviceTypeIdRequest{} }
func (m *FetchCommandsByDeviceTypeIdRequest) String() string { return proto.CompactTextString(m) }
func (*FetchCommandsByDeviceTypeIdRequest) ProtoMessage()    {}
func (*FetchCommandsByDeviceTypeIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{17}
}

func (m *FetchCommandsByDeviceTypeIdRequest) GetDeviceTypeId() uint32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

type FetchCommandsByDeviceTypeIdResponse struct {
}

func (m *FetchCommandsByDeviceTypeIdResponse) Reset()         { *m = FetchCommandsByDeviceTypeIdResponse{} }
func (m *FetchCommandsByDeviceTypeIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchCommandsByDeviceTypeIdResponse) ProtoMessage()    {}
func (*FetchCommandsByDeviceTypeIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{18}
}

func init() {
	proto.RegisterType((*DeviceType)(nil), "WompattiService.DeviceType")
	proto.RegisterType((*Command)(nil), "WompattiService.Command")
	proto.RegisterType((*CreateDeviceTypeRequest)(nil), "WompattiService.CreateDeviceTypeRequest")
	proto.RegisterType((*CreateDeviceTypeResponse)(nil), "WompattiService.CreateDeviceTypeResponse")
	proto.RegisterType((*EditDeviceTypeRequest)(nil), "WompattiService.EditDeviceTypeRequest")
	proto.RegisterType((*EditDeviceTypeResponse)(nil), "WompattiService.EditDeviceTypeResponse")
	proto.RegisterType((*RemoveDeviceTypeRequest)(nil), "WompattiService.RemoveDeviceTypeRequest")
	proto.RegisterType((*RemoveDeviceTypeResponse)(nil), "WompattiService.RemoveDeviceTypeResponse")
	proto.RegisterType((*FetchDeviceTypesRequest)(nil), "WompattiService.FetchDeviceTypesRequest")
	proto.RegisterType((*FetchDeviceTypeByIdRequest)(nil), "WompattiService.FetchDeviceTypeByIdRequest")
	proto.RegisterType((*FetchDeviceTypeByIdResponse)(nil), "WompattiService.FetchDeviceTypeByIdResponse")
	proto.RegisterType((*CreateCommandRequest)(nil), "WompattiService.CreateCommandRequest")
	proto.RegisterType((*CreateCommandResponse)(nil), "WompattiService.CreateCommandResponse")
	proto.RegisterType((*EditCommandRequest)(nil), "WompattiService.EditCommandRequest")
	proto.RegisterType((*EditCommandReponse)(nil), "WompattiService.EditCommandReponse")
	proto.RegisterType((*RemoveCommandRequest)(nil), "WompattiService.RemoveCommandRequest")
	proto.RegisterType((*RemoveCommandResponse)(nil), "WompattiService.RemoveCommandResponse")
	proto.RegisterType((*FetchCommandsByDeviceTypeIdRequest)(nil), "WompattiService.FetchCommandsByDeviceTypeIdRequest")
	proto.RegisterType((*FetchCommandsByDeviceTypeIdResponse)(nil), "WompattiService.FetchCommandsByDeviceTypeIdResponse")
	proto.RegisterEnum("WompattiService.CreateDeviceTypeResponse_State", CreateDeviceTypeResponse_State_name, CreateDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.EditDeviceTypeResponse_State", EditDeviceTypeResponse_State_name, EditDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveDeviceTypeResponse_State", RemoveDeviceTypeResponse_State_name, RemoveDeviceTypeResponse_State_value)
	proto.RegisterEnum("WompattiService.CreateCommandResponse_State", CreateCommandResponse_State_name, CreateCommandResponse_State_value)
	proto.RegisterEnum("WompattiService.EditCommandReponse_State", EditCommandReponse_State_name, EditCommandReponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveCommandResponse_State", RemoveCommandResponse_State_name, RemoveCommandResponse_State_value)
}

func init() { proto.RegisterFile("device_type.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0xfd, 0xad, 0x1d, 0xc7, 0x78, 0xf2, 0xb3, 0x9b, 0x2c, 0x76, 0x2c, 0x9a, 0x16, 0xc2, 0x86,
	0x86, 0x14, 0x12, 0x17, 0xdc, 0xde, 0x4a, 0x09, 0xf8, 0x4f, 0x5a, 0x5f, 0x12, 0x90, 0x13, 0x7a,
	0x29, 0x04, 0x55, 0x3b, 0x6e, 0x05, 0x96, 0xe5, 0x5a, 0x1b, 0x83, 0x6f, 0xfd, 0x44, 0x3d, 0xe5,
	0xde, 0x43, 0x3f, 0x42, 0xbf, 0x50, 0xd1, 0xee, 0xda, 0x92, 0x56, 0x4e, 0x6a, 0xe7, 0x10, 0x7a,
	0xd3, 0xee, 0xce, 0x7b, 0x3b, 0xef, 0xcd, 0xcc, 0x22, 0xd8, 0xe1, 0x38, 0xf5, 0x5c, 0xbc, 0x16,
	0xb3, 0x31, 0x36, 0xc6, 0x93, 0x40, 0x04, 0xf4, 0xc9, 0xc7, 0xc0, 0x1f, 0x3b, 0x42, 0x78, 0x7d,
	0x9c, 0x44, 0x67, 0xec, 0x96, 0x00, 0x74, 0x64, 0xd8, 0xe5, 0x6c, 0x8c, 0xb4, 0x02, 0x39, 0x8f,
	0x5b, 0x64, 0x9f, 0x1c, 0x95, 0xed, 0x9c, 0xc7, 0x29, 0x85, 0x8d, 0x91, 0xe3, 0xa3, 0x95, 0xdb,
	0x27, 0x47, 0x25, 0x5b, 0x7e, 0xd3, 0x63, 0xd8, 0x09, 0x71, 0xe2, 0x39, 0xc3, 0xde, 0x48, 0xe0,
	0x64, 0xe0, 0xb8, 0xd8, 0xe3, 0x56, 0x5e, 0x42, 0xb2, 0x07, 0x51, 0xb4, 0xc0, 0xe1, 0x08, 0x45,
	0x32, 0x7a, 0x43, 0x45, 0x67, 0x0e, 0xe8, 0x21, 0x54, 0x5c, 0x74, 0x93, 0xa1, 0x05, 0x19, 0x6a,
	0xec, 0xb2, 0x2f, 0x50, 0x6c, 0x07, 0xbe, 0xef, 0x8c, 0x78, 0x26, 0x65, 0x06, 0xff, 0xf3, 0x85,
	0xa0, 0x1e, 0x97, 0xa9, 0x97, 0xed, 0xd4, 0xde, 0x42, 0x56, 0x3e, 0x21, 0xab, 0x0a, 0x85, 0xa9,
	0x33, 0xbc, 0x41, 0x99, 0x5c, 0xc9, 0x56, 0x0b, 0x76, 0x02, 0xf5, 0xf6, 0x04, 0x1d, 0x81, 0xb1,
	0x49, 0x36, 0x7e, 0xbb, 0xc1, 0x50, 0x2c, 0x48, 0x48, 0x4c, 0xc2, 0x7e, 0x11, 0xb0, 0xb2, 0xf1,
	0xe1, 0x38, 0x18, 0x85, 0x48, 0xbb, 0x50, 0x08, 0x85, 0x23, 0x14, 0xa2, 0xd2, 0x7c, 0xd5, 0x30,
	0x8a, 0xd1, 0xb8, 0x0b, 0xd9, 0xe8, 0x47, 0x30, 0x5b, 0xa1, 0xe9, 0x5b, 0x80, 0x58, 0x8c, 0x94,
	0xb7, 0xd5, 0xdc, 0xcb, 0x70, 0x25, 0x58, 0x12, 0xe1, 0xec, 0x00, 0x0a, 0x92, 0x8c, 0x6e, 0x41,
	0xb1, 0x7f, 0xd5, 0x6e, 0x77, 0xfb, 0xfd, 0xed, 0xff, 0x68, 0x19, 0x4a, 0xe7, 0x17, 0x97, 0xd7,
	0x67, 0x17, 0x57, 0xe7, 0x9d, 0x6d, 0xc2, 0x7e, 0x13, 0xa8, 0x75, 0xb9, 0x27, 0xb2, 0x9a, 0x4d,
	0x73, 0xc9, 0x3d, 0xe6, 0xfe, 0x6b, 0x3d, 0xf3, 0x93, 0xc0, 0xae, 0xa9, 0x4a, 0x57, 0xa6, 0x9d,
	0xae, 0xcc, 0x49, 0xc6, 0xcd, 0xe5, 0xb8, 0xc7, 0xae, 0xcb, 0x3b, 0xa8, 0xdb, 0xe8, 0x07, 0x53,
	0x7c, 0x50, 0x61, 0xd8, 0x29, 0x58, 0x59, 0xb8, 0x52, 0xb2, 0xda, 0xfd, 0xef, 0xa1, 0x7e, 0x86,
	0xc2, 0xfd, 0x1a, 0xe3, 0xc3, 0xf9, 0xfd, 0xbb, 0xb0, 0x19, 0x0c, 0x06, 0x21, 0x0a, 0x7d, 0xb3,
	0x5e, 0x45, 0x53, 0x35, 0xf4, 0x7c, 0x4f, 0xe8, 0x31, 0x54, 0x0b, 0xd6, 0x81, 0xa7, 0x06, 0x51,
	0x6b, 0xd6, 0xe3, 0x73, 0xae, 0x43, 0xa8, 0xc4, 0x79, 0x87, 0x3d, 0x1e, 0x71, 0xe6, 0xa3, 0x82,
	0xa6, 0x77, 0xd9, 0x73, 0xd8, 0x5b, 0xca, 0xa2, 0x25, 0x71, 0xa8, 0xaa, 0x81, 0xd2, 0x2f, 0xc5,
	0x43, 0x7a, 0xf8, 0xef, 0x0f, 0xc4, 0x2d, 0x81, 0x9a, 0x71, 0x8d, 0x6e, 0xaa, 0x56, 0xba, 0xa9,
	0x8e, 0xef, 0x18, 0x77, 0x03, 0x96, 0xee, 0xa9, 0x26, 0x14, 0x5d, 0x75, 0xae, 0x1b, 0xca, 0xca,
	0xb2, 0x68, 0xfc, 0x3c, 0x70, 0xb5, 0x52, 0x7e, 0x02, 0x1a, 0xf5, 0xb4, 0x61, 0xcd, 0x33, 0x28,
	0x69, 0x96, 0x85, 0x2f, 0xf1, 0xc6, 0x1a, 0xa6, 0xfc, 0x20, 0x06, 0xbd, 0x72, 0xe4, 0x34, 0xed,
	0xc8, 0xcb, 0xa5, 0x63, 0x96, 0xc6, 0x3c, 0x92, 0x1d, 0x6f, 0xa0, 0xaa, 0x46, 0x63, 0x1d, 0x43,
	0xd8, 0x77, 0x02, 0x35, 0x03, 0xb6, 0x6a, 0xed, 0x97, 0xc2, 0x52, 0x62, 0x57, 0x4b, 0xfc, 0x03,
	0x30, 0x39, 0x03, 0x9a, 0x29, 0x6c, 0xcd, 0x3a, 0x89, 0x3e, 0x5e, 0xe7, 0x75, 0x78, 0x01, 0x07,
	0xf7, 0x32, 0xa9, 0x14, 0x3f, 0x6f, 0xca, 0x1f, 0x89, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x11, 0xaf, 0xbb, 0x6a, 0x5d, 0x08, 0x00, 0x00,
}
