// Code generated by protoc-gen-go.
// source: keijo.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Keijo struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
}

func (m *Keijo) Reset()                    { *m = Keijo{} }
func (m *Keijo) String() string            { return proto.CompactTextString(m) }
func (*Keijo) ProtoMessage()               {}
func (*Keijo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *Keijo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Keijo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Keijo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type FetchKeijosRequest struct {
}

func (m *FetchKeijosRequest) Reset()                    { *m = FetchKeijosRequest{} }
func (m *FetchKeijosRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchKeijosRequest) ProtoMessage()               {}
func (*FetchKeijosRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

type FetchKeijosResponse struct {
}

func (m *FetchKeijosResponse) Reset()                    { *m = FetchKeijosResponse{} }
func (m *FetchKeijosResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchKeijosResponse) ProtoMessage()               {}
func (*FetchKeijosResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

type FetchKeijoByIdRequest struct {
}

func (m *FetchKeijoByIdRequest) Reset()                    { *m = FetchKeijoByIdRequest{} }
func (m *FetchKeijoByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchKeijoByIdRequest) ProtoMessage()               {}
func (*FetchKeijoByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

type FetchKeijoByIdResponse struct {
}

func (m *FetchKeijoByIdResponse) Reset()                    { *m = FetchKeijoByIdResponse{} }
func (m *FetchKeijoByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchKeijoByIdResponse) ProtoMessage()               {}
func (*FetchKeijoByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

type CreateKeijoRequest struct {
}

func (m *CreateKeijoRequest) Reset()                    { *m = CreateKeijoRequest{} }
func (m *CreateKeijoRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateKeijoRequest) ProtoMessage()               {}
func (*CreateKeijoRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

type CreateKeijoResponse struct {
}

func (m *CreateKeijoResponse) Reset()                    { *m = CreateKeijoResponse{} }
func (m *CreateKeijoResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateKeijoResponse) ProtoMessage()               {}
func (*CreateKeijoResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

type EditKeijoRequest struct {
}

func (m *EditKeijoRequest) Reset()                    { *m = EditKeijoRequest{} }
func (m *EditKeijoRequest) String() string            { return proto.CompactTextString(m) }
func (*EditKeijoRequest) ProtoMessage()               {}
func (*EditKeijoRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

type EditKeijoResponse struct {
}

func (m *EditKeijoResponse) Reset()                    { *m = EditKeijoResponse{} }
func (m *EditKeijoResponse) String() string            { return proto.CompactTextString(m) }
func (*EditKeijoResponse) ProtoMessage()               {}
func (*EditKeijoResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

type RemoveKeijoRequest struct {
}

func (m *RemoveKeijoRequest) Reset()                    { *m = RemoveKeijoRequest{} }
func (m *RemoveKeijoRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveKeijoRequest) ProtoMessage()               {}
func (*RemoveKeijoRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

type RemoveKeijoResponse struct {
}

func (m *RemoveKeijoResponse) Reset()                    { *m = RemoveKeijoResponse{} }
func (m *RemoveKeijoResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveKeijoResponse) ProtoMessage()               {}
func (*RemoveKeijoResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func init() {
	proto.RegisterType((*Keijo)(nil), "WompattiService.Keijo")
	proto.RegisterType((*FetchKeijosRequest)(nil), "WompattiService.FetchKeijosRequest")
	proto.RegisterType((*FetchKeijosResponse)(nil), "WompattiService.FetchKeijosResponse")
	proto.RegisterType((*FetchKeijoByIdRequest)(nil), "WompattiService.FetchKeijoByIdRequest")
	proto.RegisterType((*FetchKeijoByIdResponse)(nil), "WompattiService.FetchKeijoByIdResponse")
	proto.RegisterType((*CreateKeijoRequest)(nil), "WompattiService.CreateKeijoRequest")
	proto.RegisterType((*CreateKeijoResponse)(nil), "WompattiService.CreateKeijoResponse")
	proto.RegisterType((*EditKeijoRequest)(nil), "WompattiService.EditKeijoRequest")
	proto.RegisterType((*EditKeijoResponse)(nil), "WompattiService.EditKeijoResponse")
	proto.RegisterType((*RemoveKeijoRequest)(nil), "WompattiService.RemoveKeijoRequest")
	proto.RegisterType((*RemoveKeijoResponse)(nil), "WompattiService.RemoveKeijoResponse")
}

func init() { proto.RegisterFile("keijo.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4e, 0xcd, 0xcc,
	0xca, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0f, 0xcf, 0xcf, 0x2d, 0x48, 0x2c, 0x29,
	0xc9, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0xb2, 0xe6, 0x62, 0xf5, 0x06, 0xc9, 0x0b,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x31, 0x65, 0xa6, 0x80,
	0xf9, 0x05, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x05, 0x42, 0x42, 0x5c, 0x2c,
	0x05, 0xf9, 0x45, 0x25, 0x12, 0xcc, 0x60, 0x15, 0x60, 0xb6, 0x92, 0x08, 0x97, 0x90, 0x5b, 0x6a,
	0x49, 0x72, 0x06, 0xd8, 0x84, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x51, 0x2e,
	0x61, 0x14, 0xd1, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x71, 0x2e, 0x51, 0x84, 0xb0, 0x53,
	0xa5, 0x67, 0x0a, 0x4c, 0xbd, 0x04, 0x97, 0x18, 0xba, 0x04, 0x54, 0x8b, 0x08, 0x97, 0x90, 0x73,
	0x51, 0x6a, 0x62, 0x49, 0x2a, 0x58, 0x0a, 0xc9, 0x7c, 0x14, 0x51, 0xa8, 0x62, 0x21, 0x2e, 0x01,
	0xd7, 0x94, 0xcc, 0x12, 0x14, 0xa5, 0xc2, 0x5c, 0x82, 0x48, 0x62, 0x08, 0x53, 0x83, 0x52, 0x73,
	0xf3, 0xcb, 0x30, 0x4c, 0x45, 0x11, 0x85, 0x28, 0x4e, 0x62, 0x03, 0x87, 0x9b, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x69, 0xac, 0xaa, 0x46, 0x01, 0x00, 0x00,
}
