// Code generated by protoc-gen-go.
// source: keijo.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CecDevices int32

const (
	CecDevices_TV           CecDevices = 0
	CecDevices_RECORDING1   CecDevices = 1
	CecDevices_RECORDING2   CecDevices = 2
	CecDevices_TUNER1       CecDevices = 3
	CecDevices_PLAYBACK1    CecDevices = 4
	CecDevices_AUDIO_SYSTEM CecDevices = 5
	CecDevices_TUNER2       CecDevices = 6
	CecDevices_TUNER3       CecDevices = 7
	CecDevices_PLAYBACK2    CecDevices = 8
	CecDevices_PLAYBACK3    CecDevices = 9
	CecDevices_TUNER4       CecDevices = 10
	CecDevices_PLAYBACK4    CecDevices = 11
	CecDevices_RESERVEDC    CecDevices = 12
	CecDevices_RESERVEDD    CecDevices = 13
	CecDevices_RESERVEDE    CecDevices = 14
	CecDevices_BROADCAST    CecDevices = 15
)

var CecDevices_name = map[int32]string{
	0:  "TV",
	1:  "RECORDING1",
	2:  "RECORDING2",
	3:  "TUNER1",
	4:  "PLAYBACK1",
	5:  "AUDIO_SYSTEM",
	6:  "TUNER2",
	7:  "TUNER3",
	8:  "PLAYBACK2",
	9:  "PLAYBACK3",
	10: "TUNER4",
	11: "PLAYBACK4",
	12: "RESERVEDC",
	13: "RESERVEDD",
	14: "RESERVEDE",
	15: "BROADCAST",
}
var CecDevices_value = map[string]int32{
	"TV":           0,
	"RECORDING1":   1,
	"RECORDING2":   2,
	"TUNER1":       3,
	"PLAYBACK1":    4,
	"AUDIO_SYSTEM": 5,
	"TUNER2":       6,
	"TUNER3":       7,
	"PLAYBACK2":    8,
	"PLAYBACK3":    9,
	"TUNER4":       10,
	"PLAYBACK4":    11,
	"RESERVEDC":    12,
	"RESERVEDD":    13,
	"RESERVEDE":    14,
	"BROADCAST":    15,
}

func (x CecDevices) String() string {
	return proto.EnumName(CecDevices_name, int32(x))
}
func (CecDevices) EnumDescriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

type Keijo struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
}

func (m *Keijo) Reset()                    { *m = Keijo{} }
func (m *Keijo) String() string            { return proto.CompactTextString(m) }
func (*Keijo) ProtoMessage()               {}
func (*Keijo) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *Keijo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Keijo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Keijo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Keijo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type AddKeijoRequest struct {
	Slug string `protobuf:"bytes,1,opt,name=slug" json:"slug,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
}

func (m *AddKeijoRequest) Reset()                    { *m = AddKeijoRequest{} }
func (m *AddKeijoRequest) String() string            { return proto.CompactTextString(m) }
func (*AddKeijoRequest) ProtoMessage()               {}
func (*AddKeijoRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *AddKeijoRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *AddKeijoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddKeijoRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddKeijoRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type AddKeijoResponse struct {
	Keijo *Keijo `protobuf:"bytes,1,opt,name=keijo" json:"keijo,omitempty"`
}

func (m *AddKeijoResponse) Reset()                    { *m = AddKeijoResponse{} }
func (m *AddKeijoResponse) String() string            { return proto.CompactTextString(m) }
func (*AddKeijoResponse) ProtoMessage()               {}
func (*AddKeijoResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *AddKeijoResponse) GetKeijo() *Keijo {
	if m != nil {
		return m.Keijo
	}
	return nil
}

type TurnOnCecDeviceRequest struct {
	KeijoId uint32 `protobuf:"varint,1,opt,name=keijoId" json:"keijoId,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address" json:"address,omitempty"`
}

func (m *TurnOnCecDeviceRequest) Reset()                    { *m = TurnOnCecDeviceRequest{} }
func (m *TurnOnCecDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*TurnOnCecDeviceRequest) ProtoMessage()               {}
func (*TurnOnCecDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *TurnOnCecDeviceRequest) GetKeijoId() uint32 {
	if m != nil {
		return m.KeijoId
	}
	return 0
}

func (m *TurnOnCecDeviceRequest) GetAddress() uint32 {
	if m != nil {
		return m.Address
	}
	return 0
}

type TurnOnCecDeviceResponse struct {
}

func (m *TurnOnCecDeviceResponse) Reset()                    { *m = TurnOnCecDeviceResponse{} }
func (m *TurnOnCecDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*TurnOnCecDeviceResponse) ProtoMessage()               {}
func (*TurnOnCecDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

type ChangeKeijoSourceRequest struct {
	KeijoId      uint32 `protobuf:"varint,1,opt,name=keijoId" json:"keijoId,omitempty"`
	SourceNumber uint32 `protobuf:"varint,2,opt,name=sourceNumber" json:"sourceNumber,omitempty"`
}

func (m *ChangeKeijoSourceRequest) Reset()                    { *m = ChangeKeijoSourceRequest{} }
func (m *ChangeKeijoSourceRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeKeijoSourceRequest) ProtoMessage()               {}
func (*ChangeKeijoSourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *ChangeKeijoSourceRequest) GetKeijoId() uint32 {
	if m != nil {
		return m.KeijoId
	}
	return 0
}

func (m *ChangeKeijoSourceRequest) GetSourceNumber() uint32 {
	if m != nil {
		return m.SourceNumber
	}
	return 0
}

type ChangeKeijoSourceResponse struct {
}

func (m *ChangeKeijoSourceResponse) Reset()                    { *m = ChangeKeijoSourceResponse{} }
func (m *ChangeKeijoSourceResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangeKeijoSourceResponse) ProtoMessage()               {}
func (*ChangeKeijoSourceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

type ShutDownCecDeviceRequest struct {
	KeijoId uint32 `protobuf:"varint,1,opt,name=keijoId" json:"keijoId,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address" json:"address,omitempty"`
}

func (m *ShutDownCecDeviceRequest) Reset()                    { *m = ShutDownCecDeviceRequest{} }
func (m *ShutDownCecDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*ShutDownCecDeviceRequest) ProtoMessage()               {}
func (*ShutDownCecDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *ShutDownCecDeviceRequest) GetKeijoId() uint32 {
	if m != nil {
		return m.KeijoId
	}
	return 0
}

func (m *ShutDownCecDeviceRequest) GetAddress() uint32 {
	if m != nil {
		return m.Address
	}
	return 0
}

type ShutDownCecDeviceResponse struct {
}

func (m *ShutDownCecDeviceResponse) Reset()                    { *m = ShutDownCecDeviceResponse{} }
func (m *ShutDownCecDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*ShutDownCecDeviceResponse) ProtoMessage()               {}
func (*ShutDownCecDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{8} }

type FetchCecDevicePowerStatusRequest struct {
	KeijoId uint32 `protobuf:"varint,1,opt,name=keijoId" json:"keijoId,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address" json:"address,omitempty"`
}

func (m *FetchCecDevicePowerStatusRequest) Reset()         { *m = FetchCecDevicePowerStatusRequest{} }
func (m *FetchCecDevicePowerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*FetchCecDevicePowerStatusRequest) ProtoMessage()    {}
func (*FetchCecDevicePowerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{9}
}

func (m *FetchCecDevicePowerStatusRequest) GetKeijoId() uint32 {
	if m != nil {
		return m.KeijoId
	}
	return 0
}

func (m *FetchCecDevicePowerStatusRequest) GetAddress() uint32 {
	if m != nil {
		return m.Address
	}
	return 0
}

type FetchCecDevicePowerStatusResponse struct {
}

func (m *FetchCecDevicePowerStatusResponse) Reset()         { *m = FetchCecDevicePowerStatusResponse{} }
func (m *FetchCecDevicePowerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*FetchCecDevicePowerStatusResponse) ProtoMessage()    {}
func (*FetchCecDevicePowerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{10}
}

type FetchCecTvDeviceSourceByKeijoIdRequest struct {
	KeijoId uint32 `protobuf:"varint,1,opt,name=keijoId" json:"keijoId,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address" json:"address,omitempty"`
}

func (m *FetchCecTvDeviceSourceByKeijoIdRequest) Reset() {
	*m = FetchCecTvDeviceSourceByKeijoIdRequest{}
}
func (m *FetchCecTvDeviceSourceByKeijoIdRequest) String() string { return proto.CompactTextString(m) }
func (*FetchCecTvDeviceSourceByKeijoIdRequest) ProtoMessage()    {}
func (*FetchCecTvDeviceSourceByKeijoIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{11}
}

func (m *FetchCecTvDeviceSourceByKeijoIdRequest) GetKeijoId() uint32 {
	if m != nil {
		return m.KeijoId
	}
	return 0
}

func (m *FetchCecTvDeviceSourceByKeijoIdRequest) GetAddress() uint32 {
	if m != nil {
		return m.Address
	}
	return 0
}

type FetchCecTvDeviceSourceByKeijoIdResponse struct {
}

func (m *FetchCecTvDeviceSourceByKeijoIdResponse) Reset() {
	*m = FetchCecTvDeviceSourceByKeijoIdResponse{}
}
func (m *FetchCecTvDeviceSourceByKeijoIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchCecTvDeviceSourceByKeijoIdResponse) ProtoMessage()    {}
func (*FetchCecTvDeviceSourceByKeijoIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{12}
}

func init() {
	proto.RegisterType((*Keijo)(nil), "WompattiService.Keijo")
	proto.RegisterType((*AddKeijoRequest)(nil), "WompattiService.AddKeijoRequest")
	proto.RegisterType((*AddKeijoResponse)(nil), "WompattiService.AddKeijoResponse")
	proto.RegisterType((*TurnOnCecDeviceRequest)(nil), "WompattiService.TurnOnCecDeviceRequest")
	proto.RegisterType((*TurnOnCecDeviceResponse)(nil), "WompattiService.TurnOnCecDeviceResponse")
	proto.RegisterType((*ChangeKeijoSourceRequest)(nil), "WompattiService.ChangeKeijoSourceRequest")
	proto.RegisterType((*ChangeKeijoSourceResponse)(nil), "WompattiService.ChangeKeijoSourceResponse")
	proto.RegisterType((*ShutDownCecDeviceRequest)(nil), "WompattiService.ShutDownCecDeviceRequest")
	proto.RegisterType((*ShutDownCecDeviceResponse)(nil), "WompattiService.ShutDownCecDeviceResponse")
	proto.RegisterType((*FetchCecDevicePowerStatusRequest)(nil), "WompattiService.FetchCecDevicePowerStatusRequest")
	proto.RegisterType((*FetchCecDevicePowerStatusResponse)(nil), "WompattiService.FetchCecDevicePowerStatusResponse")
	proto.RegisterType((*FetchCecTvDeviceSourceByKeijoIdRequest)(nil), "WompattiService.FetchCecTvDeviceSourceByKeijoIdRequest")
	proto.RegisterType((*FetchCecTvDeviceSourceByKeijoIdResponse)(nil), "WompattiService.FetchCecTvDeviceSourceByKeijoIdResponse")
	proto.RegisterEnum("WompattiService.CecDevices", CecDevices_name, CecDevices_value)
}

func init() { proto.RegisterFile("keijo.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x69, 0xd6, 0x76, 0xf4, 0xf6, 0xdf, 0x95, 0x1f, 0x46, 0xaa, 0xbd, 0x94, 0x20, 0xc1,
	0x40, 0xa8, 0x52, 0xdb, 0x7d, 0x00, 0xd2, 0x24, 0xa0, 0xaa, 0xa3, 0x99, 0x9c, 0xac, 0x30, 0x09,
	0x84, 0xb2, 0xc6, 0x5a, 0x03, 0x34, 0x09, 0xb1, 0xb3, 0x89, 0x2f, 0xcd, 0x67, 0x40, 0x71, 0x9a,
	0x90, 0xc1, 0x04, 0x88, 0xf1, 0x76, 0x8f, 0xef, 0x2f, 0xe7, 0x1c, 0xfb, 0x21, 0xd0, 0xfe, 0xc4,
	0x82, 0x8f, 0xd1, 0x28, 0x4e, 0x22, 0x11, 0x91, 0xfe, 0x9b, 0x68, 0x1b, 0x7b, 0x42, 0x04, 0x0e,
	0x4b, 0xae, 0x82, 0x35, 0xd3, 0x6c, 0x68, 0x2c, 0xb2, 0x3d, 0xe9, 0x81, 0x12, 0xf8, 0x6a, 0x6d,
	0x58, 0x3b, 0xea, 0x52, 0x25, 0xf0, 0x09, 0x81, 0x7a, 0xe8, 0x6d, 0x99, 0xaa, 0x0c, 0x6b, 0x47,
	0x2d, 0x2a, 0x67, 0xc9, 0xc4, 0xea, 0x9e, 0x3c, 0x51, 0x82, 0x38, 0x63, 0xe2, 0x28, 0x11, 0x6a,
	0x3d, 0x67, 0xb2, 0x59, 0x7b, 0x0f, 0x7d, 0xdd, 0xf7, 0xa5, 0x27, 0x65, 0x5f, 0x52, 0xc6, 0x45,
	0x86, 0xf1, 0xcf, 0xe9, 0xa5, 0x34, 0x6f, 0x51, 0x39, 0xff, 0xb3, 0xfd, 0x0b, 0xc0, 0x1f, 0xf6,
	0x3c, 0x8e, 0x42, 0xce, 0xc8, 0x73, 0x68, 0xc8, 0x3b, 0xca, 0x80, 0xf6, 0xe4, 0x60, 0xf4, 0xd3,
	0x25, 0x47, 0x39, 0x9e, 0x43, 0xda, 0x09, 0x1c, 0xb8, 0x69, 0x12, 0xda, 0xa1, 0xc1, 0xd6, 0x26,
	0xcb, 0xf6, 0x45, 0x4f, 0x15, 0xf6, 0x25, 0x32, 0x2f, 0xde, 0xa1, 0x90, 0xd9, 0xc6, 0xf3, 0xfd,
	0x84, 0x71, 0x2e, 0x0b, 0x77, 0x69, 0x21, 0xb5, 0x01, 0x3c, 0xf8, 0xc5, 0x2d, 0xaf, 0xa5, 0xbd,
	0x05, 0xd5, 0xd8, 0x78, 0xe1, 0x25, 0x93, 0xf1, 0x4e, 0x94, 0x26, 0x7f, 0x13, 0xa5, 0x41, 0x87,
	0x4b, 0x74, 0x99, 0x6e, 0x2f, 0x58, 0xb2, 0xcb, 0xbb, 0x71, 0xa6, 0x1d, 0xc2, 0xe0, 0x16, 0xe7,
	0x5d, 0xec, 0x12, 0x54, 0x67, 0x93, 0x0a, 0x33, 0xba, 0xfe, 0x3f, 0x37, 0x3c, 0x84, 0xc1, 0x2d,
	0x7e, 0xbb, 0xb0, 0x15, 0x0c, 0x5f, 0x32, 0xb1, 0xde, 0x94, 0x9b, 0xd3, 0xe8, 0x9a, 0x25, 0x8e,
	0xf0, 0x44, 0xca, 0xef, 0x12, 0xfa, 0x08, 0x1e, 0xfe, 0xc6, 0x77, 0x17, 0xfe, 0x0e, 0x1e, 0x17,
	0x90, 0x7b, 0x95, 0x63, 0xf9, 0x5b, 0xcc, 0xbe, 0x2e, 0xf2, 0x84, 0xbb, 0x54, 0x78, 0x0a, 0x4f,
	0xfe, 0xe8, 0x9e, 0x17, 0x79, 0xf6, 0xad, 0x06, 0x50, 0x36, 0xe5, 0xa4, 0x09, 0x8a, 0xbb, 0xc2,
	0x7b, 0xa4, 0x07, 0x40, 0x2d, 0xc3, 0xa6, 0xe6, 0x7c, 0xf9, 0x6a, 0x8c, 0xb5, 0x1b, 0x7a, 0x82,
	0x0a, 0x01, 0x68, 0xba, 0x67, 0x4b, 0x8b, 0x8e, 0x71, 0x8f, 0x74, 0xa1, 0x75, 0x7a, 0xa2, 0x9f,
	0xcf, 0x74, 0x63, 0x31, 0xc6, 0x3a, 0x41, 0xe8, 0xe8, 0x67, 0xe6, 0xdc, 0xfe, 0xe0, 0x9c, 0x3b,
	0xae, 0xf5, 0x1a, 0x1b, 0x25, 0x3c, 0xc1, 0x66, 0x39, 0x4f, 0x71, 0xbf, 0xfa, 0xe1, 0x04, 0xef,
	0x57, 0xe5, 0x14, 0x5b, 0x25, 0x79, 0x8c, 0x50, 0x5d, 0x1d, 0x63, 0x3b, 0x93, 0xd4, 0x72, 0x2c,
	0xba, 0xb2, 0x4c, 0x03, 0x3b, 0x55, 0x69, 0x62, 0xb7, 0x2a, 0x2d, 0xec, 0x65, 0x72, 0x46, 0x6d,
	0xdd, 0x34, 0x74, 0xc7, 0xc5, 0xfe, 0x45, 0x53, 0xfe, 0x4d, 0xa6, 0xdf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x1b, 0x5d, 0x1c, 0x32, 0x5c, 0x04, 0x00, 0x00,
}
