// Code generated by protoc-gen-go.
// source: serial_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateSerialInterfaceResponse_State int32

const (
	CreateSerialInterfaceResponse_SUCCESS   CreateSerialInterfaceResponse_State = 0
	CreateSerialInterfaceResponse_NOT_FOUND CreateSerialInterfaceResponse_State = 1
)

var CreateSerialInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateSerialInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateSerialInterfaceResponse_State) String() string {
	return proto.EnumName(CreateSerialInterfaceResponse_State_name, int32(x))
}
func (CreateSerialInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor7, []int{7, 0}
}

type EditSerialInterfaceResponse_State int32

const (
	EditSerialInterfaceResponse_SUCCESS   EditSerialInterfaceResponse_State = 0
	EditSerialInterfaceResponse_NOT_FOUND EditSerialInterfaceResponse_State = 1
)

var EditSerialInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditSerialInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditSerialInterfaceResponse_State) String() string {
	return proto.EnumName(EditSerialInterfaceResponse_State_name, int32(x))
}
func (EditSerialInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor7, []int{9, 0}
}

type SerialInterface struct {
	Id           uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SerialPortId uint32 `protobuf:"varint,2,opt,name=serialPortId" json:"serialPortId,omitempty"`
}

func (m *SerialInterface) Reset()                    { *m = SerialInterface{} }
func (m *SerialInterface) String() string            { return proto.CompactTextString(m) }
func (*SerialInterface) ProtoMessage()               {}
func (*SerialInterface) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *SerialInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SerialInterface) GetSerialPortId() uint32 {
	if m != nil {
		return m.SerialPortId
	}
	return 0
}

type SerialInterfacesEdge struct {
	Node   *SerialInterface `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32           `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *SerialInterfacesEdge) Reset()                    { *m = SerialInterfacesEdge{} }
func (m *SerialInterfacesEdge) String() string            { return proto.CompactTextString(m) }
func (*SerialInterfacesEdge) ProtoMessage()               {}
func (*SerialInterfacesEdge) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *SerialInterfacesEdge) GetNode() *SerialInterface {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *SerialInterfacesEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type SerialInterfacesConnection struct {
	PageInfo   *PageInfo               `protobuf:"bytes,1,opt,name=pageInfo" json:"pageInfo,omitempty"`
	Edges      []*SerialInterfacesEdge `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32                  `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *SerialInterfacesConnection) Reset()                    { *m = SerialInterfacesConnection{} }
func (m *SerialInterfacesConnection) String() string            { return proto.CompactTextString(m) }
func (*SerialInterfacesConnection) ProtoMessage()               {}
func (*SerialInterfacesConnection) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *SerialInterfacesConnection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *SerialInterfacesConnection) GetEdges() []*SerialInterfacesEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *SerialInterfacesConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type FetchSerialInterfacesRequest struct {
	After  uint32 `protobuf:"varint,1,opt,name=after" json:"after,omitempty"`
	Before uint32 `protobuf:"varint,2,opt,name=before" json:"before,omitempty"`
	First  uint32 `protobuf:"varint,3,opt,name=first" json:"first,omitempty"`
	Last   uint32 `protobuf:"varint,4,opt,name=last" json:"last,omitempty"`
}

func (m *FetchSerialInterfacesRequest) Reset()                    { *m = FetchSerialInterfacesRequest{} }
func (m *FetchSerialInterfacesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSerialInterfacesRequest) ProtoMessage()               {}
func (*FetchSerialInterfacesRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *FetchSerialInterfacesRequest) GetAfter() uint32 {
	if m != nil {
		return m.After
	}
	return 0
}

func (m *FetchSerialInterfacesRequest) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

func (m *FetchSerialInterfacesRequest) GetFirst() uint32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *FetchSerialInterfacesRequest) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type FetchSerialInterfaceByIdRequest struct {
	SerialInterfaceIdt []uint32 `protobuf:"varint,1,rep,packed,name=serialInterfaceIdt" json:"serialInterfaceIdt,omitempty"`
}

func (m *FetchSerialInterfaceByIdRequest) Reset()                    { *m = FetchSerialInterfaceByIdRequest{} }
func (m *FetchSerialInterfaceByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSerialInterfaceByIdRequest) ProtoMessage()               {}
func (*FetchSerialInterfaceByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *FetchSerialInterfaceByIdRequest) GetSerialInterfaceIdt() []uint32 {
	if m != nil {
		return m.SerialInterfaceIdt
	}
	return nil
}

type FetchSerialInterfaceByIdResponse struct {
	SerialInterfaces []*SerialInterface `protobuf:"bytes,1,rep,name=serialInterfaces" json:"serialInterfaces,omitempty"`
}

func (m *FetchSerialInterfaceByIdResponse) Reset()         { *m = FetchSerialInterfaceByIdResponse{} }
func (m *FetchSerialInterfaceByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSerialInterfaceByIdResponse) ProtoMessage()    {}
func (*FetchSerialInterfaceByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{5}
}

func (m *FetchSerialInterfaceByIdResponse) GetSerialInterfaces() []*SerialInterface {
	if m != nil {
		return m.SerialInterfaces
	}
	return nil
}

type CreateSerialInterfaceRequest struct {
	SerialPortId uint32 `protobuf:"varint,1,opt,name=serialPortId" json:"serialPortId,omitempty"`
}

func (m *CreateSerialInterfaceRequest) Reset()                    { *m = CreateSerialInterfaceRequest{} }
func (m *CreateSerialInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSerialInterfaceRequest) ProtoMessage()               {}
func (*CreateSerialInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *CreateSerialInterfaceRequest) GetSerialPortId() uint32 {
	if m != nil {
		return m.SerialPortId
	}
	return 0
}

type CreateSerialInterfaceResponse struct {
	State           CreateSerialInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateSerialInterfaceResponse_State" json:"state,omitempty"`
	SerialInterface *SerialInterface                    `protobuf:"bytes,2,opt,name=serialInterface" json:"serialInterface,omitempty"`
}

func (m *CreateSerialInterfaceResponse) Reset()                    { *m = CreateSerialInterfaceResponse{} }
func (m *CreateSerialInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSerialInterfaceResponse) ProtoMessage()               {}
func (*CreateSerialInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *CreateSerialInterfaceResponse) GetState() CreateSerialInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return CreateSerialInterfaceResponse_SUCCESS
}

func (m *CreateSerialInterfaceResponse) GetSerialInterface() *SerialInterface {
	if m != nil {
		return m.SerialInterface
	}
	return nil
}

type EditSerialInterfaceRequest struct {
	SerialInterfaceId uint32 `protobuf:"varint,1,opt,name=serialInterfaceId" json:"serialInterfaceId,omitempty"`
	SerialPortId      uint32 `protobuf:"varint,2,opt,name=serialPortId" json:"serialPortId,omitempty"`
}

func (m *EditSerialInterfaceRequest) Reset()                    { *m = EditSerialInterfaceRequest{} }
func (m *EditSerialInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EditSerialInterfaceRequest) ProtoMessage()               {}
func (*EditSerialInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *EditSerialInterfaceRequest) GetSerialInterfaceId() uint32 {
	if m != nil {
		return m.SerialInterfaceId
	}
	return 0
}

func (m *EditSerialInterfaceRequest) GetSerialPortId() uint32 {
	if m != nil {
		return m.SerialPortId
	}
	return 0
}

type EditSerialInterfaceResponse struct {
	State           EditSerialInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditSerialInterfaceResponse_State" json:"state,omitempty"`
	SerialInterface *SerialInterface                  `protobuf:"bytes,2,opt,name=serialInterface" json:"serialInterface,omitempty"`
}

func (m *EditSerialInterfaceResponse) Reset()                    { *m = EditSerialInterfaceResponse{} }
func (m *EditSerialInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EditSerialInterfaceResponse) ProtoMessage()               {}
func (*EditSerialInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *EditSerialInterfaceResponse) GetState() EditSerialInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return EditSerialInterfaceResponse_SUCCESS
}

func (m *EditSerialInterfaceResponse) GetSerialInterface() *SerialInterface {
	if m != nil {
		return m.SerialInterface
	}
	return nil
}

type RemoveSerialInterfaceRequest struct {
	SerialInterfaceId uint32 `protobuf:"varint,1,opt,name=serialInterfaceId" json:"serialInterfaceId,omitempty"`
}

func (m *RemoveSerialInterfaceRequest) Reset()                    { *m = RemoveSerialInterfaceRequest{} }
func (m *RemoveSerialInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveSerialInterfaceRequest) ProtoMessage()               {}
func (*RemoveSerialInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *RemoveSerialInterfaceRequest) GetSerialInterfaceId() uint32 {
	if m != nil {
		return m.SerialInterfaceId
	}
	return 0
}

type RemoveSerialInterfaceResponse struct {
}

func (m *RemoveSerialInterfaceResponse) Reset()                    { *m = RemoveSerialInterfaceResponse{} }
func (m *RemoveSerialInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveSerialInterfaceResponse) ProtoMessage()               {}
func (*RemoveSerialInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func init() {
	proto.RegisterType((*SerialInterface)(nil), "WompattiService.SerialInterface")
	proto.RegisterType((*SerialInterfacesEdge)(nil), "WompattiService.SerialInterfacesEdge")
	proto.RegisterType((*SerialInterfacesConnection)(nil), "WompattiService.SerialInterfacesConnection")
	proto.RegisterType((*FetchSerialInterfacesRequest)(nil), "WompattiService.FetchSerialInterfacesRequest")
	proto.RegisterType((*FetchSerialInterfaceByIdRequest)(nil), "WompattiService.FetchSerialInterfaceByIdRequest")
	proto.RegisterType((*FetchSerialInterfaceByIdResponse)(nil), "WompattiService.FetchSerialInterfaceByIdResponse")
	proto.RegisterType((*CreateSerialInterfaceRequest)(nil), "WompattiService.CreateSerialInterfaceRequest")
	proto.RegisterType((*CreateSerialInterfaceResponse)(nil), "WompattiService.CreateSerialInterfaceResponse")
	proto.RegisterType((*EditSerialInterfaceRequest)(nil), "WompattiService.EditSerialInterfaceRequest")
	proto.RegisterType((*EditSerialInterfaceResponse)(nil), "WompattiService.EditSerialInterfaceResponse")
	proto.RegisterType((*RemoveSerialInterfaceRequest)(nil), "WompattiService.RemoveSerialInterfaceRequest")
	proto.RegisterType((*RemoveSerialInterfaceResponse)(nil), "WompattiService.RemoveSerialInterfaceResponse")
	proto.RegisterEnum("WompattiService.CreateSerialInterfaceResponse_State", CreateSerialInterfaceResponse_State_name, CreateSerialInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.EditSerialInterfaceResponse_State", EditSerialInterfaceResponse_State_name, EditSerialInterfaceResponse_State_value)
}

func init() { proto.RegisterFile("serial_interface.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x65, 0xf3, 0x51, 0x60, 0x42, 0x9a, 0x60, 0x55, 0xd5, 0x12, 0x52, 0x1a, 0x19, 0x21, 0xe5,
	0x80, 0x72, 0x08, 0xe5, 0xc4, 0xad, 0x21, 0x15, 0x5b, 0x55, 0x6d, 0xd9, 0xa5, 0xe2, 0x18, 0x6d,
	0xd7, 0xb3, 0xc1, 0x52, 0x6a, 0x2f, 0xb6, 0x13, 0x89, 0x7f, 0xc5, 0xcf, 0xe1, 0xc0, 0x8f, 0x41,
	0xf1, 0x6e, 0x10, 0xf1, 0x26, 0x25, 0x07, 0x24, 0x6e, 0x19, 0xcf, 0xbc, 0xf7, 0xe6, 0x3d, 0x3b,
	0x0b, 0x87, 0x1a, 0x15, 0x8f, 0x67, 0x13, 0x2e, 0x0c, 0xaa, 0x34, 0x4e, 0x70, 0x90, 0x29, 0x69,
	0x24, 0x69, 0x7d, 0x96, 0x77, 0x59, 0x6c, 0x0c, 0x8f, 0x50, 0x2d, 0x78, 0x82, 0x9d, 0x56, 0x16,
	0x4f, 0x71, 0xc2, 0x45, 0x2a, 0xf3, 0x09, 0x3a, 0x86, 0x56, 0x64, 0xb1, 0xc1, 0x0a, 0x4a, 0xf6,
	0xa1, 0xc2, 0x99, 0xef, 0xf5, 0xbc, 0x7e, 0x33, 0xac, 0x70, 0x46, 0x28, 0x3c, 0xc9, 0xe9, 0xaf,
	0xa5, 0x32, 0x01, 0xf3, 0x2b, 0xb6, 0xb3, 0x76, 0x46, 0x19, 0x1c, 0x38, 0x34, 0x7a, 0xcc, 0xa6,
	0x48, 0x4e, 0xa0, 0x26, 0x24, 0x43, 0xcb, 0xd6, 0x18, 0xf6, 0x06, 0xce, 0x3e, 0x03, 0x07, 0x14,
	0xda, 0x69, 0x72, 0x08, 0x7b, 0xc9, 0x5c, 0x69, 0xa9, 0x0a, 0xad, 0xa2, 0xa2, 0xdf, 0x3d, 0xe8,
	0xb8, 0x32, 0x23, 0x29, 0x04, 0x26, 0x86, 0x4b, 0x41, 0xde, 0xc2, 0xa3, 0xa5, 0xbd, 0x40, 0xa4,
	0xb2, 0x10, 0x7c, 0x56, 0x12, 0xbc, 0x2e, 0x06, 0xc2, 0xdf, 0xa3, 0xe4, 0x1d, 0xd4, 0x91, 0x4d,
	0x51, 0xfb, 0x95, 0x5e, 0xb5, 0xdf, 0x18, 0xbe, 0xfa, 0xdb, 0x92, 0xd6, 0x59, 0x98, 0x63, 0xc8,
	0x0b, 0x00, 0x23, 0x4d, 0x3c, 0x1b, 0xc9, 0xb9, 0x30, 0x7e, 0xd5, 0xae, 0xfb, 0xc7, 0x09, 0x5d,
	0x40, 0xf7, 0x0c, 0x4d, 0xf2, 0xc5, 0xe5, 0x08, 0xf1, 0xeb, 0x1c, 0xb5, 0x21, 0x07, 0x50, 0x8f,
	0x53, 0x83, 0xaa, 0xc8, 0x3b, 0x2f, 0x96, 0x01, 0xdc, 0x62, 0x2a, 0x15, 0xae, 0x02, 0xc8, 0xab,
	0xe5, 0x74, 0xca, 0x95, 0x5e, 0x09, 0xe5, 0x05, 0x21, 0x50, 0x9b, 0xc5, 0xda, 0xf8, 0x35, 0x7b,
	0x68, 0x7f, 0xd3, 0x8f, 0x70, 0xbc, 0x49, 0xf7, 0xf4, 0x5b, 0xc0, 0x56, 0xd2, 0x03, 0x20, 0x7a,
	0xbd, 0x1b, 0x30, 0xe3, 0x7b, 0xbd, 0x6a, 0xbf, 0x19, 0x6e, 0xe8, 0xd0, 0x0c, 0x7a, 0xdb, 0x29,
	0x75, 0x26, 0x85, 0x46, 0x72, 0x01, 0x6d, 0x07, 0xa9, 0x2d, 0xe3, 0x2e, 0x77, 0x5f, 0x42, 0xd2,
	0x53, 0xe8, 0x8e, 0x14, 0xc6, 0x06, 0xdd, 0xd1, 0xc2, 0x81, 0xfb, 0x32, 0xbd, 0x0d, 0x2f, 0xf3,
	0xa7, 0x07, 0x47, 0x5b, 0x48, 0x8a, 0x9d, 0xcf, 0xa1, 0xae, 0x4d, 0x6c, 0xf2, 0x47, 0xba, 0x3f,
	0x3c, 0x29, 0x2d, 0x7a, 0x2f, 0x7c, 0x10, 0x2d, 0xb1, 0x61, 0x4e, 0x41, 0xce, 0xa1, 0xe5, 0xb8,
	0xb0, 0x37, 0xb8, 0x8b, 0x7d, 0x17, 0x48, 0x5f, 0x42, 0xdd, 0x72, 0x93, 0x06, 0x3c, 0x8c, 0x6e,
	0x46, 0xa3, 0x71, 0x14, 0xb5, 0x1f, 0x90, 0x26, 0x3c, 0xbe, 0xbc, 0xfa, 0x34, 0x39, 0xbb, 0xba,
	0xb9, 0x7c, 0xdf, 0xf6, 0xa8, 0x80, 0xce, 0x98, 0x71, 0xb3, 0x25, 0xa0, 0xd7, 0xf0, 0xb4, 0x74,
	0x91, 0x45, 0x4a, 0xe5, 0xc6, 0x4e, 0x7f, 0xf4, 0x1f, 0x1e, 0x3c, 0xdf, 0x28, 0x58, 0x84, 0xf9,
	0x61, 0x3d, 0xcc, 0x61, 0xc9, 0xf6, 0x3d, 0xe0, 0xff, 0x1c, 0xe5, 0x05, 0x74, 0x43, 0xbc, 0x93,
	0x0b, 0xfc, 0x17, 0x61, 0xd2, 0x63, 0x38, 0xda, 0xc2, 0x96, 0x9b, 0xbd, 0xdd, 0xb3, 0x1f, 0xe0,
	0x37, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0xb6, 0x1e, 0x80, 0xbc, 0x05, 0x00, 0x00,
}
