// Code generated by protoc-gen-go.
// source: telnet_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EditTelnetInterfaceResponse_State int32

const (
	EditTelnetInterfaceResponse_SUCCESS   EditTelnetInterfaceResponse_State = 0
	EditTelnetInterfaceResponse_NOT_FOUND EditTelnetInterfaceResponse_State = 1
)

var EditTelnetInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditTelnetInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditTelnetInterfaceResponse_State) String() string {
	return proto.EnumName(EditTelnetInterfaceResponse_State_name, int32(x))
}
func (EditTelnetInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{10, 0}
}

type RemoveTelnetInterfaceResponse_State int32

const (
	RemoveTelnetInterfaceResponse_SUCCESS   RemoveTelnetInterfaceResponse_State = 0
	RemoveTelnetInterfaceResponse_NOT_FOUND RemoveTelnetInterfaceResponse_State = 1
)

var RemoveTelnetInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveTelnetInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveTelnetInterfaceResponse_State) String() string {
	return proto.EnumName(RemoveTelnetInterfaceResponse_State_name, int32(x))
}
func (RemoveTelnetInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{12, 0}
}

type TelnetInterface struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
}

func (m *TelnetInterface) Reset()                    { *m = TelnetInterface{} }
func (m *TelnetInterface) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterface) ProtoMessage()               {}
func (*TelnetInterface) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *TelnetInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TelnetInterface) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TelnetInterface) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type TelnetInterfacesConnection struct {
	PageInfo   *PageInfo               `protobuf:"bytes,1,opt,name=pageInfo" json:"pageInfo,omitempty"`
	Edges      []*TelnetInterfacesEdge `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32                  `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *TelnetInterfacesConnection) Reset()                    { *m = TelnetInterfacesConnection{} }
func (m *TelnetInterfacesConnection) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterfacesConnection) ProtoMessage()               {}
func (*TelnetInterfacesConnection) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *TelnetInterfacesConnection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *TelnetInterfacesConnection) GetEdges() []*TelnetInterfacesEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *TelnetInterfacesConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type TelnetInterfacesEdge struct {
	Node   *TelnetInterface `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32           `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *TelnetInterfacesEdge) Reset()                    { *m = TelnetInterfacesEdge{} }
func (m *TelnetInterfacesEdge) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterfacesEdge) ProtoMessage()               {}
func (*TelnetInterfacesEdge) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *TelnetInterfacesEdge) GetNode() *TelnetInterface {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *TelnetInterfacesEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type FetchTelnetInterfacesRequest struct {
}

func (m *FetchTelnetInterfacesRequest) Reset()                    { *m = FetchTelnetInterfacesRequest{} }
func (m *FetchTelnetInterfacesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchTelnetInterfacesRequest) ProtoMessage()               {}
func (*FetchTelnetInterfacesRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

type FetchTelnetInterfacesResponse struct {
}

func (m *FetchTelnetInterfacesResponse) Reset()                    { *m = FetchTelnetInterfacesResponse{} }
func (m *FetchTelnetInterfacesResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchTelnetInterfacesResponse) ProtoMessage()               {}
func (*FetchTelnetInterfacesResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

type FetchTelnetInterfaceByIdRequest struct {
	TelnetInterfaceId []uint32 `protobuf:"varint,1,rep,packed,name=telnetInterfaceId" json:"telnetInterfaceId,omitempty"`
}

func (m *FetchTelnetInterfaceByIdRequest) Reset()         { *m = FetchTelnetInterfaceByIdRequest{} }
func (m *FetchTelnetInterfaceByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTelnetInterfaceByIdRequest) ProtoMessage()    {}
func (*FetchTelnetInterfaceByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{5}
}

func (m *FetchTelnetInterfaceByIdRequest) GetTelnetInterfaceId() []uint32 {
	if m != nil {
		return m.TelnetInterfaceId
	}
	return nil
}

type FetchTelnetInterfaceByIdResponse struct {
	TelnetInterfaces []*TelnetInterface `protobuf:"bytes,1,rep,name=telnetInterfaces" json:"telnetInterfaces,omitempty"`
}

func (m *FetchTelnetInterfaceByIdResponse) Reset()         { *m = FetchTelnetInterfaceByIdResponse{} }
func (m *FetchTelnetInterfaceByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTelnetInterfaceByIdResponse) ProtoMessage()    {}
func (*FetchTelnetInterfaceByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{6}
}

func (m *FetchTelnetInterfaceByIdResponse) GetTelnetInterfaces() []*TelnetInterface {
	if m != nil {
		return m.TelnetInterfaces
	}
	return nil
}

type CreateTelnetInterfaceRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *CreateTelnetInterfaceRequest) Reset()                    { *m = CreateTelnetInterfaceRequest{} }
func (m *CreateTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTelnetInterfaceRequest) ProtoMessage()               {}
func (*CreateTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

func (m *CreateTelnetInterfaceRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateTelnetInterfaceRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type CreateTelnetInterfaceResponse struct {
	TelnetInterface *TelnetInterface `protobuf:"bytes,1,opt,name=telnetInterface" json:"telnetInterface,omitempty"`
}

func (m *CreateTelnetInterfaceResponse) Reset()                    { *m = CreateTelnetInterfaceResponse{} }
func (m *CreateTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTelnetInterfaceResponse) ProtoMessage()               {}
func (*CreateTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *CreateTelnetInterfaceResponse) GetTelnetInterface() *TelnetInterface {
	if m != nil {
		return m.TelnetInterface
	}
	return nil
}

type EditTelnetInterfaceRequest struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
}

func (m *EditTelnetInterfaceRequest) Reset()                    { *m = EditTelnetInterfaceRequest{} }
func (m *EditTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EditTelnetInterfaceRequest) ProtoMessage()               {}
func (*EditTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{9} }

func (m *EditTelnetInterfaceRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditTelnetInterfaceRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *EditTelnetInterfaceRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type EditTelnetInterfaceResponse struct {
	State           EditTelnetInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditTelnetInterfaceResponse_State" json:"state,omitempty"`
	TelnetInterface *TelnetInterface                  `protobuf:"bytes,2,opt,name=telnetInterface" json:"telnetInterface,omitempty"`
}

func (m *EditTelnetInterfaceResponse) Reset()                    { *m = EditTelnetInterfaceResponse{} }
func (m *EditTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EditTelnetInterfaceResponse) ProtoMessage()               {}
func (*EditTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *EditTelnetInterfaceResponse) GetState() EditTelnetInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return EditTelnetInterfaceResponse_SUCCESS
}

func (m *EditTelnetInterfaceResponse) GetTelnetInterface() *TelnetInterface {
	if m != nil {
		return m.TelnetInterface
	}
	return nil
}

type RemoveTelnetInterfaceRequest struct {
	TelnetInterfaceId uint32 `protobuf:"varint,1,opt,name=telnetInterfaceId" json:"telnetInterfaceId,omitempty"`
}

func (m *RemoveTelnetInterfaceRequest) Reset()                    { *m = RemoveTelnetInterfaceRequest{} }
func (m *RemoveTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveTelnetInterfaceRequest) ProtoMessage()               {}
func (*RemoveTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{11} }

func (m *RemoveTelnetInterfaceRequest) GetTelnetInterfaceId() uint32 {
	if m != nil {
		return m.TelnetInterfaceId
	}
	return 0
}

type RemoveTelnetInterfaceResponse struct {
	State RemoveTelnetInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveTelnetInterfaceResponse_State" json:"state,omitempty"`
}

func (m *RemoveTelnetInterfaceResponse) Reset()                    { *m = RemoveTelnetInterfaceResponse{} }
func (m *RemoveTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveTelnetInterfaceResponse) ProtoMessage()               {}
func (*RemoveTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *RemoveTelnetInterfaceResponse) GetState() RemoveTelnetInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveTelnetInterfaceResponse_SUCCESS
}

func init() {
	proto.RegisterType((*TelnetInterface)(nil), "WompattiService.TelnetInterface")
	proto.RegisterType((*TelnetInterfacesConnection)(nil), "WompattiService.TelnetInterfacesConnection")
	proto.RegisterType((*TelnetInterfacesEdge)(nil), "WompattiService.TelnetInterfacesEdge")
	proto.RegisterType((*FetchTelnetInterfacesRequest)(nil), "WompattiService.FetchTelnetInterfacesRequest")
	proto.RegisterType((*FetchTelnetInterfacesResponse)(nil), "WompattiService.FetchTelnetInterfacesResponse")
	proto.RegisterType((*FetchTelnetInterfaceByIdRequest)(nil), "WompattiService.FetchTelnetInterfaceByIdRequest")
	proto.RegisterType((*FetchTelnetInterfaceByIdResponse)(nil), "WompattiService.FetchTelnetInterfaceByIdResponse")
	proto.RegisterType((*CreateTelnetInterfaceRequest)(nil), "WompattiService.CreateTelnetInterfaceRequest")
	proto.RegisterType((*CreateTelnetInterfaceResponse)(nil), "WompattiService.CreateTelnetInterfaceResponse")
	proto.RegisterType((*EditTelnetInterfaceRequest)(nil), "WompattiService.EditTelnetInterfaceRequest")
	proto.RegisterType((*EditTelnetInterfaceResponse)(nil), "WompattiService.EditTelnetInterfaceResponse")
	proto.RegisterType((*RemoveTelnetInterfaceRequest)(nil), "WompattiService.RemoveTelnetInterfaceRequest")
	proto.RegisterType((*RemoveTelnetInterfaceResponse)(nil), "WompattiService.RemoveTelnetInterfaceResponse")
	proto.RegisterEnum("WompattiService.EditTelnetInterfaceResponse_State", EditTelnetInterfaceResponse_State_name, EditTelnetInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveTelnetInterfaceResponse_State", RemoveTelnetInterfaceResponse_State_name, RemoveTelnetInterfaceResponse_State_value)
}

func init() { proto.RegisterFile("telnet_interface.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0x53, 0xe8, 0x44, 0x69, 0xc2, 0x0a, 0x55, 0x21, 0x24, 0xad, 0xb5, 0x08, 0x29,
	0x07, 0x94, 0x43, 0x28, 0x27, 0x6e, 0x35, 0xa9, 0x08, 0xaa, 0x9a, 0x6a, 0xdd, 0x8a, 0x63, 0x64,
	0xec, 0x49, 0x58, 0xd1, 0xee, 0x1a, 0x7b, 0x52, 0x89, 0x7f, 0xc1, 0x4f, 0xe1, 0xe7, 0xf0, 0x73,
	0x50, 0xd6, 0x4e, 0x45, 0xfc, 0x11, 0xa2, 0xde, 0xbc, 0x9e, 0xf7, 0xde, 0xbc, 0x9d, 0x79, 0x36,
	0x1c, 0x11, 0xde, 0x2a, 0xa4, 0x99, 0x54, 0x84, 0xf1, 0xdc, 0x0f, 0x70, 0x18, 0xc5, 0x9a, 0x34,
	0x6b, 0x7d, 0xd1, 0x77, 0x91, 0x4f, 0x24, 0x3d, 0x8c, 0xef, 0x65, 0x80, 0xdd, 0x56, 0xe4, 0x2f,
	0x70, 0x26, 0xd5, 0x5c, 0xa7, 0x08, 0x3e, 0x86, 0xd6, 0xb5, 0xe1, 0x4e, 0xd6, 0x54, 0x76, 0x08,
	0xb6, 0x0c, 0x3b, 0x96, 0x63, 0x0d, 0x9a, 0xc2, 0x96, 0xa1, 0x39, 0x47, 0x1d, 0xdb, 0xb1, 0x06,
	0x07, 0xc2, 0x96, 0x11, 0x63, 0xb0, 0x17, 0xe9, 0x98, 0x3a, 0x35, 0x83, 0x30, 0xcf, 0xfc, 0xb7,
	0x05, 0xdd, 0x9c, 0x4e, 0xe2, 0x6a, 0xa5, 0x30, 0x20, 0xa9, 0x15, 0x7b, 0x0f, 0xcf, 0x56, 0x8d,
	0x27, 0x6a, 0xae, 0x8d, 0x70, 0x63, 0xf4, 0x72, 0x98, 0xb3, 0x36, 0xbc, 0xca, 0x00, 0xe2, 0x01,
	0xca, 0x3e, 0x40, 0x1d, 0xc3, 0x05, 0x26, 0x1d, 0xdb, 0xa9, 0x0d, 0x1a, 0xa3, 0x37, 0x05, 0x4e,
	0xbe, 0xe5, 0x38, 0x5c, 0xa0, 0x48, 0x39, 0xec, 0x18, 0x80, 0x34, 0xf9, 0xb7, 0xae, 0x5e, 0xaa,
	0xb5, 0xd9, 0x7f, 0xde, 0xf0, 0x10, 0x5e, 0x94, 0xd1, 0xd9, 0x29, 0xec, 0x29, 0x1d, 0x62, 0xe6,
	0xd3, 0xf9, 0x5f, 0x4f, 0x61, 0xd0, 0xec, 0x08, 0xf6, 0x83, 0x65, 0x9c, 0xe8, 0xd8, 0x0c, 0xaa,
	0x29, 0xb2, 0x13, 0x3f, 0x86, 0xde, 0x39, 0x52, 0xf0, 0x2d, 0xdf, 0x4a, 0xe0, 0x8f, 0x25, 0x26,
	0xc4, 0x4f, 0xa0, 0x5f, 0x51, 0x4f, 0x22, 0xad, 0x12, 0xe4, 0x53, 0x38, 0x29, 0x03, 0x9c, 0xfd,
	0x9c, 0x84, 0x99, 0x06, 0x7b, 0x0b, 0xcf, 0x69, 0xb3, 0x3a, 0x59, 0xed, 0xaf, 0x36, 0x68, 0x8a,
	0x62, 0x81, 0x47, 0xe0, 0x54, 0x0b, 0xa6, 0x4d, 0xd9, 0x05, 0xb4, 0x73, 0xc4, 0xc4, 0x08, 0xee,
	0x32, 0x8f, 0x02, 0x93, 0x9f, 0x41, 0xcf, 0x8d, 0xd1, 0x27, 0xcc, 0x43, 0x33, 0xff, 0x69, 0xc0,
	0xac, 0x42, 0xc0, 0xd2, 0xc8, 0xa5, 0x01, 0xfb, 0x0e, 0xfd, 0x0a, 0x8d, 0xcc, 0xf2, 0x67, 0x68,
	0xe5, 0x1a, 0xef, 0xbc, 0xc1, 0x3c, 0x91, 0x5f, 0x41, 0x77, 0x1c, 0x4a, 0xda, 0x62, 0x77, 0xd7,
	0xef, 0x63, 0x6d, 0xff, 0x8f, 0x05, 0xaf, 0x4a, 0x25, 0x33, 0xf7, 0x9f, 0xa0, 0x9e, 0x90, 0x4f,
	0xa9, 0xe7, 0xc3, 0xd1, 0xa8, 0xe0, 0x79, 0x0b, 0x79, 0xe8, 0xad, 0x98, 0x22, 0x15, 0x28, 0x9b,
	0x83, 0xfd, 0xd8, 0x39, 0xbc, 0x86, 0xba, 0xd1, 0x66, 0x0d, 0x78, 0xea, 0xdd, 0xb8, 0xee, 0xd8,
	0xf3, 0xda, 0x4f, 0x58, 0x13, 0x0e, 0x2e, 0xa7, 0xd7, 0xb3, 0xf3, 0xe9, 0xcd, 0xe5, 0xc7, 0xb6,
	0xc5, 0x2f, 0xa0, 0x27, 0xf0, 0x4e, 0xdf, 0x57, 0x6d, 0xb7, 0x22, 0x9d, 0x56, 0x79, 0x3a, 0x7f,
	0x59, 0xd0, 0xaf, 0x90, 0x7b, 0x58, 0xf4, 0xc6, 0xa8, 0x4e, 0x0b, 0xd7, 0xda, 0x4a, 0xdf, 0x18,
	0xd6, 0x4e, 0x17, 0xfc, 0xba, 0x6f, 0xfe, 0x94, 0xef, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0x96, 0xe3, 0xc8, 0x65, 0x05, 0x00, 0x00,
}
