// Code generated by protoc-gen-go.
// source: telnet_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RemoveTelnetInterfaceResponse_State int32

const (
	RemoveTelnetInterfaceResponse_SUCCESS   RemoveTelnetInterfaceResponse_State = 0
	RemoveTelnetInterfaceResponse_NOT_FOUND RemoveTelnetInterfaceResponse_State = 1
)

var RemoveTelnetInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveTelnetInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveTelnetInterfaceResponse_State) String() string {
	return proto.EnumName(RemoveTelnetInterfaceResponse_State_name, int32(x))
}
func (RemoveTelnetInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{6, 0}
}

type TelnetInterface struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
}

func (m *TelnetInterface) Reset()                    { *m = TelnetInterface{} }
func (m *TelnetInterface) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterface) ProtoMessage()               {}
func (*TelnetInterface) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *TelnetInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TelnetInterface) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TelnetInterface) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type CreateTelnetInterfaceRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *CreateTelnetInterfaceRequest) Reset()                    { *m = CreateTelnetInterfaceRequest{} }
func (m *CreateTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTelnetInterfaceRequest) ProtoMessage()               {}
func (*CreateTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *CreateTelnetInterfaceRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateTelnetInterfaceRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type CreateTelnetInterfaceResponse struct {
}

func (m *CreateTelnetInterfaceResponse) Reset()                    { *m = CreateTelnetInterfaceResponse{} }
func (m *CreateTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTelnetInterfaceResponse) ProtoMessage()               {}
func (*CreateTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

type EditTelnetInterfaceRequest struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
}

func (m *EditTelnetInterfaceRequest) Reset()                    { *m = EditTelnetInterfaceRequest{} }
func (m *EditTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EditTelnetInterfaceRequest) ProtoMessage()               {}
func (*EditTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *EditTelnetInterfaceRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditTelnetInterfaceRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *EditTelnetInterfaceRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type EditTelnetInterfaceResponse struct {
}

func (m *EditTelnetInterfaceResponse) Reset()                    { *m = EditTelnetInterfaceResponse{} }
func (m *EditTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EditTelnetInterfaceResponse) ProtoMessage()               {}
func (*EditTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

type RemoveTelnetInterfaceRequest struct {
	EthernetInterfaceId uint32 `protobuf:"varint,1,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
}

func (m *RemoveTelnetInterfaceRequest) Reset()                    { *m = RemoveTelnetInterfaceRequest{} }
func (m *RemoveTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveTelnetInterfaceRequest) ProtoMessage()               {}
func (*RemoveTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *RemoveTelnetInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

type RemoveTelnetInterfaceResponse struct {
	State RemoveTelnetInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveTelnetInterfaceResponse_State" json:"state,omitempty"`
}

func (m *RemoveTelnetInterfaceResponse) Reset()                    { *m = RemoveTelnetInterfaceResponse{} }
func (m *RemoveTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveTelnetInterfaceResponse) ProtoMessage()               {}
func (*RemoveTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *RemoveTelnetInterfaceResponse) GetState() RemoveTelnetInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveTelnetInterfaceResponse_SUCCESS
}

type FetchTelnetInterfacesRequest struct {
	Offset uint32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *FetchTelnetInterfacesRequest) Reset()                    { *m = FetchTelnetInterfacesRequest{} }
func (m *FetchTelnetInterfacesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchTelnetInterfacesRequest) ProtoMessage()               {}
func (*FetchTelnetInterfacesRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *FetchTelnetInterfacesRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FetchTelnetInterfacesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type FetchTelnetInterfaceByIdRequest struct {
}

func (m *FetchTelnetInterfaceByIdRequest) Reset()                    { *m = FetchTelnetInterfaceByIdRequest{} }
func (m *FetchTelnetInterfaceByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchTelnetInterfaceByIdRequest) ProtoMessage()               {}
func (*FetchTelnetInterfaceByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{8} }

type FetchTelnetInterfaceByIdResponse struct {
}

func (m *FetchTelnetInterfaceByIdResponse) Reset()         { *m = FetchTelnetInterfaceByIdResponse{} }
func (m *FetchTelnetInterfaceByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTelnetInterfaceByIdResponse) ProtoMessage()    {}
func (*FetchTelnetInterfaceByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{9}
}

func init() {
	proto.RegisterType((*TelnetInterface)(nil), "WompattiService.TelnetInterface")
	proto.RegisterType((*CreateTelnetInterfaceRequest)(nil), "WompattiService.CreateTelnetInterfaceRequest")
	proto.RegisterType((*CreateTelnetInterfaceResponse)(nil), "WompattiService.CreateTelnetInterfaceResponse")
	proto.RegisterType((*EditTelnetInterfaceRequest)(nil), "WompattiService.EditTelnetInterfaceRequest")
	proto.RegisterType((*EditTelnetInterfaceResponse)(nil), "WompattiService.EditTelnetInterfaceResponse")
	proto.RegisterType((*RemoveTelnetInterfaceRequest)(nil), "WompattiService.RemoveTelnetInterfaceRequest")
	proto.RegisterType((*RemoveTelnetInterfaceResponse)(nil), "WompattiService.RemoveTelnetInterfaceResponse")
	proto.RegisterType((*FetchTelnetInterfacesRequest)(nil), "WompattiService.FetchTelnetInterfacesRequest")
	proto.RegisterType((*FetchTelnetInterfaceByIdRequest)(nil), "WompattiService.FetchTelnetInterfaceByIdRequest")
	proto.RegisterType((*FetchTelnetInterfaceByIdResponse)(nil), "WompattiService.FetchTelnetInterfaceByIdResponse")
	proto.RegisterEnum("WompattiService.RemoveTelnetInterfaceResponse_State", RemoveTelnetInterfaceResponse_State_name, RemoveTelnetInterfaceResponse_State_value)
}

func init() { proto.RegisterFile("telnet_interface.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x6f, 0x4b, 0x02, 0x41,
	0x10, 0xc6, 0xbb, 0x2b, 0x0d, 0x27, 0xfc, 0xc3, 0x16, 0x22, 0xa5, 0x68, 0xdb, 0x1b, 0x5f, 0x1d,
	0x51, 0x7d, 0x02, 0x4d, 0xc1, 0x08, 0x8d, 0x3b, 0xa5, 0x97, 0x72, 0x79, 0x23, 0x2e, 0xa8, 0xbb,
	0xed, 0x4e, 0x42, 0xdf, 0xa2, 0x8f, 0x1c, 0xed, 0x9d, 0x21, 0x76, 0x27, 0xf4, 0xee, 0x9e, 0x9b,
	0x99, 0xdf, 0x33, 0x0f, 0xb3, 0x50, 0x25, 0x5c, 0xae, 0x91, 0xa6, 0x62, 0x4d, 0xa8, 0xe7, 0xe1,
	0x0c, 0x3d, 0xa5, 0x25, 0x49, 0x56, 0x7e, 0x95, 0x2b, 0x15, 0x12, 0x89, 0x00, 0xf5, 0x46, 0xcc,
	0x90, 0xf7, 0xa0, 0x3c, 0xb6, 0xad, 0x83, 0x6d, 0x27, 0x2b, 0x81, 0x2b, 0xa2, 0x9a, 0xd3, 0x72,
	0xda, 0x45, 0xdf, 0x15, 0x91, 0xd5, 0xaa, 0xe6, 0xb6, 0x9c, 0x76, 0xc1, 0x77, 0x85, 0x62, 0x0c,
	0x4e, 0x94, 0xd4, 0x54, 0x3b, 0xb6, 0x7f, 0xec, 0x37, 0xef, 0x40, 0xbd, 0xab, 0x31, 0x24, 0xdc,
	0x83, 0xf9, 0xf8, 0xfe, 0x81, 0x86, 0x12, 0x86, 0xf3, 0x87, 0xe1, 0xee, 0x30, 0x9a, 0xd0, 0xc8,
	0x60, 0x18, 0x25, 0xd7, 0x06, 0xf9, 0x0b, 0x5c, 0xf6, 0x22, 0x41, 0x07, 0x2c, 0xfe, 0xbb, 0x76,
	0x03, 0xae, 0x52, 0x89, 0xbf, 0x86, 0x75, 0x1f, 0x57, 0x72, 0x93, 0x95, 0xea, 0x16, 0xce, 0x91,
	0x16, 0xa8, 0x77, 0x6b, 0x83, 0xed, 0x0e, 0x69, 0x25, 0xfe, 0xe5, 0x40, 0x23, 0x03, 0x19, 0x7b,
	0xb2, 0x27, 0xc8, 0x19, 0x0a, 0x09, 0x2d, 0xa5, 0x74, 0xf7, 0xe0, 0xed, 0x5d, 0xcc, 0x3b, 0x38,
	0xee, 0x05, 0x3f, 0xb3, 0x7e, 0x8c, 0xe0, 0x37, 0x90, 0xb3, 0x9a, 0x9d, 0xc1, 0x69, 0x30, 0xe9,
	0x76, 0x7b, 0x41, 0x50, 0x39, 0x62, 0x45, 0x28, 0x0c, 0x47, 0xe3, 0x69, 0x7f, 0x34, 0x19, 0x3e,
	0x56, 0x1c, 0xfe, 0x0c, 0xf5, 0x3e, 0xd2, 0x6c, 0xb1, 0x47, 0x34, 0xdb, 0x90, 0x55, 0xc8, 0xcb,
	0xf9, 0xdc, 0x20, 0x25, 0xb9, 0x12, 0xc5, 0x2e, 0x20, 0xb7, 0x14, 0x2b, 0x11, 0xdf, 0xb0, 0xe8,
	0xc7, 0x82, 0x5f, 0x43, 0x33, 0x8d, 0xd6, 0xf9, 0x1c, 0x44, 0x09, 0x90, 0x73, 0x68, 0x65, 0xb7,
	0xc4, 0x31, 0xde, 0xf2, 0xf6, 0xb9, 0xde, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x08, 0xcb, 0x2b,
	0x84, 0xc8, 0x02, 0x00, 0x00,
}
