// Code generated by protoc-gen-go.
// source: telnet_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EditTelnetInterfaceResponse_State int32

const (
	EditTelnetInterfaceResponse_SUCCESS   EditTelnetInterfaceResponse_State = 0
	EditTelnetInterfaceResponse_NOT_FOUND EditTelnetInterfaceResponse_State = 1
)

var EditTelnetInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditTelnetInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditTelnetInterfaceResponse_State) String() string {
	return proto.EnumName(EditTelnetInterfaceResponse_State_name, int32(x))
}
func (EditTelnetInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{9, 0}
}

type RemoveTelnetInterfaceResponse_State int32

const (
	RemoveTelnetInterfaceResponse_SUCCESS   RemoveTelnetInterfaceResponse_State = 0
	RemoveTelnetInterfaceResponse_NOT_FOUND RemoveTelnetInterfaceResponse_State = 1
)

var RemoveTelnetInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveTelnetInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveTelnetInterfaceResponse_State) String() string {
	return proto.EnumName(RemoveTelnetInterfaceResponse_State_name, int32(x))
}
func (RemoveTelnetInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{11, 0}
}

type TelnetInterface struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
}

func (m *TelnetInterface) Reset()                    { *m = TelnetInterface{} }
func (m *TelnetInterface) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterface) ProtoMessage()               {}
func (*TelnetInterface) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *TelnetInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TelnetInterface) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TelnetInterface) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type TelnetInterfacesConnection struct {
	PageInfo   *PageInfo               `protobuf:"bytes,1,opt,name=pageInfo" json:"pageInfo,omitempty"`
	Edges      []*TelnetInterfacesEdge `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32                  `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *TelnetInterfacesConnection) Reset()                    { *m = TelnetInterfacesConnection{} }
func (m *TelnetInterfacesConnection) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterfacesConnection) ProtoMessage()               {}
func (*TelnetInterfacesConnection) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *TelnetInterfacesConnection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *TelnetInterfacesConnection) GetEdges() []*TelnetInterfacesEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *TelnetInterfacesConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type TelnetInterfacesEdge struct {
	Node   *TelnetInterface `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32           `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *TelnetInterfacesEdge) Reset()                    { *m = TelnetInterfacesEdge{} }
func (m *TelnetInterfacesEdge) String() string            { return proto.CompactTextString(m) }
func (*TelnetInterfacesEdge) ProtoMessage()               {}
func (*TelnetInterfacesEdge) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *TelnetInterfacesEdge) GetNode() *TelnetInterface {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *TelnetInterfacesEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type FetchTelnetInterfacesRequest struct {
	After  uint32 `protobuf:"varint,1,opt,name=after" json:"after,omitempty"`
	Before uint32 `protobuf:"varint,2,opt,name=before" json:"before,omitempty"`
	First  uint32 `protobuf:"varint,3,opt,name=first" json:"first,omitempty"`
	Last   uint32 `protobuf:"varint,4,opt,name=last" json:"last,omitempty"`
}

func (m *FetchTelnetInterfacesRequest) Reset()                    { *m = FetchTelnetInterfacesRequest{} }
func (m *FetchTelnetInterfacesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchTelnetInterfacesRequest) ProtoMessage()               {}
func (*FetchTelnetInterfacesRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *FetchTelnetInterfacesRequest) GetAfter() uint32 {
	if m != nil {
		return m.After
	}
	return 0
}

func (m *FetchTelnetInterfacesRequest) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

func (m *FetchTelnetInterfacesRequest) GetFirst() uint32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *FetchTelnetInterfacesRequest) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type FetchTelnetInterfaceByIdRequest struct {
	TelnetInterfaceId []uint32 `protobuf:"varint,1,rep,packed,name=telnetInterfaceId" json:"telnetInterfaceId,omitempty"`
}

func (m *FetchTelnetInterfaceByIdRequest) Reset()                    { *m = FetchTelnetInterfaceByIdRequest{} }
func (m *FetchTelnetInterfaceByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchTelnetInterfaceByIdRequest) ProtoMessage()               {}
func (*FetchTelnetInterfaceByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *FetchTelnetInterfaceByIdRequest) GetTelnetInterfaceId() []uint32 {
	if m != nil {
		return m.TelnetInterfaceId
	}
	return nil
}

type FetchTelnetInterfaceByIdResponse struct {
	TelnetInterfaces []*TelnetInterface `protobuf:"bytes,1,rep,name=telnetInterfaces" json:"telnetInterfaces,omitempty"`
}

func (m *FetchTelnetInterfaceByIdResponse) Reset()         { *m = FetchTelnetInterfaceByIdResponse{} }
func (m *FetchTelnetInterfaceByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTelnetInterfaceByIdResponse) ProtoMessage()    {}
func (*FetchTelnetInterfaceByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{5}
}

func (m *FetchTelnetInterfaceByIdResponse) GetTelnetInterfaces() []*TelnetInterface {
	if m != nil {
		return m.TelnetInterfaces
	}
	return nil
}

type CreateTelnetInterfaceRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *CreateTelnetInterfaceRequest) Reset()                    { *m = CreateTelnetInterfaceRequest{} }
func (m *CreateTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTelnetInterfaceRequest) ProtoMessage()               {}
func (*CreateTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *CreateTelnetInterfaceRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateTelnetInterfaceRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type CreateTelnetInterfaceResponse struct {
	TelnetInterface *TelnetInterface `protobuf:"bytes,1,opt,name=telnetInterface" json:"telnetInterface,omitempty"`
}

func (m *CreateTelnetInterfaceResponse) Reset()                    { *m = CreateTelnetInterfaceResponse{} }
func (m *CreateTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTelnetInterfaceResponse) ProtoMessage()               {}
func (*CreateTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *CreateTelnetInterfaceResponse) GetTelnetInterface() *TelnetInterface {
	if m != nil {
		return m.TelnetInterface
	}
	return nil
}

type EditTelnetInterfaceRequest struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
}

func (m *EditTelnetInterfaceRequest) Reset()                    { *m = EditTelnetInterfaceRequest{} }
func (m *EditTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EditTelnetInterfaceRequest) ProtoMessage()               {}
func (*EditTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{8} }

func (m *EditTelnetInterfaceRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditTelnetInterfaceRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *EditTelnetInterfaceRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type EditTelnetInterfaceResponse struct {
	State           EditTelnetInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditTelnetInterfaceResponse_State" json:"state,omitempty"`
	TelnetInterface *TelnetInterface                  `protobuf:"bytes,2,opt,name=telnetInterface" json:"telnetInterface,omitempty"`
}

func (m *EditTelnetInterfaceResponse) Reset()                    { *m = EditTelnetInterfaceResponse{} }
func (m *EditTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EditTelnetInterfaceResponse) ProtoMessage()               {}
func (*EditTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{9} }

func (m *EditTelnetInterfaceResponse) GetState() EditTelnetInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return EditTelnetInterfaceResponse_SUCCESS
}

func (m *EditTelnetInterfaceResponse) GetTelnetInterface() *TelnetInterface {
	if m != nil {
		return m.TelnetInterface
	}
	return nil
}

type RemoveTelnetInterfaceRequest struct {
	EthernetInterfaceId uint32 `protobuf:"varint,1,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
}

func (m *RemoveTelnetInterfaceRequest) Reset()                    { *m = RemoveTelnetInterfaceRequest{} }
func (m *RemoveTelnetInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveTelnetInterfaceRequest) ProtoMessage()               {}
func (*RemoveTelnetInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{10} }

func (m *RemoveTelnetInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

type RemoveTelnetInterfaceResponse struct {
	State RemoveTelnetInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveTelnetInterfaceResponse_State" json:"state,omitempty"`
}

func (m *RemoveTelnetInterfaceResponse) Reset()                    { *m = RemoveTelnetInterfaceResponse{} }
func (m *RemoveTelnetInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveTelnetInterfaceResponse) ProtoMessage()               {}
func (*RemoveTelnetInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{11} }

func (m *RemoveTelnetInterfaceResponse) GetState() RemoveTelnetInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveTelnetInterfaceResponse_SUCCESS
}

func init() {
	proto.RegisterType((*TelnetInterface)(nil), "WompattiService.TelnetInterface")
	proto.RegisterType((*TelnetInterfacesConnection)(nil), "WompattiService.TelnetInterfacesConnection")
	proto.RegisterType((*TelnetInterfacesEdge)(nil), "WompattiService.TelnetInterfacesEdge")
	proto.RegisterType((*FetchTelnetInterfacesRequest)(nil), "WompattiService.FetchTelnetInterfacesRequest")
	proto.RegisterType((*FetchTelnetInterfaceByIdRequest)(nil), "WompattiService.FetchTelnetInterfaceByIdRequest")
	proto.RegisterType((*FetchTelnetInterfaceByIdResponse)(nil), "WompattiService.FetchTelnetInterfaceByIdResponse")
	proto.RegisterType((*CreateTelnetInterfaceRequest)(nil), "WompattiService.CreateTelnetInterfaceRequest")
	proto.RegisterType((*CreateTelnetInterfaceResponse)(nil), "WompattiService.CreateTelnetInterfaceResponse")
	proto.RegisterType((*EditTelnetInterfaceRequest)(nil), "WompattiService.EditTelnetInterfaceRequest")
	proto.RegisterType((*EditTelnetInterfaceResponse)(nil), "WompattiService.EditTelnetInterfaceResponse")
	proto.RegisterType((*RemoveTelnetInterfaceRequest)(nil), "WompattiService.RemoveTelnetInterfaceRequest")
	proto.RegisterType((*RemoveTelnetInterfaceResponse)(nil), "WompattiService.RemoveTelnetInterfaceResponse")
	proto.RegisterEnum("WompattiService.EditTelnetInterfaceResponse_State", EditTelnetInterfaceResponse_State_name, EditTelnetInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveTelnetInterfaceResponse_State", RemoveTelnetInterfaceResponse_State_name, RemoveTelnetInterfaceResponse_State_value)
}

func init() { proto.RegisterFile("telnet_interface.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdf, 0x6e, 0x12, 0x4d,
	0x14, 0xff, 0x76, 0x81, 0x7e, 0xf6, 0x10, 0x0a, 0x8e, 0x4d, 0x83, 0x48, 0x95, 0xac, 0x31, 0xe1,
	0xc2, 0x10, 0x83, 0xf5, 0xca, 0xbb, 0x22, 0x8d, 0x18, 0x53, 0xc8, 0xd0, 0xc6, 0x4b, 0xb2, 0x65,
	0xcf, 0xd2, 0x89, 0x74, 0x66, 0x9d, 0x39, 0x90, 0xf8, 0x16, 0x3e, 0x8a, 0x8f, 0xe3, 0xe3, 0x98,
	0x9d, 0x5d, 0x9a, 0xb2, 0x0b, 0x88, 0xde, 0xed, 0x99, 0x39, 0xbf, 0x3f, 0xf3, 0x3b, 0x07, 0xe0,
	0x84, 0x70, 0x2e, 0x91, 0x26, 0x42, 0x12, 0xea, 0xd0, 0x9f, 0x62, 0x27, 0xd2, 0x8a, 0x14, 0xab,
	0x7e, 0x51, 0x77, 0x91, 0x4f, 0x24, 0xc6, 0xa8, 0x97, 0x62, 0x8a, 0x8d, 0x6a, 0xe4, 0xcf, 0x70,
	0x22, 0x64, 0xa8, 0x92, 0x0e, 0xaf, 0x0f, 0xd5, 0x2b, 0x8b, 0x1d, 0xac, 0xa0, 0xec, 0x08, 0x5c,
	0x11, 0xd4, 0x9d, 0x96, 0xd3, 0xae, 0x70, 0x57, 0x04, 0xb6, 0x8e, 0xea, 0x6e, 0xcb, 0x69, 0x1f,
	0x72, 0x57, 0x44, 0x8c, 0x41, 0x31, 0x52, 0x9a, 0xea, 0x05, 0x7b, 0x62, 0xbf, 0xbd, 0x9f, 0x0e,
	0x34, 0x32, 0x3c, 0xa6, 0xa7, 0xa4, 0xc4, 0x29, 0x09, 0x25, 0xd9, 0x3b, 0x78, 0x14, 0x0b, 0x0f,
	0x64, 0xa8, 0x2c, 0x71, 0xb9, 0xfb, 0xb4, 0x93, 0xb1, 0xd6, 0x19, 0xa5, 0x0d, 0xfc, 0xbe, 0x95,
	0xbd, 0x87, 0x12, 0x06, 0x33, 0x34, 0x75, 0xb7, 0x55, 0x68, 0x97, 0xbb, 0xaf, 0x72, 0x98, 0xac,
	0x64, 0x3f, 0x98, 0x21, 0x4f, 0x30, 0xec, 0x39, 0x00, 0x29, 0xf2, 0xe7, 0x3d, 0xb5, 0x90, 0x89,
	0xd9, 0x0a, 0x7f, 0x70, 0xe2, 0x05, 0x70, 0xbc, 0x09, 0xce, 0xce, 0xa0, 0x28, 0x55, 0x80, 0xa9,
	0xcf, 0xd6, 0x9f, 0x34, 0xb9, 0xed, 0x66, 0x27, 0x70, 0x30, 0x5d, 0x68, 0xa3, 0xb4, 0x0d, 0xaa,
	0xc2, 0xd3, 0xca, 0x5b, 0x42, 0xf3, 0x02, 0x69, 0x7a, 0x9b, 0x95, 0xe2, 0xf8, 0x6d, 0x81, 0x86,
	0xd8, 0x31, 0x94, 0xfc, 0x90, 0x50, 0xa7, 0x79, 0x27, 0x45, 0xcc, 0x76, 0x83, 0xa1, 0xd2, 0xb8,
	0x62, 0x4b, 0xaa, 0xb8, 0x3b, 0x14, 0xda, 0xac, 0x9e, 0x93, 0x14, 0xf1, 0x40, 0xe6, 0xbe, 0xa1,
	0x7a, 0xd1, 0x1e, 0xda, 0x6f, 0x6f, 0x08, 0x2f, 0x36, 0xe9, 0x9e, 0x7f, 0x1f, 0x04, 0x2b, 0xe9,
	0xd7, 0xf0, 0x98, 0xd6, 0x6f, 0x07, 0xf1, 0xd8, 0x0b, 0xed, 0x0a, 0xcf, 0x5f, 0x78, 0x11, 0xb4,
	0xb6, 0x13, 0x9a, 0x48, 0x49, 0x83, 0xec, 0x33, 0xd4, 0x32, 0x40, 0x63, 0x09, 0xf7, 0x89, 0x31,
	0x87, 0xf4, 0xce, 0xa1, 0xd9, 0xd3, 0xe8, 0x13, 0x66, 0x5b, 0x53, 0xff, 0xc9, 0x5e, 0x3a, 0xb9,
	0xbd, 0x74, 0x1f, 0xec, 0xe5, 0x57, 0x38, 0xdd, 0xc2, 0x91, 0x5a, 0xfe, 0x04, 0xd5, 0x8c, 0xf0,
	0xde, 0x83, 0xcf, 0x02, 0xbd, 0x11, 0x34, 0xfa, 0x81, 0xa0, 0x1d, 0x76, 0xff, 0xf6, 0x67, 0xf5,
	0xcb, 0x81, 0x67, 0x1b, 0x29, 0x53, 0xf7, 0x1f, 0xa1, 0x64, 0xc8, 0xa7, 0xc4, 0xf3, 0x51, 0xb7,
	0x9b, 0xf3, 0xbc, 0x03, 0xdc, 0x19, 0xc7, 0x48, 0x9e, 0x10, 0x6c, 0xca, 0xc1, 0xfd, 0xd7, 0x1c,
	0x5e, 0x42, 0xc9, 0x72, 0xb3, 0x32, 0xfc, 0x3f, 0xbe, 0xee, 0xf5, 0xfa, 0xe3, 0x71, 0xed, 0x3f,
	0x56, 0x81, 0xc3, 0xcb, 0xe1, 0xd5, 0xe4, 0x62, 0x78, 0x7d, 0xf9, 0xa1, 0xe6, 0x78, 0x23, 0x68,
	0x72, 0xbc, 0x53, 0xcb, 0x6d, 0xd3, 0x7d, 0x03, 0x4f, 0x90, 0x6e, 0x51, 0xe7, 0xf6, 0x33, 0xce,
	0x6f, 0xd3, 0x95, 0xf7, 0xc3, 0x81, 0xd3, 0x2d, 0x94, 0xf7, 0xc3, 0x5e, 0x8b, 0xeb, 0x2c, 0xf7,
	0xb4, 0x9d, 0xf0, 0xb5, 0xc0, 0xf6, 0x7a, 0xe4, 0xcd, 0x81, 0xfd, 0x93, 0x7d, 0xfb, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x22, 0xe2, 0xd5, 0x0e, 0xa0, 0x05, 0x00, 0x00,
}
