// Code generated by protoc-gen-go.
// source: wol_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateWolInterfaceResponse_State int32

const (
	CreateWolInterfaceResponse_SUCCESS   CreateWolInterfaceResponse_State = 0
	CreateWolInterfaceResponse_NOT_FOUND CreateWolInterfaceResponse_State = 1
)

var CreateWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateWolInterfaceResponse_State) String() string {
	return proto.EnumName(CreateWolInterfaceResponse_State_name, int32(x))
}
func (CreateWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor9, []int{2, 0}
}

type EditWolInterfaceResponse_State int32

const (
	EditWolInterfaceResponse_SUCCESS   EditWolInterfaceResponse_State = 0
	EditWolInterfaceResponse_NOT_FOUND EditWolInterfaceResponse_State = 1
)

var EditWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditWolInterfaceResponse_State) String() string {
	return proto.EnumName(EditWolInterfaceResponse_State_name, int32(x))
}
func (EditWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor9, []int{4, 0}
}

type RemoveWolInterfaceResponse_State int32

const (
	RemoveWolInterfaceResponse_SUCCESS   RemoveWolInterfaceResponse_State = 0
	RemoveWolInterfaceResponse_NOT_FOUND RemoveWolInterfaceResponse_State = 1
)

var RemoveWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveWolInterfaceResponse_State) String() string {
	return proto.EnumName(RemoveWolInterfaceResponse_State_name, int32(x))
}
func (RemoveWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor9, []int{6, 0}
}

type ExecuteWolInterfaceResponse_State int32

const (
	ExecuteWolInterfaceResponse_SUCCESS   ExecuteWolInterfaceResponse_State = 0
	ExecuteWolInterfaceResponse_NOT_FOUND ExecuteWolInterfaceResponse_State = 1
)

var ExecuteWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var ExecuteWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x ExecuteWolInterfaceResponse_State) String() string {
	return proto.EnumName(ExecuteWolInterfaceResponse_State_name, int32(x))
}
func (ExecuteWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor9, []int{8, 0}
}

type WolInterface struct {
	Id                  uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *WolInterface) Reset()                    { *m = WolInterface{} }
func (m *WolInterface) String() string            { return proto.CompactTextString(m) }
func (*WolInterface) ProtoMessage()               {}
func (*WolInterface) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *WolInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WolInterface) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *WolInterface) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type CreateWolInterfaceRequest struct {
	ComputerId          uint32 `protobuf:"varint,1,opt,name=computerId" json:"computerId,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *CreateWolInterfaceRequest) Reset()                    { *m = CreateWolInterfaceRequest{} }
func (m *CreateWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateWolInterfaceRequest) ProtoMessage()               {}
func (*CreateWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *CreateWolInterfaceRequest) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

func (m *CreateWolInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *CreateWolInterfaceRequest) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type CreateWolInterfaceResponse struct {
	State        CreateWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateWolInterfaceResponse_State" json:"state,omitempty"`
	WolInterface *WolInterface                    `protobuf:"bytes,2,opt,name=wolInterface" json:"wolInterface,omitempty"`
}

func (m *CreateWolInterfaceResponse) Reset()                    { *m = CreateWolInterfaceResponse{} }
func (m *CreateWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateWolInterfaceResponse) ProtoMessage()               {}
func (*CreateWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *CreateWolInterfaceResponse) GetState() CreateWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return CreateWolInterfaceResponse_SUCCESS
}

func (m *CreateWolInterfaceResponse) GetWolInterface() *WolInterface {
	if m != nil {
		return m.WolInterface
	}
	return nil
}

type EditWolInterfaceRequest struct {
	WolInterfaceId      uint32 `protobuf:"varint,1,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *EditWolInterfaceRequest) Reset()                    { *m = EditWolInterfaceRequest{} }
func (m *EditWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EditWolInterfaceRequest) ProtoMessage()               {}
func (*EditWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *EditWolInterfaceRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

func (m *EditWolInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *EditWolInterfaceRequest) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type EditWolInterfaceResponse struct {
	State        EditWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditWolInterfaceResponse_State" json:"state,omitempty"`
	WolInterface *WolInterface                  `protobuf:"bytes,2,opt,name=wolInterface" json:"wolInterface,omitempty"`
}

func (m *EditWolInterfaceResponse) Reset()                    { *m = EditWolInterfaceResponse{} }
func (m *EditWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EditWolInterfaceResponse) ProtoMessage()               {}
func (*EditWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

func (m *EditWolInterfaceResponse) GetState() EditWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return EditWolInterfaceResponse_SUCCESS
}

func (m *EditWolInterfaceResponse) GetWolInterface() *WolInterface {
	if m != nil {
		return m.WolInterface
	}
	return nil
}

type RemoveWolInterfaceRequest struct {
	WolInterfaceId uint32 `protobuf:"varint,1,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
}

func (m *RemoveWolInterfaceRequest) Reset()                    { *m = RemoveWolInterfaceRequest{} }
func (m *RemoveWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveWolInterfaceRequest) ProtoMessage()               {}
func (*RemoveWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

func (m *RemoveWolInterfaceRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

type RemoveWolInterfaceResponse struct {
	State RemoveWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveWolInterfaceResponse_State" json:"state,omitempty"`
}

func (m *RemoveWolInterfaceResponse) Reset()                    { *m = RemoveWolInterfaceResponse{} }
func (m *RemoveWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveWolInterfaceResponse) ProtoMessage()               {}
func (*RemoveWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

func (m *RemoveWolInterfaceResponse) GetState() RemoveWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveWolInterfaceResponse_SUCCESS
}

type ExecuteWolInterfaceRequest struct {
	WolInterfaceId uint32 `protobuf:"varint,1,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
}

func (m *ExecuteWolInterfaceRequest) Reset()                    { *m = ExecuteWolInterfaceRequest{} }
func (m *ExecuteWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteWolInterfaceRequest) ProtoMessage()               {}
func (*ExecuteWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{7} }

func (m *ExecuteWolInterfaceRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

type ExecuteWolInterfaceResponse struct {
	State ExecuteWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.ExecuteWolInterfaceResponse_State" json:"state,omitempty"`
}

func (m *ExecuteWolInterfaceResponse) Reset()                    { *m = ExecuteWolInterfaceResponse{} }
func (m *ExecuteWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteWolInterfaceResponse) ProtoMessage()               {}
func (*ExecuteWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{8} }

func (m *ExecuteWolInterfaceResponse) GetState() ExecuteWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return ExecuteWolInterfaceResponse_SUCCESS
}

type FetchWolInterfaceByIdRequest struct {
	WolInterfaceIdt []uint32 `protobuf:"varint,1,rep,packed,name=wolInterfaceIdt" json:"wolInterfaceIdt,omitempty"`
}

func (m *FetchWolInterfaceByIdRequest) Reset()                    { *m = FetchWolInterfaceByIdRequest{} }
func (m *FetchWolInterfaceByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchWolInterfaceByIdRequest) ProtoMessage()               {}
func (*FetchWolInterfaceByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{9} }

func (m *FetchWolInterfaceByIdRequest) GetWolInterfaceIdt() []uint32 {
	if m != nil {
		return m.WolInterfaceIdt
	}
	return nil
}

type FetchWolInterfaceByIdResponse struct {
	WolInterfaces []*WolInterface `protobuf:"bytes,1,rep,name=wolInterfaces" json:"wolInterfaces,omitempty"`
}

func (m *FetchWolInterfaceByIdResponse) Reset()                    { *m = FetchWolInterfaceByIdResponse{} }
func (m *FetchWolInterfaceByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchWolInterfaceByIdResponse) ProtoMessage()               {}
func (*FetchWolInterfaceByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{10} }

func (m *FetchWolInterfaceByIdResponse) GetWolInterfaces() []*WolInterface {
	if m != nil {
		return m.WolInterfaces
	}
	return nil
}

func init() {
	proto.RegisterType((*WolInterface)(nil), "WompattiService.WolInterface")
	proto.RegisterType((*CreateWolInterfaceRequest)(nil), "WompattiService.CreateWolInterfaceRequest")
	proto.RegisterType((*CreateWolInterfaceResponse)(nil), "WompattiService.CreateWolInterfaceResponse")
	proto.RegisterType((*EditWolInterfaceRequest)(nil), "WompattiService.EditWolInterfaceRequest")
	proto.RegisterType((*EditWolInterfaceResponse)(nil), "WompattiService.EditWolInterfaceResponse")
	proto.RegisterType((*RemoveWolInterfaceRequest)(nil), "WompattiService.RemoveWolInterfaceRequest")
	proto.RegisterType((*RemoveWolInterfaceResponse)(nil), "WompattiService.RemoveWolInterfaceResponse")
	proto.RegisterType((*ExecuteWolInterfaceRequest)(nil), "WompattiService.ExecuteWolInterfaceRequest")
	proto.RegisterType((*ExecuteWolInterfaceResponse)(nil), "WompattiService.ExecuteWolInterfaceResponse")
	proto.RegisterType((*FetchWolInterfaceByIdRequest)(nil), "WompattiService.FetchWolInterfaceByIdRequest")
	proto.RegisterType((*FetchWolInterfaceByIdResponse)(nil), "WompattiService.FetchWolInterfaceByIdResponse")
	proto.RegisterEnum("WompattiService.CreateWolInterfaceResponse_State", CreateWolInterfaceResponse_State_name, CreateWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.EditWolInterfaceResponse_State", EditWolInterfaceResponse_State_name, EditWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveWolInterfaceResponse_State", RemoveWolInterfaceResponse_State_name, RemoveWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.ExecuteWolInterfaceResponse_State", ExecuteWolInterfaceResponse_State_name, ExecuteWolInterfaceResponse_State_value)
}

func init() { proto.RegisterFile("wol_interface.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x41, 0x8f, 0x9a, 0x50,
	0x10, 0xc7, 0xfb, 0x34, 0xb6, 0xe9, 0x28, 0x6a, 0x9e, 0x87, 0xa2, 0xad, 0x8d, 0xa1, 0x49, 0xc3,
	0x89, 0xb6, 0xf6, 0x13, 0xb4, 0x88, 0x95, 0x8b, 0x26, 0x50, 0xe3, 0xd1, 0x20, 0x4c, 0x23, 0x89,
	0xf8, 0x28, 0x3c, 0xb5, 0x3d, 0xed, 0x69, 0x2f, 0x9b, 0xfd, 0x62, 0x7b, 0xd8, 0xef, 0xb4, 0x91,
	0x55, 0x03, 0x02, 0x59, 0xb3, 0x9a, 0xec, 0x8d, 0x0c, 0xf3, 0xff, 0xcf, 0xfc, 0x7f, 0x4c, 0x80,
	0xc6, 0x86, 0x2d, 0xa6, 0xee, 0x92, 0x63, 0xf0, 0xc7, 0xb2, 0x51, 0xf1, 0x03, 0xc6, 0x19, 0xad,
	0x4d, 0x98, 0xe7, 0x5b, 0x9c, 0xbb, 0x26, 0x06, 0x6b, 0xd7, 0x46, 0x69, 0x06, 0x95, 0x09, 0x5b,
	0xe8, 0xfb, 0x36, 0x5a, 0x85, 0x82, 0xeb, 0x88, 0xa4, 0x43, 0x64, 0xc1, 0x28, 0xb8, 0x0e, 0xfd,
	0x0a, 0x0d, 0xe4, 0x73, 0x0c, 0x96, 0xc8, 0x0f, 0x4d, 0xba, 0x23, 0x16, 0xa2, 0x86, 0xac, 0x57,
	0xb4, 0x0e, 0x45, 0xcf, 0xb2, 0xc5, 0x62, 0x87, 0xc8, 0x15, 0x63, 0xfb, 0x28, 0x5d, 0x41, 0x53,
	0x0d, 0xd0, 0xe2, 0x18, 0x9f, 0x64, 0xe0, 0xdf, 0x15, 0x86, 0x9c, 0x7e, 0x04, 0xb0, 0x99, 0xe7,
	0xaf, 0x38, 0x06, 0xfa, 0x7e, 0x70, 0xac, 0x72, 0x91, 0x05, 0xee, 0x09, 0xb4, 0xb2, 0x36, 0x08,
	0x7d, 0xb6, 0x0c, 0x91, 0xfe, 0x82, 0x52, 0xc8, 0x2d, 0x8e, 0xd1, 0xf4, 0x6a, 0xf7, 0x9b, 0x72,
	0x04, 0x49, 0xc9, 0xd7, 0x2a, 0xe6, 0x56, 0x68, 0x3c, 0xea, 0xe9, 0x0f, 0xa8, 0x6c, 0x62, 0x4d,
	0xd1, 0x92, 0xe5, 0x6e, 0x3b, 0xe5, 0x97, 0x70, 0x4a, 0x48, 0xa4, 0x4f, 0x50, 0x8a, 0x2c, 0x69,
	0x19, 0xde, 0x98, 0x63, 0x55, 0xd5, 0x4c, 0xb3, 0xfe, 0x8a, 0x0a, 0xf0, 0x76, 0x38, 0xfa, 0x3d,
	0xed, 0x8f, 0xc6, 0xc3, 0x5e, 0x9d, 0x48, 0xd7, 0x04, 0xde, 0x69, 0x8e, 0xcb, 0xb3, 0x78, 0x7e,
	0x86, 0x6a, 0xdc, 0xf0, 0xc0, 0xf4, 0xa8, 0x7a, 0x11, 0xae, 0x77, 0x04, 0xc4, 0xf4, 0x1e, 0x3b,
	0xaa, 0x5a, 0x92, 0xea, 0x97, 0x14, 0x85, 0x3c, 0xe5, 0xcb, 0x30, 0x55, 0xa1, 0x69, 0xa0, 0xc7,
	0xd6, 0x78, 0x06, 0x54, 0xe9, 0x86, 0x40, 0x2b, 0xcb, 0xe5, 0xd4, 0x43, 0xcb, 0xd7, 0x26, 0xa0,
	0x9c, 0x96, 0xa8, 0x07, 0x2d, 0xed, 0x1f, 0xda, 0x2b, 0x7e, 0x56, 0xa4, 0x5b, 0x02, 0xef, 0x33,
	0x6d, 0x76, 0x99, 0x06, 0xc9, 0x4c, 0xdd, 0xf4, 0x67, 0xce, 0x17, 0x3f, 0x23, 0xd4, 0x00, 0x3e,
	0xf4, 0x91, 0xdb, 0xf3, 0xb8, 0xdd, 0xcf, 0xff, 0xba, 0xb3, 0x8f, 0x25, 0x43, 0x2d, 0x19, 0x80,
	0x8b, 0xa4, 0x53, 0x94, 0x05, 0xe3, 0xb8, 0x2c, 0x39, 0xd0, 0xce, 0x71, 0xda, 0x25, 0x53, 0x41,
	0x88, 0x6b, 0xc2, 0xc8, 0xe8, 0xc9, 0xd3, 0x4b, 0x6a, 0x66, 0xaf, 0xa3, 0xff, 0xee, 0xf7, 0x87,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x9c, 0x23, 0xda, 0x8e, 0x05, 0x00, 0x00,
}
