// Code generated by protoc-gen-go.
// source: wol_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateWolInterfaceResponse_State int32

const (
	CreateWolInterfaceResponse_SUCCESS   CreateWolInterfaceResponse_State = 0
	CreateWolInterfaceResponse_NOT_FOUND CreateWolInterfaceResponse_State = 1
)

var CreateWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateWolInterfaceResponse_State) String() string {
	return proto.EnumName(CreateWolInterfaceResponse_State_name, int32(x))
}
func (CreateWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{2, 0}
}

type EditWolInterfaceResponse_State int32

const (
	EditWolInterfaceResponse_SUCCESS   EditWolInterfaceResponse_State = 0
	EditWolInterfaceResponse_NOT_FOUND EditWolInterfaceResponse_State = 1
)

var EditWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var EditWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x EditWolInterfaceResponse_State) String() string {
	return proto.EnumName(EditWolInterfaceResponse_State_name, int32(x))
}
func (EditWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{4, 0}
}

type RemoveWolInterfaceResponse_State int32

const (
	RemoveWolInterfaceResponse_SUCCESS   RemoveWolInterfaceResponse_State = 0
	RemoveWolInterfaceResponse_NOT_FOUND RemoveWolInterfaceResponse_State = 1
)

var RemoveWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var RemoveWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x RemoveWolInterfaceResponse_State) String() string {
	return proto.EnumName(RemoveWolInterfaceResponse_State_name, int32(x))
}
func (RemoveWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{6, 0}
}

type ExecuteWolInterfaceResponse_State int32

const (
	ExecuteWolInterfaceResponse_SUCCESS   ExecuteWolInterfaceResponse_State = 0
	ExecuteWolInterfaceResponse_NOT_FOUND ExecuteWolInterfaceResponse_State = 1
)

var ExecuteWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var ExecuteWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x ExecuteWolInterfaceResponse_State) String() string {
	return proto.EnumName(ExecuteWolInterfaceResponse_State_name, int32(x))
}
func (ExecuteWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{8, 0}
}

type FetchWolInterfaceByIdResponse_State int32

const (
	FetchWolInterfaceByIdResponse_SUCCESS   FetchWolInterfaceByIdResponse_State = 0
	FetchWolInterfaceByIdResponse_NOT_FOUND FetchWolInterfaceByIdResponse_State = 1
)

var FetchWolInterfaceByIdResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var FetchWolInterfaceByIdResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x FetchWolInterfaceByIdResponse_State) String() string {
	return proto.EnumName(FetchWolInterfaceByIdResponse_State_name, int32(x))
}
func (FetchWolInterfaceByIdResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor8, []int{10, 0}
}

type WolInterface struct {
	Id                  uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *WolInterface) Reset()                    { *m = WolInterface{} }
func (m *WolInterface) String() string            { return proto.CompactTextString(m) }
func (*WolInterface) ProtoMessage()               {}
func (*WolInterface) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *WolInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WolInterface) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *WolInterface) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type CreateWolInterfaceRequest struct {
	ComputerId          uint32 `protobuf:"varint,1,opt,name=computerId" json:"computerId,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *CreateWolInterfaceRequest) Reset()                    { *m = CreateWolInterfaceRequest{} }
func (m *CreateWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateWolInterfaceRequest) ProtoMessage()               {}
func (*CreateWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *CreateWolInterfaceRequest) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

func (m *CreateWolInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *CreateWolInterfaceRequest) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type CreateWolInterfaceResponse struct {
	State        CreateWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateWolInterfaceResponse_State" json:"state,omitempty"`
	WolInterface *WolInterface                    `protobuf:"bytes,2,opt,name=wolInterface" json:"wolInterface,omitempty"`
}

func (m *CreateWolInterfaceResponse) Reset()                    { *m = CreateWolInterfaceResponse{} }
func (m *CreateWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateWolInterfaceResponse) ProtoMessage()               {}
func (*CreateWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *CreateWolInterfaceResponse) GetState() CreateWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return CreateWolInterfaceResponse_SUCCESS
}

func (m *CreateWolInterfaceResponse) GetWolInterface() *WolInterface {
	if m != nil {
		return m.WolInterface
	}
	return nil
}

type EditWolInterfaceRequest struct {
	WolInterfaceId      uint32 `protobuf:"varint,1,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *EditWolInterfaceRequest) Reset()                    { *m = EditWolInterfaceRequest{} }
func (m *EditWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EditWolInterfaceRequest) ProtoMessage()               {}
func (*EditWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *EditWolInterfaceRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

func (m *EditWolInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *EditWolInterfaceRequest) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type EditWolInterfaceResponse struct {
	State        EditWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.EditWolInterfaceResponse_State" json:"state,omitempty"`
	WolInterface *WolInterface                  `protobuf:"bytes,2,opt,name=wolInterface" json:"wolInterface,omitempty"`
}

func (m *EditWolInterfaceResponse) Reset()                    { *m = EditWolInterfaceResponse{} }
func (m *EditWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EditWolInterfaceResponse) ProtoMessage()               {}
func (*EditWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *EditWolInterfaceResponse) GetState() EditWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return EditWolInterfaceResponse_SUCCESS
}

func (m *EditWolInterfaceResponse) GetWolInterface() *WolInterface {
	if m != nil {
		return m.WolInterface
	}
	return nil
}

type RemoveWolInterfaceRequest struct {
	WolInterfaceId uint32 `protobuf:"varint,1,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
}

func (m *RemoveWolInterfaceRequest) Reset()                    { *m = RemoveWolInterfaceRequest{} }
func (m *RemoveWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveWolInterfaceRequest) ProtoMessage()               {}
func (*RemoveWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *RemoveWolInterfaceRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

type RemoveWolInterfaceResponse struct {
	State RemoveWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.RemoveWolInterfaceResponse_State" json:"state,omitempty"`
}

func (m *RemoveWolInterfaceResponse) Reset()                    { *m = RemoveWolInterfaceResponse{} }
func (m *RemoveWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveWolInterfaceResponse) ProtoMessage()               {}
func (*RemoveWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *RemoveWolInterfaceResponse) GetState() RemoveWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return RemoveWolInterfaceResponse_SUCCESS
}

type ExecuteWolInterfaceRequest struct {
	WolInterfaceId uint32 `protobuf:"varint,1,opt,name=wolInterfaceId" json:"wolInterfaceId,omitempty"`
}

func (m *ExecuteWolInterfaceRequest) Reset()                    { *m = ExecuteWolInterfaceRequest{} }
func (m *ExecuteWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteWolInterfaceRequest) ProtoMessage()               {}
func (*ExecuteWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *ExecuteWolInterfaceRequest) GetWolInterfaceId() uint32 {
	if m != nil {
		return m.WolInterfaceId
	}
	return 0
}

type ExecuteWolInterfaceResponse struct {
	State ExecuteWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.ExecuteWolInterfaceResponse_State" json:"state,omitempty"`
}

func (m *ExecuteWolInterfaceResponse) Reset()                    { *m = ExecuteWolInterfaceResponse{} }
func (m *ExecuteWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteWolInterfaceResponse) ProtoMessage()               {}
func (*ExecuteWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{8} }

func (m *ExecuteWolInterfaceResponse) GetState() ExecuteWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return ExecuteWolInterfaceResponse_SUCCESS
}

type FetchWolInterfaceByIdRequest struct {
	WolInterfaceIdt []uint32 `protobuf:"varint,1,rep,packed,name=wolInterfaceIdt" json:"wolInterfaceIdt,omitempty"`
}

func (m *FetchWolInterfaceByIdRequest) Reset()                    { *m = FetchWolInterfaceByIdRequest{} }
func (m *FetchWolInterfaceByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchWolInterfaceByIdRequest) ProtoMessage()               {}
func (*FetchWolInterfaceByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{9} }

func (m *FetchWolInterfaceByIdRequest) GetWolInterfaceIdt() []uint32 {
	if m != nil {
		return m.WolInterfaceIdt
	}
	return nil
}

type FetchWolInterfaceByIdResponse struct {
	State        FetchWolInterfaceByIdResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.FetchWolInterfaceByIdResponse_State" json:"state,omitempty"`
	WolInterface *WolInterface                       `protobuf:"bytes,2,opt,name=wolInterface" json:"wolInterface,omitempty"`
}

func (m *FetchWolInterfaceByIdResponse) Reset()                    { *m = FetchWolInterfaceByIdResponse{} }
func (m *FetchWolInterfaceByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchWolInterfaceByIdResponse) ProtoMessage()               {}
func (*FetchWolInterfaceByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{10} }

func (m *FetchWolInterfaceByIdResponse) GetState() FetchWolInterfaceByIdResponse_State {
	if m != nil {
		return m.State
	}
	return FetchWolInterfaceByIdResponse_SUCCESS
}

func (m *FetchWolInterfaceByIdResponse) GetWolInterface() *WolInterface {
	if m != nil {
		return m.WolInterface
	}
	return nil
}

func init() {
	proto.RegisterType((*WolInterface)(nil), "WompattiService.WolInterface")
	proto.RegisterType((*CreateWolInterfaceRequest)(nil), "WompattiService.CreateWolInterfaceRequest")
	proto.RegisterType((*CreateWolInterfaceResponse)(nil), "WompattiService.CreateWolInterfaceResponse")
	proto.RegisterType((*EditWolInterfaceRequest)(nil), "WompattiService.EditWolInterfaceRequest")
	proto.RegisterType((*EditWolInterfaceResponse)(nil), "WompattiService.EditWolInterfaceResponse")
	proto.RegisterType((*RemoveWolInterfaceRequest)(nil), "WompattiService.RemoveWolInterfaceRequest")
	proto.RegisterType((*RemoveWolInterfaceResponse)(nil), "WompattiService.RemoveWolInterfaceResponse")
	proto.RegisterType((*ExecuteWolInterfaceRequest)(nil), "WompattiService.ExecuteWolInterfaceRequest")
	proto.RegisterType((*ExecuteWolInterfaceResponse)(nil), "WompattiService.ExecuteWolInterfaceResponse")
	proto.RegisterType((*FetchWolInterfaceByIdRequest)(nil), "WompattiService.FetchWolInterfaceByIdRequest")
	proto.RegisterType((*FetchWolInterfaceByIdResponse)(nil), "WompattiService.FetchWolInterfaceByIdResponse")
	proto.RegisterEnum("WompattiService.CreateWolInterfaceResponse_State", CreateWolInterfaceResponse_State_name, CreateWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.EditWolInterfaceResponse_State", EditWolInterfaceResponse_State_name, EditWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.RemoveWolInterfaceResponse_State", RemoveWolInterfaceResponse_State_name, RemoveWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.ExecuteWolInterfaceResponse_State", ExecuteWolInterfaceResponse_State_name, ExecuteWolInterfaceResponse_State_value)
	proto.RegisterEnum("WompattiService.FetchWolInterfaceByIdResponse_State", FetchWolInterfaceByIdResponse_State_name, FetchWolInterfaceByIdResponse_State_value)
}

func init() { proto.RegisterFile("wol_interface.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x4f, 0x8f, 0x9a, 0x60,
	0x10, 0xc6, 0xfb, 0x6a, 0x6c, 0xd3, 0xf1, 0x6f, 0x5e, 0x0f, 0x45, 0x5b, 0x1b, 0x43, 0x93, 0x86,
	0x13, 0x6d, 0x6d, 0xbf, 0x40, 0x8b, 0x58, 0xe9, 0x41, 0x13, 0xa8, 0xf1, 0x68, 0x10, 0xa6, 0x91,
	0x44, 0x7c, 0x29, 0xbc, 0x6a, 0x7b, 0xea, 0xa9, 0x97, 0xcd, 0x7e, 0xb1, 0x3d, 0xec, 0x69, 0xbf,
	0xd0, 0x46, 0x56, 0x0d, 0x08, 0x6c, 0xcc, 0x6a, 0xe2, 0x8d, 0x0c, 0xf3, 0x3c, 0x33, 0xcf, 0x8f,
	0x09, 0x50, 0x5f, 0xb3, 0xf9, 0xc4, 0x59, 0x70, 0xf4, 0x7f, 0x99, 0x16, 0xca, 0x9e, 0xcf, 0x38,
	0xa3, 0xd5, 0x31, 0x73, 0x3d, 0x93, 0x73, 0xc7, 0x40, 0x7f, 0xe5, 0x58, 0x28, 0x4e, 0xa1, 0x34,
	0x66, 0x73, 0x6d, 0xd7, 0x46, 0x2b, 0x90, 0x73, 0x6c, 0x81, 0xb4, 0x89, 0x54, 0xd6, 0x73, 0x8e,
	0x4d, 0x3f, 0x42, 0x1d, 0xf9, 0x0c, 0xfd, 0x05, 0xf2, 0x7d, 0x93, 0x66, 0x0b, 0xb9, 0xb0, 0x21,
	0xed, 0x15, 0xad, 0x41, 0xde, 0x35, 0x2d, 0x21, 0xdf, 0x26, 0x52, 0x49, 0xdf, 0x3c, 0x8a, 0xff,
	0xa0, 0xa1, 0xf8, 0x68, 0x72, 0x8c, 0x4e, 0xd2, 0xf1, 0xf7, 0x12, 0x03, 0x4e, 0xdf, 0x02, 0x58,
	0xcc, 0xf5, 0x96, 0x1c, 0x7d, 0x6d, 0x37, 0x38, 0x52, 0x39, 0xcb, 0x02, 0xb7, 0x04, 0x9a, 0x69,
	0x1b, 0x04, 0x1e, 0x5b, 0x04, 0x48, 0xbf, 0x43, 0x21, 0xe0, 0x26, 0xc7, 0x70, 0x7a, 0xa5, 0xf3,
	0x49, 0x3e, 0x80, 0x24, 0x67, 0x6b, 0x65, 0x63, 0x23, 0xd4, 0x1f, 0xf4, 0xf4, 0x2b, 0x94, 0xd6,
	0x91, 0xa6, 0x70, 0xc9, 0x62, 0xa7, 0x95, 0xf0, 0x8b, 0x39, 0xc5, 0x24, 0xe2, 0x3b, 0x28, 0x84,
	0x96, 0xb4, 0x08, 0x2f, 0x8c, 0x91, 0xa2, 0xa8, 0x86, 0x51, 0x7b, 0x46, 0xcb, 0xf0, 0x72, 0x30,
	0xfc, 0x39, 0xe9, 0x0d, 0x47, 0x83, 0x6e, 0x8d, 0x88, 0xff, 0x09, 0xbc, 0x52, 0x6d, 0x87, 0xa7,
	0xf1, 0x7c, 0x0f, 0x95, 0xa8, 0xe1, 0x9e, 0xe9, 0x41, 0xf5, 0x2c, 0x5c, 0x6f, 0x08, 0x08, 0xc9,
	0x3d, 0xb6, 0x54, 0xd5, 0x38, 0xd5, 0x0f, 0x09, 0x0a, 0x59, 0xca, 0xcb, 0x30, 0x55, 0xa0, 0xa1,
	0xa3, 0xcb, 0x56, 0x78, 0x02, 0x54, 0xf1, 0x8a, 0x40, 0x33, 0xcd, 0xe5, 0xd8, 0x43, 0xcb, 0xd6,
	0xc6, 0xa0, 0x1c, 0x97, 0xa8, 0x0b, 0x4d, 0xf5, 0x0f, 0x5a, 0x4b, 0x7e, 0x52, 0xa4, 0x6b, 0x02,
	0xaf, 0x53, 0x6d, 0xb6, 0x99, 0xfa, 0xf1, 0x4c, 0x9d, 0xe4, 0x67, 0xce, 0x16, 0x3f, 0x21, 0x54,
	0x1f, 0xde, 0xf4, 0x90, 0x5b, 0xb3, 0xa8, 0xdd, 0xb7, 0xbf, 0x9a, 0xbd, 0x8b, 0x25, 0x41, 0x35,
	0x1e, 0x80, 0x0b, 0xa4, 0x9d, 0x97, 0xca, 0xfa, 0x61, 0x59, 0xbc, 0x23, 0xd0, 0xca, 0xb0, 0xda,
	0x46, 0xfb, 0x11, 0x8f, 0xf6, 0x25, 0x11, 0xed, 0x51, 0xf9, 0x45, 0xce, 0x78, 0xfa, 0x3c, 0xfc,
	0xcf, 0x7f, 0xbe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xcf, 0x10, 0x8e, 0xfe, 0x05, 0x00, 0x00,
}
