// Code generated by protoc-gen-go.
// source: wol_interface.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateWolInterfaceResponse_State int32

const (
	CreateWolInterfaceResponse_SUCCESS   CreateWolInterfaceResponse_State = 0
	CreateWolInterfaceResponse_NOT_FOUND CreateWolInterfaceResponse_State = 1
)

var CreateWolInterfaceResponse_State_name = map[int32]string{
	0: "SUCCESS",
	1: "NOT_FOUND",
}
var CreateWolInterfaceResponse_State_value = map[string]int32{
	"SUCCESS":   0,
	"NOT_FOUND": 1,
}

func (x CreateWolInterfaceResponse_State) String() string {
	return proto.EnumName(CreateWolInterfaceResponse_State_name, int32(x))
}
func (CreateWolInterfaceResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{2, 0}
}

type WolInterface struct {
	Id                  uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *WolInterface) Reset()                    { *m = WolInterface{} }
func (m *WolInterface) String() string            { return proto.CompactTextString(m) }
func (*WolInterface) ProtoMessage()               {}
func (*WolInterface) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *WolInterface) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WolInterface) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *WolInterface) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type CreateWolInterfaceRequest struct {
	ComputerId          uint32 `protobuf:"varint,1,opt,name=computerId" json:"computerId,omitempty"`
	EthernetInterfaceId uint32 `protobuf:"varint,2,opt,name=ethernetInterfaceId" json:"ethernetInterfaceId,omitempty"`
	Mac                 []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *CreateWolInterfaceRequest) Reset()                    { *m = CreateWolInterfaceRequest{} }
func (m *CreateWolInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateWolInterfaceRequest) ProtoMessage()               {}
func (*CreateWolInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *CreateWolInterfaceRequest) GetComputerId() uint32 {
	if m != nil {
		return m.ComputerId
	}
	return 0
}

func (m *CreateWolInterfaceRequest) GetEthernetInterfaceId() uint32 {
	if m != nil {
		return m.EthernetInterfaceId
	}
	return 0
}

func (m *CreateWolInterfaceRequest) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type CreateWolInterfaceResponse struct {
	State        CreateWolInterfaceResponse_State `protobuf:"varint,1,opt,name=state,enum=WompattiService.CreateWolInterfaceResponse_State" json:"state,omitempty"`
	WolInterface *WolInterface                    `protobuf:"bytes,2,opt,name=wolInterface" json:"wolInterface,omitempty"`
}

func (m *CreateWolInterfaceResponse) Reset()                    { *m = CreateWolInterfaceResponse{} }
func (m *CreateWolInterfaceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateWolInterfaceResponse) ProtoMessage()               {}
func (*CreateWolInterfaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *CreateWolInterfaceResponse) GetState() CreateWolInterfaceResponse_State {
	if m != nil {
		return m.State
	}
	return CreateWolInterfaceResponse_SUCCESS
}

func (m *CreateWolInterfaceResponse) GetWolInterface() *WolInterface {
	if m != nil {
		return m.WolInterface
	}
	return nil
}

func init() {
	proto.RegisterType((*WolInterface)(nil), "WompattiService.WolInterface")
	proto.RegisterType((*CreateWolInterfaceRequest)(nil), "WompattiService.CreateWolInterfaceRequest")
	proto.RegisterType((*CreateWolInterfaceResponse)(nil), "WompattiService.CreateWolInterfaceResponse")
	proto.RegisterEnum("WompattiService.CreateWolInterfaceResponse_State", CreateWolInterfaceResponse_State_name, CreateWolInterfaceResponse_State_value)
}

func init() { proto.RegisterFile("wol_interface.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xcf, 0xcf, 0x89,
	0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x0f, 0xcf, 0xcf, 0x2d, 0x48, 0x2c, 0x29, 0xc9, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x55, 0x4a, 0xe2, 0xe2, 0x09, 0xcf, 0xcf, 0xf1, 0x84, 0x29, 0x13, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x32, 0xe0, 0x12, 0x4e, 0x2d,
	0xc9, 0x48, 0x2d, 0xca, 0x4b, 0x2d, 0x81, 0x2b, 0xf2, 0x4c, 0x91, 0x60, 0x02, 0x2b, 0xc0, 0x26,
	0x25, 0x24, 0xc0, 0xc5, 0x9c, 0x9b, 0x98, 0x2c, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x62,
	0x2a, 0xd5, 0x73, 0x49, 0x3a, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x22, 0xdb, 0x14, 0x94, 0x5a, 0x58,
	0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc7, 0xc5, 0x95, 0x9c, 0x9f, 0x5b, 0x50, 0x5a, 0x92, 0x5a, 0xe4,
	0x09, 0xb3, 0x18, 0x49, 0x84, 0x2a, 0x0e, 0x38, 0xcb, 0xc8, 0x25, 0x85, 0xcd, 0x05, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xee, 0x5c, 0xac, 0xc5, 0x25, 0x89, 0x25, 0xa9, 0x60, 0xdb, 0xf9,
	0x8c, 0x0c, 0xf5, 0xd0, 0x02, 0x49, 0x0f, 0xb7, 0x5e, 0xbd, 0x60, 0x90, 0xc6, 0x20, 0x88, 0x7e,
	0x21, 0x47, 0x2e, 0x9e, 0x72, 0x24, 0x45, 0x60, 0x47, 0x72, 0x1b, 0xc9, 0x62, 0x98, 0x87, 0x62,
	0x12, 0x8a, 0x16, 0x25, 0x65, 0x2e, 0x56, 0xb0, 0x91, 0x42, 0xdc, 0x5c, 0xec, 0xc1, 0xa1, 0xce,
	0xce, 0xae, 0xc1, 0xc1, 0x02, 0x0c, 0x42, 0xbc, 0x5c, 0x9c, 0x7e, 0xfe, 0x21, 0xf1, 0x6e, 0xfe,
	0xa1, 0x7e, 0x2e, 0x02, 0x8c, 0x49, 0x6c, 0xe0, 0xc8, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x85, 0xbf, 0xdc, 0xb4, 0xe3, 0x01, 0x00, 0x00,
}
