// Code generated by protoc-gen-go.
// source: wompatti_service.proto
// DO NOT EDIT!

package WompattiService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Wompatti service

type WompattiClient interface {
	// Fetch
	FetchTelnetInterfaces(ctx context.Context, in *FetchTelnetInterfacesRequest, opts ...grpc.CallOption) (*FetchTelnetInterfacesResponse, error)
	FetchTelnetInterfaceById(ctx context.Context, in *FetchTelnetInterfaceByIdRequest, opts ...grpc.CallOption) (*FetchTelnetInterfaceByIdResponse, error)
	FetchDevices(ctx context.Context, in *FetchDevicesRequest, opts ...grpc.CallOption) (*FetchDevicesResponse, error)
	FetchDeviceById(ctx context.Context, in *FetchDeviceByIdRequest, opts ...grpc.CallOption) (*FetchDeviceByIdResponse, error)
	FetchDeviceTypes(ctx context.Context, in *FetchDeviceTypesRequest, opts ...grpc.CallOption) (*FetchDeviceTypesResponse, error)
	FetchDeviceTypeById(ctx context.Context, in *FetchDeviceTypeByIdRequest, opts ...grpc.CallOption) (*FetchDeviceTypeByIdResponse, error)
	FetchCommands(ctx context.Context, in *FetchCommandsRequest, opts ...grpc.CallOption) (*FetchCommandsResponse, error)
	FetchCommandsByDeviceTypeId(ctx context.Context, in *FetchCommandsByDeviceTypeIdRequest, opts ...grpc.CallOption) (*FetchCommandsByDeviceTypeIdResponse, error)
	FetchCommandById(ctx context.Context, in *FetchCommandByIdRequest, opts ...grpc.CallOption) (*FetchCommandByIdResponse, error)
	FetchKeijos(ctx context.Context, in *FetchKeijosRequest, opts ...grpc.CallOption) (*FetchKeijosResponse, error)
	FetchKeijoById(ctx context.Context, in *FetchKeijoByIdRequest, opts ...grpc.CallOption) (*FetchKeijoByIdResponse, error)
	FetchSeveris(ctx context.Context, in *FetchSeverisRequest, opts ...grpc.CallOption) (*FetchSeverisResponse, error)
	FetchSeveriById(ctx context.Context, in *FetchSeveriByIdRequest, opts ...grpc.CallOption) (*FetchSeveriByIdResponse, error)
	FetchWolInterfaces(ctx context.Context, in *FetchWolInterfacesRequest, opts ...grpc.CallOption) (*FetchWolInterfacesResponse, error)
	FetchWolInterfaceById(ctx context.Context, in *FetchWolInterfaceByIdRequest, opts ...grpc.CallOption) (*FetchWolInterfaceByIdResponse, error)
	// Mutate
	CreateTelnetInterface(ctx context.Context, in *CreateTelnetInterfaceRequest, opts ...grpc.CallOption) (*CreateTelnetInterfaceResponse, error)
	EditTelnetInterface(ctx context.Context, in *EditTelnetInterfaceRequest, opts ...grpc.CallOption) (*EditTelnetInterfaceResponse, error)
	RemoveTelnetInterface(ctx context.Context, in *RemoveTelnetInterfaceRequest, opts ...grpc.CallOption) (*RemoveTelnetInterfaceResponse, error)
	CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	EditDevice(ctx context.Context, in *EditDeviceRequest, opts ...grpc.CallOption) (*EditDeviceResponse, error)
	RemoveDevice(ctx context.Context, in *RemoveDeviceRequest, opts ...grpc.CallOption) (*RemoveDeviceResponse, error)
	CreateDeviceType(ctx context.Context, in *CreateDeviceTypeRequest, opts ...grpc.CallOption) (*CreateDeviceTypeResponse, error)
	EditDeviceType(ctx context.Context, in *EditDeviceTypeRequest, opts ...grpc.CallOption) (*EditDeviceTypeResponse, error)
	RemoveDeviceType(ctx context.Context, in *RemoveDeviceTypeRequest, opts ...grpc.CallOption) (*RemoveDeviceTypeResponse, error)
	CreateCommand(ctx context.Context, in *CreateCommandRequest, opts ...grpc.CallOption) (*CreateCommandResponse, error)
	EditCommand(ctx context.Context, in *EditCommandRequest, opts ...grpc.CallOption) (*EditCommandReponse, error)
	RemoveCommand(ctx context.Context, in *RemoveCommandRequest, opts ...grpc.CallOption) (*RemoveCommandResponse, error)
	CreateKeijo(ctx context.Context, in *CreateKeijoRequest, opts ...grpc.CallOption) (*CreateKeijoResponse, error)
	EditKeijo(ctx context.Context, in *EditKeijoRequest, opts ...grpc.CallOption) (*EditKeijoResponse, error)
	RemoveKeijo(ctx context.Context, in *RemoveKeijoRequest, opts ...grpc.CallOption) (*RemoveKeijoResponse, error)
	CreateSeveri(ctx context.Context, in *CreateSeveriRequest, opts ...grpc.CallOption) (*CreateSeveriResponse, error)
	EditSeveri(ctx context.Context, in *EditSeveriRequest, opts ...grpc.CallOption) (*EditSeveriResponse, error)
	RemoveSeveri(ctx context.Context, in *RemoveSeveriRequest, opts ...grpc.CallOption) (*RemoveSeveriResponse, error)
	CreateWolInterface(ctx context.Context, in *CreateWolInterfaceRequest, opts ...grpc.CallOption) (*CreateWolInterfaceResponse, error)
	EditWolInterface(ctx context.Context, in *EditWolInterfaceRequest, opts ...grpc.CallOption) (*EditWolInterfaceResponse, error)
	RemoveWolInterface(ctx context.Context, in *RemoveWolInterfaceRequest, opts ...grpc.CallOption) (*RemoveWolInterfaceResponse, error)
	WakeupWolInterface(ctx context.Context, in *WakeupWolInterfaceRequest, opts ...grpc.CallOption) (*WakeupWolInterfaceResponse, error)
}

type wompattiClient struct {
	cc *grpc.ClientConn
}

func NewWompattiClient(cc *grpc.ClientConn) WompattiClient {
	return &wompattiClient{cc}
}

func (c *wompattiClient) FetchTelnetInterfaces(ctx context.Context, in *FetchTelnetInterfacesRequest, opts ...grpc.CallOption) (*FetchTelnetInterfacesResponse, error) {
	out := new(FetchTelnetInterfacesResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchTelnetInterfaces", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchTelnetInterfaceById(ctx context.Context, in *FetchTelnetInterfaceByIdRequest, opts ...grpc.CallOption) (*FetchTelnetInterfaceByIdResponse, error) {
	out := new(FetchTelnetInterfaceByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchTelnetInterfaceById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchDevices(ctx context.Context, in *FetchDevicesRequest, opts ...grpc.CallOption) (*FetchDevicesResponse, error) {
	out := new(FetchDevicesResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchDeviceById(ctx context.Context, in *FetchDeviceByIdRequest, opts ...grpc.CallOption) (*FetchDeviceByIdResponse, error) {
	out := new(FetchDeviceByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchDeviceById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchDeviceTypes(ctx context.Context, in *FetchDeviceTypesRequest, opts ...grpc.CallOption) (*FetchDeviceTypesResponse, error) {
	out := new(FetchDeviceTypesResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchDeviceTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchDeviceTypeById(ctx context.Context, in *FetchDeviceTypeByIdRequest, opts ...grpc.CallOption) (*FetchDeviceTypeByIdResponse, error) {
	out := new(FetchDeviceTypeByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchDeviceTypeById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchCommands(ctx context.Context, in *FetchCommandsRequest, opts ...grpc.CallOption) (*FetchCommandsResponse, error) {
	out := new(FetchCommandsResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchCommands", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchCommandsByDeviceTypeId(ctx context.Context, in *FetchCommandsByDeviceTypeIdRequest, opts ...grpc.CallOption) (*FetchCommandsByDeviceTypeIdResponse, error) {
	out := new(FetchCommandsByDeviceTypeIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchCommandsByDeviceTypeId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchCommandById(ctx context.Context, in *FetchCommandByIdRequest, opts ...grpc.CallOption) (*FetchCommandByIdResponse, error) {
	out := new(FetchCommandByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchCommandById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchKeijos(ctx context.Context, in *FetchKeijosRequest, opts ...grpc.CallOption) (*FetchKeijosResponse, error) {
	out := new(FetchKeijosResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchKeijos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchKeijoById(ctx context.Context, in *FetchKeijoByIdRequest, opts ...grpc.CallOption) (*FetchKeijoByIdResponse, error) {
	out := new(FetchKeijoByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchKeijoById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchSeveris(ctx context.Context, in *FetchSeverisRequest, opts ...grpc.CallOption) (*FetchSeverisResponse, error) {
	out := new(FetchSeverisResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchSeveris", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchSeveriById(ctx context.Context, in *FetchSeveriByIdRequest, opts ...grpc.CallOption) (*FetchSeveriByIdResponse, error) {
	out := new(FetchSeveriByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchSeveriById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchWolInterfaces(ctx context.Context, in *FetchWolInterfacesRequest, opts ...grpc.CallOption) (*FetchWolInterfacesResponse, error) {
	out := new(FetchWolInterfacesResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchWolInterfaces", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) FetchWolInterfaceById(ctx context.Context, in *FetchWolInterfaceByIdRequest, opts ...grpc.CallOption) (*FetchWolInterfaceByIdResponse, error) {
	out := new(FetchWolInterfaceByIdResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/fetchWolInterfaceById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateTelnetInterface(ctx context.Context, in *CreateTelnetInterfaceRequest, opts ...grpc.CallOption) (*CreateTelnetInterfaceResponse, error) {
	out := new(CreateTelnetInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createTelnetInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditTelnetInterface(ctx context.Context, in *EditTelnetInterfaceRequest, opts ...grpc.CallOption) (*EditTelnetInterfaceResponse, error) {
	out := new(EditTelnetInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editTelnetInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveTelnetInterface(ctx context.Context, in *RemoveTelnetInterfaceRequest, opts ...grpc.CallOption) (*RemoveTelnetInterfaceResponse, error) {
	out := new(RemoveTelnetInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeTelnetInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	out := new(CreateDeviceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditDevice(ctx context.Context, in *EditDeviceRequest, opts ...grpc.CallOption) (*EditDeviceResponse, error) {
	out := new(EditDeviceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveDevice(ctx context.Context, in *RemoveDeviceRequest, opts ...grpc.CallOption) (*RemoveDeviceResponse, error) {
	out := new(RemoveDeviceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateDeviceType(ctx context.Context, in *CreateDeviceTypeRequest, opts ...grpc.CallOption) (*CreateDeviceTypeResponse, error) {
	out := new(CreateDeviceTypeResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createDeviceType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditDeviceType(ctx context.Context, in *EditDeviceTypeRequest, opts ...grpc.CallOption) (*EditDeviceTypeResponse, error) {
	out := new(EditDeviceTypeResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editDeviceType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveDeviceType(ctx context.Context, in *RemoveDeviceTypeRequest, opts ...grpc.CallOption) (*RemoveDeviceTypeResponse, error) {
	out := new(RemoveDeviceTypeResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeDeviceType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateCommand(ctx context.Context, in *CreateCommandRequest, opts ...grpc.CallOption) (*CreateCommandResponse, error) {
	out := new(CreateCommandResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditCommand(ctx context.Context, in *EditCommandRequest, opts ...grpc.CallOption) (*EditCommandReponse, error) {
	out := new(EditCommandReponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveCommand(ctx context.Context, in *RemoveCommandRequest, opts ...grpc.CallOption) (*RemoveCommandResponse, error) {
	out := new(RemoveCommandResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateKeijo(ctx context.Context, in *CreateKeijoRequest, opts ...grpc.CallOption) (*CreateKeijoResponse, error) {
	out := new(CreateKeijoResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createKeijo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditKeijo(ctx context.Context, in *EditKeijoRequest, opts ...grpc.CallOption) (*EditKeijoResponse, error) {
	out := new(EditKeijoResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editKeijo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveKeijo(ctx context.Context, in *RemoveKeijoRequest, opts ...grpc.CallOption) (*RemoveKeijoResponse, error) {
	out := new(RemoveKeijoResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeKeijo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateSeveri(ctx context.Context, in *CreateSeveriRequest, opts ...grpc.CallOption) (*CreateSeveriResponse, error) {
	out := new(CreateSeveriResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createSeveri", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditSeveri(ctx context.Context, in *EditSeveriRequest, opts ...grpc.CallOption) (*EditSeveriResponse, error) {
	out := new(EditSeveriResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editSeveri", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveSeveri(ctx context.Context, in *RemoveSeveriRequest, opts ...grpc.CallOption) (*RemoveSeveriResponse, error) {
	out := new(RemoveSeveriResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeSeveri", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) CreateWolInterface(ctx context.Context, in *CreateWolInterfaceRequest, opts ...grpc.CallOption) (*CreateWolInterfaceResponse, error) {
	out := new(CreateWolInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/createWolInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) EditWolInterface(ctx context.Context, in *EditWolInterfaceRequest, opts ...grpc.CallOption) (*EditWolInterfaceResponse, error) {
	out := new(EditWolInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/editWolInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) RemoveWolInterface(ctx context.Context, in *RemoveWolInterfaceRequest, opts ...grpc.CallOption) (*RemoveWolInterfaceResponse, error) {
	out := new(RemoveWolInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/removeWolInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wompattiClient) WakeupWolInterface(ctx context.Context, in *WakeupWolInterfaceRequest, opts ...grpc.CallOption) (*WakeupWolInterfaceResponse, error) {
	out := new(WakeupWolInterfaceResponse)
	err := grpc.Invoke(ctx, "/WompattiService.Wompatti/wakeupWolInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wompatti service

type WompattiServer interface {
	// Fetch
	FetchTelnetInterfaces(context.Context, *FetchTelnetInterfacesRequest) (*FetchTelnetInterfacesResponse, error)
	FetchTelnetInterfaceById(context.Context, *FetchTelnetInterfaceByIdRequest) (*FetchTelnetInterfaceByIdResponse, error)
	FetchDevices(context.Context, *FetchDevicesRequest) (*FetchDevicesResponse, error)
	FetchDeviceById(context.Context, *FetchDeviceByIdRequest) (*FetchDeviceByIdResponse, error)
	FetchDeviceTypes(context.Context, *FetchDeviceTypesRequest) (*FetchDeviceTypesResponse, error)
	FetchDeviceTypeById(context.Context, *FetchDeviceTypeByIdRequest) (*FetchDeviceTypeByIdResponse, error)
	FetchCommands(context.Context, *FetchCommandsRequest) (*FetchCommandsResponse, error)
	FetchCommandsByDeviceTypeId(context.Context, *FetchCommandsByDeviceTypeIdRequest) (*FetchCommandsByDeviceTypeIdResponse, error)
	FetchCommandById(context.Context, *FetchCommandByIdRequest) (*FetchCommandByIdResponse, error)
	FetchKeijos(context.Context, *FetchKeijosRequest) (*FetchKeijosResponse, error)
	FetchKeijoById(context.Context, *FetchKeijoByIdRequest) (*FetchKeijoByIdResponse, error)
	FetchSeveris(context.Context, *FetchSeverisRequest) (*FetchSeverisResponse, error)
	FetchSeveriById(context.Context, *FetchSeveriByIdRequest) (*FetchSeveriByIdResponse, error)
	FetchWolInterfaces(context.Context, *FetchWolInterfacesRequest) (*FetchWolInterfacesResponse, error)
	FetchWolInterfaceById(context.Context, *FetchWolInterfaceByIdRequest) (*FetchWolInterfaceByIdResponse, error)
	// Mutate
	CreateTelnetInterface(context.Context, *CreateTelnetInterfaceRequest) (*CreateTelnetInterfaceResponse, error)
	EditTelnetInterface(context.Context, *EditTelnetInterfaceRequest) (*EditTelnetInterfaceResponse, error)
	RemoveTelnetInterface(context.Context, *RemoveTelnetInterfaceRequest) (*RemoveTelnetInterfaceResponse, error)
	CreateDevice(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error)
	EditDevice(context.Context, *EditDeviceRequest) (*EditDeviceResponse, error)
	RemoveDevice(context.Context, *RemoveDeviceRequest) (*RemoveDeviceResponse, error)
	CreateDeviceType(context.Context, *CreateDeviceTypeRequest) (*CreateDeviceTypeResponse, error)
	EditDeviceType(context.Context, *EditDeviceTypeRequest) (*EditDeviceTypeResponse, error)
	RemoveDeviceType(context.Context, *RemoveDeviceTypeRequest) (*RemoveDeviceTypeResponse, error)
	CreateCommand(context.Context, *CreateCommandRequest) (*CreateCommandResponse, error)
	EditCommand(context.Context, *EditCommandRequest) (*EditCommandReponse, error)
	RemoveCommand(context.Context, *RemoveCommandRequest) (*RemoveCommandResponse, error)
	CreateKeijo(context.Context, *CreateKeijoRequest) (*CreateKeijoResponse, error)
	EditKeijo(context.Context, *EditKeijoRequest) (*EditKeijoResponse, error)
	RemoveKeijo(context.Context, *RemoveKeijoRequest) (*RemoveKeijoResponse, error)
	CreateSeveri(context.Context, *CreateSeveriRequest) (*CreateSeveriResponse, error)
	EditSeveri(context.Context, *EditSeveriRequest) (*EditSeveriResponse, error)
	RemoveSeveri(context.Context, *RemoveSeveriRequest) (*RemoveSeveriResponse, error)
	CreateWolInterface(context.Context, *CreateWolInterfaceRequest) (*CreateWolInterfaceResponse, error)
	EditWolInterface(context.Context, *EditWolInterfaceRequest) (*EditWolInterfaceResponse, error)
	RemoveWolInterface(context.Context, *RemoveWolInterfaceRequest) (*RemoveWolInterfaceResponse, error)
	WakeupWolInterface(context.Context, *WakeupWolInterfaceRequest) (*WakeupWolInterfaceResponse, error)
}

func RegisterWompattiServer(s *grpc.Server, srv WompattiServer) {
	s.RegisterService(&_Wompatti_serviceDesc, srv)
}

func _Wompatti_FetchTelnetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTelnetInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchTelnetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchTelnetInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchTelnetInterfaces(ctx, req.(*FetchTelnetInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchTelnetInterfaceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTelnetInterfaceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchTelnetInterfaceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchTelnetInterfaceById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchTelnetInterfaceById(ctx, req.(*FetchTelnetInterfaceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchDevices(ctx, req.(*FetchDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchDeviceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchDeviceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchDeviceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchDeviceById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchDeviceById(ctx, req.(*FetchDeviceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchDeviceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchDeviceTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchDeviceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchDeviceTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchDeviceTypes(ctx, req.(*FetchDeviceTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchDeviceTypeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchDeviceTypeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchDeviceTypeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchDeviceTypeById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchDeviceTypeById(ctx, req.(*FetchDeviceTypeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchCommands(ctx, req.(*FetchCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchCommandsByDeviceTypeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCommandsByDeviceTypeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchCommandsByDeviceTypeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchCommandsByDeviceTypeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchCommandsByDeviceTypeId(ctx, req.(*FetchCommandsByDeviceTypeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchCommandById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCommandByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchCommandById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchCommandById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchCommandById(ctx, req.(*FetchCommandByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchKeijos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchKeijosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchKeijos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchKeijos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchKeijos(ctx, req.(*FetchKeijosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchKeijoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchKeijoByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchKeijoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchKeijoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchKeijoById(ctx, req.(*FetchKeijoByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchSeveris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSeverisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchSeveris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchSeveris",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchSeveris(ctx, req.(*FetchSeverisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchSeveriById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSeveriByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchSeveriById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchSeveriById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchSeveriById(ctx, req.(*FetchSeveriByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchWolInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchWolInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchWolInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchWolInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchWolInterfaces(ctx, req.(*FetchWolInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_FetchWolInterfaceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchWolInterfaceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).FetchWolInterfaceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/FetchWolInterfaceById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).FetchWolInterfaceById(ctx, req.(*FetchWolInterfaceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateTelnetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTelnetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateTelnetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateTelnetInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateTelnetInterface(ctx, req.(*CreateTelnetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditTelnetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTelnetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditTelnetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditTelnetInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditTelnetInterface(ctx, req.(*EditTelnetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveTelnetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTelnetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveTelnetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveTelnetInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveTelnetInterface(ctx, req.(*RemoveTelnetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateDevice(ctx, req.(*CreateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditDevice(ctx, req.(*EditDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveDevice(ctx, req.(*RemoveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateDeviceType(ctx, req.(*CreateDeviceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDeviceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditDeviceType(ctx, req.(*EditDeviceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeviceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveDeviceType(ctx, req.(*RemoveDeviceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateCommand(ctx, req.(*CreateCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditCommand(ctx, req.(*EditCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveCommand(ctx, req.(*RemoveCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateKeijo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeijoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateKeijo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateKeijo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateKeijo(ctx, req.(*CreateKeijoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditKeijo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditKeijoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditKeijo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditKeijo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditKeijo(ctx, req.(*EditKeijoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveKeijo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveKeijoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveKeijo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveKeijo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveKeijo(ctx, req.(*RemoveKeijoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateSeveri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeveriRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateSeveri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateSeveri",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateSeveri(ctx, req.(*CreateSeveriRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditSeveri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSeveriRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditSeveri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditSeveri",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditSeveri(ctx, req.(*EditSeveriRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveSeveri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSeveriRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveSeveri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveSeveri",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveSeveri(ctx, req.(*RemoveSeveriRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_CreateWolInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWolInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).CreateWolInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/CreateWolInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).CreateWolInterface(ctx, req.(*CreateWolInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_EditWolInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditWolInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).EditWolInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/EditWolInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).EditWolInterface(ctx, req.(*EditWolInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_RemoveWolInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWolInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).RemoveWolInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/RemoveWolInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).RemoveWolInterface(ctx, req.(*RemoveWolInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wompatti_WakeupWolInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WakeupWolInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WompattiServer).WakeupWolInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WompattiService.Wompatti/WakeupWolInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WompattiServer).WakeupWolInterface(ctx, req.(*WakeupWolInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wompatti_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WompattiService.Wompatti",
	HandlerType: (*WompattiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fetchTelnetInterfaces",
			Handler:    _Wompatti_FetchTelnetInterfaces_Handler,
		},
		{
			MethodName: "fetchTelnetInterfaceById",
			Handler:    _Wompatti_FetchTelnetInterfaceById_Handler,
		},
		{
			MethodName: "fetchDevices",
			Handler:    _Wompatti_FetchDevices_Handler,
		},
		{
			MethodName: "fetchDeviceById",
			Handler:    _Wompatti_FetchDeviceById_Handler,
		},
		{
			MethodName: "fetchDeviceTypes",
			Handler:    _Wompatti_FetchDeviceTypes_Handler,
		},
		{
			MethodName: "fetchDeviceTypeById",
			Handler:    _Wompatti_FetchDeviceTypeById_Handler,
		},
		{
			MethodName: "fetchCommands",
			Handler:    _Wompatti_FetchCommands_Handler,
		},
		{
			MethodName: "fetchCommandsByDeviceTypeId",
			Handler:    _Wompatti_FetchCommandsByDeviceTypeId_Handler,
		},
		{
			MethodName: "fetchCommandById",
			Handler:    _Wompatti_FetchCommandById_Handler,
		},
		{
			MethodName: "fetchKeijos",
			Handler:    _Wompatti_FetchKeijos_Handler,
		},
		{
			MethodName: "fetchKeijoById",
			Handler:    _Wompatti_FetchKeijoById_Handler,
		},
		{
			MethodName: "fetchSeveris",
			Handler:    _Wompatti_FetchSeveris_Handler,
		},
		{
			MethodName: "fetchSeveriById",
			Handler:    _Wompatti_FetchSeveriById_Handler,
		},
		{
			MethodName: "fetchWolInterfaces",
			Handler:    _Wompatti_FetchWolInterfaces_Handler,
		},
		{
			MethodName: "fetchWolInterfaceById",
			Handler:    _Wompatti_FetchWolInterfaceById_Handler,
		},
		{
			MethodName: "createTelnetInterface",
			Handler:    _Wompatti_CreateTelnetInterface_Handler,
		},
		{
			MethodName: "editTelnetInterface",
			Handler:    _Wompatti_EditTelnetInterface_Handler,
		},
		{
			MethodName: "removeTelnetInterface",
			Handler:    _Wompatti_RemoveTelnetInterface_Handler,
		},
		{
			MethodName: "createDevice",
			Handler:    _Wompatti_CreateDevice_Handler,
		},
		{
			MethodName: "editDevice",
			Handler:    _Wompatti_EditDevice_Handler,
		},
		{
			MethodName: "removeDevice",
			Handler:    _Wompatti_RemoveDevice_Handler,
		},
		{
			MethodName: "createDeviceType",
			Handler:    _Wompatti_CreateDeviceType_Handler,
		},
		{
			MethodName: "editDeviceType",
			Handler:    _Wompatti_EditDeviceType_Handler,
		},
		{
			MethodName: "removeDeviceType",
			Handler:    _Wompatti_RemoveDeviceType_Handler,
		},
		{
			MethodName: "createCommand",
			Handler:    _Wompatti_CreateCommand_Handler,
		},
		{
			MethodName: "editCommand",
			Handler:    _Wompatti_EditCommand_Handler,
		},
		{
			MethodName: "removeCommand",
			Handler:    _Wompatti_RemoveCommand_Handler,
		},
		{
			MethodName: "createKeijo",
			Handler:    _Wompatti_CreateKeijo_Handler,
		},
		{
			MethodName: "editKeijo",
			Handler:    _Wompatti_EditKeijo_Handler,
		},
		{
			MethodName: "removeKeijo",
			Handler:    _Wompatti_RemoveKeijo_Handler,
		},
		{
			MethodName: "createSeveri",
			Handler:    _Wompatti_CreateSeveri_Handler,
		},
		{
			MethodName: "editSeveri",
			Handler:    _Wompatti_EditSeveri_Handler,
		},
		{
			MethodName: "removeSeveri",
			Handler:    _Wompatti_RemoveSeveri_Handler,
		},
		{
			MethodName: "createWolInterface",
			Handler:    _Wompatti_CreateWolInterface_Handler,
		},
		{
			MethodName: "editWolInterface",
			Handler:    _Wompatti_EditWolInterface_Handler,
		},
		{
			MethodName: "removeWolInterface",
			Handler:    _Wompatti_RemoveWolInterface_Handler,
		},
		{
			MethodName: "wakeupWolInterface",
			Handler:    _Wompatti_WakeupWolInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wompatti_service.proto",
}

func init() { proto.RegisterFile("wompatti_service.proto", fileDescriptor14) }

var fileDescriptor14 = []byte{
	// 812 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x97, 0xdd, 0x6e, 0xd3, 0x4e,
	0x10, 0xc5, 0xff, 0xbd, 0xf9, 0x0b, 0xb6, 0x5f, 0xb0, 0x15, 0x55, 0x15, 0x24, 0x24, 0xda, 0xd2,
	0x0f, 0x4a, 0x23, 0xa0, 0x3c, 0x41, 0x03, 0x48, 0x15, 0x77, 0x6e, 0xa5, 0x08, 0x24, 0x14, 0x4c,
	0x32, 0x51, 0x4d, 0x93, 0xd8, 0xd8, 0x9b, 0x84, 0x5c, 0x72, 0xcb, 0x0b, 0xf1, 0x7a, 0xc8, 0xbb,
	0xde, 0xf5, 0xd8, 0xbb, 0xe3, 0x75, 0x2f, 0xe3, 0xf9, 0xf9, 0x9c, 0x99, 0x53, 0xef, 0xac, 0xca,
	0x76, 0x97, 0xf1, 0x34, 0x09, 0x85, 0x88, 0x06, 0x19, 0xa4, 0x8b, 0x68, 0x08, 0xdd, 0x24, 0x8d,
	0x45, 0xcc, 0xb7, 0xfb, 0xc5, 0xf3, 0x6b, 0xf5, 0xb8, 0xb3, 0x35, 0x8c, 0xa7, 0xc9, 0x5c, 0x40,
	0xaa, 0x80, 0xce, 0xe3, 0x11, 0xe4, 0xcf, 0x07, 0xd1, 0x6c, 0x1c, 0x17, 0x8f, 0xb6, 0xef, 0x60,
	0x35, 0x58, 0x84, 0x93, 0x79, 0x21, 0xd2, 0x59, 0x0f, 0x53, 0x21, 0xe6, 0xc5, 0x8f, 0x0d, 0xf5,
	0x42, 0xf1, 0x6b, 0x0f, 0xc4, 0x2d, 0xa4, 0x33, 0x10, 0x83, 0x68, 0x26, 0x20, 0x1d, 0x87, 0xa6,
	0xb2, 0xb3, 0x8c, 0x27, 0xd6, 0x43, 0xed, 0x26, 0x56, 0x89, 0x7e, 0xb4, 0x9b, 0x41, 0x1a, 0x85,
	0x36, 0xba, 0x2b, 0x60, 0xe2, 0xd2, 0xdd, 0x1c, 0xc6, 0xd3, 0x69, 0x38, 0x1b, 0xe9, 0xde, 0xee,
	0x20, 0xfa, 0xa1, 0x3b, 0xdf, 0xc8, 0x60, 0x01, 0x69, 0xa4, 0x7e, 0xbd, 0xfd, 0xfb, 0x8c, 0x3d,
	0xd0, 0xe3, 0xf3, 0x5f, 0xec, 0xc9, 0x18, 0xc4, 0xf0, 0xf6, 0x46, 0xaa, 0x5e, 0x69, 0xd1, 0x8c,
	0x9f, 0x77, 0x6b, 0x11, 0x75, 0x3f, 0xba, 0xb8, 0x00, 0x7e, 0xce, 0x21, 0x13, 0x9d, 0x6e, 0x5b,
	0x3c, 0x4b, 0xe2, 0x59, 0x06, 0xfb, 0xff, 0xf1, 0xdf, 0x6b, 0x6c, 0xcf, 0x65, 0x7d, 0xb9, 0xba,
	0x1a, 0xf1, 0xd7, 0xad, 0xe4, 0x72, 0x54, 0x37, 0xf0, 0xe6, 0x1e, 0x6f, 0x98, 0x1e, 0xbe, 0xb2,
	0x0d, 0xd9, 0xc2, 0x7b, 0x19, 0x7f, 0xc6, 0x0f, 0xdd, 0x22, 0x45, 0x59, 0x5b, 0xbd, 0xf0, 0x50,
	0x46, 0x7e, 0xcc, 0xb6, 0x91, 0xbc, 0x1c, 0xec, 0xb8, 0xe9, 0x5d, 0x3c, 0xcf, 0x89, 0x1f, 0x34,
	0x3e, 0x11, 0x7b, 0x84, 0x7c, 0x6e, 0x56, 0x09, 0x64, 0xbc, 0xf1, 0x7d, 0x89, 0x68, 0xa7, 0xd3,
	0x16, 0xa4, 0xb1, 0x4a, 0xd9, 0x4e, 0xcd, 0x4a, 0x8e, 0x75, 0xe6, 0xd3, 0xc0, 0xa3, 0xbd, 0x6a,
	0x07, 0x1b, 0xcf, 0x6f, 0x6c, 0x53, 0x7a, 0xf6, 0xd4, 0x17, 0x9e, 0x71, 0xe2, 0x0f, 0xa0, 0xeb,
	0xda, 0xe7, 0xc8, 0x87, 0x19, 0x87, 0x3f, 0x6b, 0xec, 0x69, 0xc5, 0xe2, 0x72, 0x55, 0x76, 0x73,
	0x35, 0xe2, 0x17, 0xcd, 0x4a, 0x55, 0x5a, 0xdb, 0xbf, 0xbb, 0xdf, 0x4b, 0xd6, 0x5f, 0xb3, 0x00,
	0x65, 0xbe, 0x27, 0x8d, 0x5a, 0x38, 0xdc, 0xd3, 0x16, 0xa4, 0xb1, 0xfa, 0xc2, 0xd6, 0xa5, 0xd5,
	0xa7, 0x7c, 0x59, 0x64, 0xfc, 0xc0, 0xfd, 0xae, 0xaa, 0x6a, 0x83, 0xc3, 0x66, 0xc8, 0x68, 0x0f,
	0xd9, 0x56, 0xa9, 0x2d, 0x87, 0x38, 0x6a, 0x78, 0x13, 0x8f, 0x70, 0xec, 0xe5, 0xac, 0x03, 0x7c,
	0x2d, 0x17, 0x1c, 0x79, 0x80, 0x8b, 0xb2, 0xe7, 0x00, 0x1b, 0xca, 0x3a, 0xc0, 0xaa, 0xd2, 0x74,
	0x80, 0x4b, 0xc2, 0x73, 0x80, 0x31, 0x68, 0x7c, 0x62, 0xc6, 0xa5, 0x4f, 0x3f, 0x9e, 0xa0, 0x15,
	0xfc, 0xd2, 0xad, 0x50, 0x81, 0xb4, 0xdb, 0x59, 0x2b, 0xd6, 0x18, 0xea, 0xb5, 0x8f, 0xeb, 0x72,
	0xbc, 0x73, 0xbf, 0x0e, 0x1e, 0xb2, 0xdb, 0x16, 0xc7, 0xce, 0xc3, 0x14, 0x42, 0x01, 0xb5, 0xcd,
	0xec, 0x70, 0xee, 0xb9, 0x38, 0xda, 0x99, 0xc0, 0xf1, 0xea, 0x82, 0x51, 0x24, 0xea, 0xbe, 0x76,
	0x72, 0x1f, 0x6c, 0x8a, 0x5e, 0x5d, 0x4e, 0x18, 0x4f, 0x9b, 0xc2, 0x34, 0x5e, 0xb4, 0x98, 0x36,
	0x70, 0x71, 0xf4, 0xb4, 0x04, 0x8e, 0x4f, 0x86, 0xca, 0x59, 0x6d, 0x19, 0xc7, 0xc9, 0xe8, 0xa1,
	0x32, 0x7d, 0x32, 0xaa, 0x94, 0x91, 0xef, 0x33, 0x96, 0x87, 0x59, 0x88, 0xef, 0x3b, 0x63, 0xa9,
	0x4a, 0x1f, 0x34, 0x32, 0xb8, 0x6f, 0x95, 0x18, 0xd9, 0x77, 0x80, 0xca, 0x74, 0xdf, 0x55, 0x0a,
	0x2f, 0x57, 0x1c, 0x4b, 0xbe, 0x7c, 0x1d, 0xcb, 0xb5, 0x57, 0x43, 0xe8, 0xe5, 0x6a, 0x93, 0x78,
	0x01, 0x96, 0x11, 0x49, 0xa3, 0xa3, 0x86, 0x08, 0xb0, 0xcd, 0xb1, 0x97, 0xc3, 0xf3, 0xe0, 0xb8,
	0x88, 0x79, 0x82, 0x1a, 0x42, 0xcf, 0x63, 0x93, 0xf8, 0x1a, 0x56, 0xd1, 0x15, 0x77, 0x09, 0xa7,
	0x3e, 0x96, 0xa2, 0x4e, 0x5f, 0xc3, 0x35, 0xcc, 0x38, 0x7c, 0x66, 0xeb, 0x79, 0x62, 0x5a, 0xdf,
	0xfd, 0xc5, 0xd4, 0xd4, 0x3d, 0x10, 0x6a, 0x5e, 0xe5, 0x44, 0x37, 0x1f, 0xe0, 0x3a, 0xdd, 0x7c,
	0x0d, 0xc3, 0x77, 0xa9, 0x8a, 0x47, 0xde, 0x53, 0x8e, 0xe6, 0x7b, 0x65, 0x95, 0xbe, 0x4b, 0x2b,
	0x90, 0xd1, 0xbe, 0x61, 0x0f, 0xf3, 0x60, 0x94, 0xf2, 0x73, 0xe7, 0xc4, 0x15, 0xdd, 0xfd, 0x26,
	0x04, 0x77, 0xac, 0x32, 0xa1, 0x3a, 0x0e, 0xca, 0x2a, 0xdd, 0x71, 0x05, 0xb2, 0xd7, 0x8f, 0xba,
	0xef, 0xc8, 0xf5, 0xa3, 0xca, 0xbe, 0xf5, 0xa3, 0xa9, 0xfa, 0xfa, 0x29, 0xc4, 0xdd, 0xe3, 0x56,
	0xa5, 0x0f, 0x1a, 0x19, 0x7b, 0xfd, 0x90, 0x7d, 0x07, 0xa8, 0xec, 0x5b, 0x3f, 0x96, 0x7c, 0xcc,
	0xb8, 0x8a, 0x05, 0xdf, 0x90, 0x8e, 0x8b, 0xbe, 0x67, 0x41, 0xf4, 0x45, 0xef, 0x62, 0xf1, 0x7e,
	0xc8, 0x83, 0xaa, 0xd8, 0x9d, 0x38, 0xa3, 0x70, 0x99, 0x9d, 0xb6, 0x20, 0xf1, 0x6c, 0x2a, 0x3a,
	0xcf, 0x6c, 0x81, 0x05, 0xd1, 0xb3, 0xb9, 0x58, 0x6c, 0xb8, 0x0c, 0xef, 0x60, 0x9e, 0x78, 0x0c,
	0xfb, 0x16, 0x44, 0x1b, 0xba, 0x58, 0x6d, 0xf8, 0xfd, 0x7f, 0xf9, 0x0f, 0xf4, 0xc5, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0a, 0x83, 0x34, 0x08, 0x56, 0x10, 0x00, 0x00,
}
